### PR TITLE
Fix OOM detection for pods with restartPolicy: Never

### LINKED ISSUE #6236: VPA doesn't provide any recommendations when CronJob is in OOMKill crash loop
**Which component are you using?**:

 vertical-pod-autoscaler

**What version of the component are you using?**:

Component version: 1.0.0

**What k8s version are you using (`kubectl version`)?**:

v1.25.14-eks-f8587cb

**What environment is this in?**:

AWS EKS

**What did you expect to happen?**:

VPA should track CronJob OOMKilled events and adjust resources requests and limits.

**What happened instead?**:

VPA doesn't react to job OOMKilled events 

**How to reproduce it (as minimally and precisely as possible)**:

```YAML
apiVersion: batch/v1
kind: CronJob
metadata:
  name: oomkilled
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        app: oomkilled
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - image: gcr.io/google-containers/stress:v1
            name: stress
            command: [ "/stress"]
            args: 
              - "--mem-total"
              - "10485800000"
              - "--logtostderr"
              - "--mem-alloc-size"
              - "100000"
            resources:
              requests:
                memory: 100Mi
                cpu: 5m
              limits:
                memory: 1Gi

---

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: oomkilled
spec:
  targetRef:
    apiVersion: "batch/v1"
    kind: CronJob
    name: oomkilled
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 50m
          memory: 10Mi
        maxAllowed:
          cpu: 1
          memory: 2Gi
        controlledResources: ["cpu", "memory"]
```

### PR DESCRIPTION
**Pull request by tkukushkin**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Current approach of detection OOMs is based on `RestartCount` and `status.containerStatuses.lastState` of pod. But if pod doesn't restart (`restartPolicy: Never`), pod doesn't have `lastState` and `RestartCount` isn't increased.

I changed it to check `status.containerStatuses.state.terminated` instead. If container's status changes from running to terminated with `OOMKilled` reason, we record OOM. I believe this approach works for regular pods that can restart and works for not restarting pods as well.

If it is regular pod which restarts:
1. Container is running (`status.containerStatuses.state.terminated == nil`)
2. Container is OOM killed (`status.containerStatuses.state.terminated.reason == "OOMKilled"`)
3. We record OOM
4. Container restarts, it's `state.terminated` resets (`status.containerStatuses.state.terminated == nil`)
6. See 1.

If it is pod which doesn't restart:
1. Container is running (`status.containerStatuses.state.terminated == nil`)
2. Container is OOM killed (`status.containerStatuses.state.terminated.reason == "OOMKilled"`)
3. We record OOM

#### Which issue(s) this PR fixes:

Fixes #6236

#### Does this PR introduce a user-facing change?

```release-note
- Fixed OOM detection for pods with `restartPolicy: Never`
```

### CODE REVIEW

**Comment by voelzmo** [comment]
I'm not sure if it is safe to switch entirely to `.status.state` and disregard the `restartCount` event for restartable Containers.

Looking at the docs for https://pkg.go.dev/k8s.io/client-go@v0.33.0/tools/cache#ResourceEventHandler it states that events may be combined if they happen quickly after another
> `OnUpdate` is called when an object is modified. Note that oldObj is the last known state of the object-- it is possible that several changes were combined together, so you can't use this to see every single change. OnUpdate is also called when a re-list happens, and it will get called even if nothing changed. This is useful for periodically evaluating or syncing something.

After merging the PR, the oom observer only considers Pod update events that updated `.status.state.terminated` from `nil` in the `oldObject` to non-nil in the `object`. This works iff:
* in between two OOMKills an update event from `.status.state.terminated` to `.status.state.running` is observed – so the Pod has to be running "long enough", and I don't know how long that might be
* for Containers which _are restartable_, the Controller doesn't restart "too quickly", such that the observer can get the event where `.status.state.terminated` is non-nil

Maybe we need to consider the Pod's [restartPolicy](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy) and choose which fields to read in the Container's status?

What do the others think, @raywainman @adrianmoisey @omerap12?

**Comment by tkukushkin** [comment]
> events may be combined if they happen quickly after another

If events may be combined, this approach may not work in some edge cases, I didn't know about this behaviour. Isn't it possible to disable it somehow?

By the way, we've been using this approach in production for several months and haven't noticed any problems like that, but of course we can't be sure it **always** works like expected.

Also, I could be wrong, but it seems to me that the `restartCount` tracking has another flaw. `restartCount` is increased only when container is actually restarted, but there is backoff time as weel, so OOM may be recorded later, sometimes much later.

**Comment by voelzmo** [comment]
> OOM may be recorded later, sometimes much later.

That definitely is an issue! I think we had people report instances where OOMKill events had been dropped with 
`OOM event will be discarded - it is too old` which might happen if the aggregation window changed between OOMKill and the Pod restart. Not sure if there might be other causes for this to occur, though.

**Comment by omerap12** [comment]
> Maybe we need to consider the Pod's [restartPolicy](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy) and choose which fields to read in the Container's status?

Yeah I agree, I think we should define the behavior based on the `restartPolicy`:

For `restartPolicy: Never`:
- Use `containerStatus.State.Terminated` check

For `restartPolicy: Always/OnFailure`:
- Primary: Use `RestartCount` +` LastTerminationState` check
- Fallback: Use `State.Terminated` check
  (to catch OOMs that might be missed due to backoff/aggregation window issues)

**Comment by LEDfan** [comment]
> Is seems it's not possible. But if this is the only problem, is it possible to implement a custom watcher that won't have this behaviour? It might be technically more difficult, but would it work better and handle all cases?

I believe that the k8s api server combines the events, and therefore it's not possible to do this client side. Even if it would be possible client side, I think the proposed alternatives are better.

We are also running into this issue, and would be very happy if it would be fixed. If you don't have the time or resources to continue with this PR, I could attempt to implement the suggested changes, although I have very little go experience.

**Comment by tkukushkin** [comment]
> I believe that the k8s api server combines the events

I'm not so sure. From https://kubernetes.io/docs/reference/using-api/api-concepts/:

> The overall watch mechanism allows a client to fetch the current state and then subscribe to subsequent changes, **without missing any events**.

**Comment by tkukushkin** [comment]
And I don't think proposed alternatives are better, it's strange to use a different approach just because `ResourceEventHandler` can't deliver all change events.

**Comment by LEDfan** [comment]
> I'm not so sure. From https://kubernetes.io/docs/reference/using-api/api-concepts/:

Ah yes, you are right, it appears to be caused by the use of `DeltaFifo` queues in the client.

> And I don't think proposed alternatives are better, it's strange to use a different approach just because ResourceEventHandler can't deliver all change events.

But implementing a `ResourceEventHandler` (or any other watcher) that guarantees that all events are handled is difficult. Even if a watch request sends all the events, the request  will at some point stop and needs to be restarted. This can trigger a watch+list and therefore it's almost guaranteed that some events are lost.

In addition, a `pod` resource is very frequently updated throughout it's lifecycle, I don't think it makes sense to have VPA process every individual update event. Hence the use of deltafifo queues will prevent performance issues in the VPA component.

I'm not an expert on these internal details, so I cannot make a good decisions here. 
Maybe the maintainers that posted earlier can share there thoughts which approach should be used?

**Comment by tkukushkin** [comment]
It turned out it's not as simple as I thought. I'm developing a small Prometheus exporter in our company, which exports a signle metric: `container_terminations_total{namespace,pod,container,reason,exit_code}` – the number of all container terminations (excluding pods that are in the process of deletion). So I had to implement a similar algorithm for detecting container terminations. Even though I'm using Python, where the Kubernetes client doesn't combine events, I noticed watches still miss some state transitions.

1. If container fails to fast, it never reaches `running` state. It transitions directly from `terminated` (or `waiting`) to another `terminated` state while increasing `restartCount`. Example:
   ```bash
   kubectl run --image busybox --overrides='{"spec": {"containers": [{"name": "test", "resources": {"limits": {"memory": "128Mi"}}}]}}' --override-type strategic test -- sh -c 'for b in {0..99999999}; do a=$b$a; done'
   ```
   You can inspect events by running:
   ```bash
   kubectl get pods --watch -o json | jq '.status.containerStatuses[0]'
   ```

2. Sometimes containers skip the `terminated` state entirely and transition from `running` to `running` with increased `restartCount`. I observed this in 100% of cases when containers were restarted by liveness probes. In such cases, only `lastState` contains information about the termination. Example:
   ```bash
   kubectl run --image busybox --overrides='{"spec": {"containers": [{"name": "test", "livenessProbe": {"periodSeconds": 3, "exec": {"command": ["ls", "/not-existing-file"]}}}]}}' --override-type strategic test -- sh -c 'sleep 10000'
   ```

   I'm not sure whether this happens during OOM kills, I haven't seen such cases yet, but supporting it is straightforward.


I tried to build an algorithm that does not rely on `restartPolicy` and works for any pod. Currently, the logic looks like this:

```python
if container.state.terminated and container.state.terminated.reason == "OOMKilled" (
    not old_container.state.terminated
    or container.restart_count > old_container.restart_count
):
    # use `state`
    self._metrics[
        pod.namespace,
        pod.name,
        container_name,
        container.state.terminated.reason,
        str(container.state.terminated.exit_code),
    ] += 1

if (
    container.state.running
    and not old_container.state.terminated
    and container.restart_count > old_container.restart_count
    and container.last_state.terminated
):
    # use `lastState`
    self._metrics[
        pod.namespace,
        pod.name,
        container_name,
        container.last_state.terminated.reason,
        str(container.last_state.terminated.exit_code),
    ] += 1
```

I believe similar approach can also be used in VPA to reliably detect OOM problems, I will update the PR in the near future.

**Comment by adrianmoisey** [comment]
/remove-lifecycle rotten

Sorry for the delay, I still plan on getting to this PR

File: vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go [hunk 1]
```diff
@@ -148,33 +148,63 @@ func (o *observer) OnUpdate(oldObj, newObj any) {
...
+
+		// Check if container changes state from non-Terminated to Terminated
+		// with OOMKilled reason. Also if container fails too fast, it may
+		// skip Running state and change state direcly to Terminated
+		// (from Terminated or Waiting) with increased RestartCount.
+		// We check for this case as well.
+		isNewOOM := containerStatus.State.Terminated != nil &&
+			containerStatus.State.Terminated.Reason == "OOMKilled" &&
+			(oldStatus.State.Terminated == nil ||
+				containerStatus.RestartCount > oldStatus.RestartCount)
```
Comment (adrianmoisey) [inline vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go]: Since both `oldStatus.State.Terminated == nil` and `containerStatus.RestartCount > oldStatus.RestartCount` are used in isNewOOM and isPreviousOOM, could this be moved out to their own variables?

It may make this easier to read

File: vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go [hunk 2]
```diff
@@ -148,33 +148,63 @@ func (o *observer) OnUpdate(oldObj, newObj any) {
...
+		if isNewOOM {
+			oomState = containerStatus.State.Terminated
+		} else {
+			oomState = containerStatus.LastTerminationState.Terminated
+		}
+
+		oldSpec := findSpec(containerStatus.Name, oldPod.Spec.Containers)
+		if oldSpec == nil {
+			continue
 		}
```
Comment (adrianmoisey) [inline vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go]: What is the purpose of this check?

Comment (adrianmoisey) [reply vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go]: Oh, is this testing that previous pod has the container of the current pod?
If so, can you rename the variable and add a comment?

File: vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go (hunk 1 above)
Comment (tkukushkin) [reply vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go]: Done in 5e930a4 — extracted `oldNotTerminated` and `restartCountIncreased` as shared variables.

File: vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go (hunk 2 above)
Comment (tkukushkin) [reply vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go]: Good catch. The check is actually dead code: since 204ac568 ("Also read resources from containerStatus in oom observer") the memory is read via `resourcehelpers.ContainerRequestsAndLimits(name, pod)` instead of `oldSpec.Resources`, and the `oldSpec` variable hasn't been used for anything other than the nil check itself. Since we also already `continue` when `oldStatus == nil` (and a container present in `Status.ContainerStatuses` has to exist in `Spec.Containers`), the check is redundant.

Removed it (and the now-unused `findSpec` helper) in 5e930a4.

While touching this block I also noticed `ContainerRequestsAndLimits` was always being called with `oldPod`, which isn't quite right now that we have two branches: for `isNewOOM` the OOM just happened on the container currently in `newPod` (its resources should be read from there), and for `isPreviousOOM` the OOM happened on the pre-restart instance, whose resources are those of `oldPod`. Fixed in the same commit and adjusted the tests.

**Comment by adrianmoisey** [comment]
From my understanding and testing, this seems to improve OOM detection correctly.

/cc maxcao13 

Max, any chance you have some cycles to look a this too?

File: vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go [hunk 3]
```diff
@@ -148,33 +139,69 @@ func (o *observer) OnUpdate(oldObj, newObj any) {
...
+			(oldNotTerminated || restartCountIncreased)
+
+		// If controller restarts container, it may skip
+		// Terminated state and change directly from Running
+		// to Running with increased RestartCount. In this
+		// case we check LastTerminationState.
+		isPreviousOOM := containerStatus.State.Running != nil &&
+			oldNotTerminated &&
+			restartCountIncreased &&
 			containerStatus.LastTerminationState.Terminated != nil &&
```
Comment (maxcao13) [inline vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go:168]: From manually testing and debug statements, I think there's a bug if the container goes into CrashLoopBackoff (waiting state).

1. Container A transitions (observed) `Running` -> `Terminated (OOMKill)`, restartCount 0 -> 0, so `isNewOOM` will trigger and record an OOM sample.
2. Container A transitions (observed) `Terminated` -> `Waiting (CrashLoopBackoff)`, restartCount 0 -> 0, and both the previousOom and newOom will skip since state is now `Waiting` and neither `Terminated` or `Running`.
3. Container A transitions (observed) `Waiting` -> `Running` , restartCount 0 -> 1, but here the `lastState.terminated.reason==OOMKill` so `isPreviousOOM` triggers, because `isPreviousOOM` checks if the previous containerStatus was NOT `Terminated`, and here the previous status was `Waiting`, which records another OOM sample.

So I believe we are double counting from 1 oomkill. Here in the example, we are actually observing every state that actually happens. I think we could fix this if we change the check in `isPreviousOOM` to check if `lastState == Running` and not just `lastState != Terminated` since there exists the `Waiting` container state.

File: vertical-pod-autoscaler/pkg/recommender/input/oom/observer_test.go [hunk 4]
```diff
@@ -181,18 +179,291 @@ func TestOOMReceived(t *testing.T) {
...
+			newPod, err := newPod(tc.newPodYaml)
+			assert.NoError(t, err)
+			observer := NewObserver()
+			observer.OnUpdate(oldPod, newPod)
+			assert.Empty(t, observer.observedOomsChannel)
+		})
+	}
+}
 
+func TestOOMStateAfterTerminatedState(t *testing.T) {
```
Comment (maxcao13) [inline vertical-pod-autoscaler/pkg/recommender/input/oom/observer_test.go:539]: Can we add one more test which is just to check that a simulated pod informer re-list won't double count an OOMkill?

i.e. if a container 
1. went running -> OOMKill -> running such that `lastState.terminatedReason` is now `OOMKilled` will trigger an OOMKill observer event in the oomchannel
2. Then we simulate an informer relist, which causes an update to list the same pod, but lastState.terminatedReason is still `OOMKilled`. Can we test that this wouldn't trigger a new `OOMKill` event to be sent to the same oomobserver channel?

File: vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go (hunk 3 above)
Comment (tkukushkin) [reply vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go:168]: Confirmed. Reproduced in a test cluster — the container does go Waiting(CrashLoopBackOff) -> Running while keeping `lastState.terminated.reason=OOMKilled`, so `isPreviousOOM` fires a second time for an OOM already recorded by `isNewOOM` on the preceding Running -> Terminated transition.

Applied the suggested fix in ad5fb271 — `isPreviousOOM` now requires `oldStatus.State.Running != nil` instead of just `oldStatus.State.Terminated == nil`. Added `TestOOMNotDoubleCountedAcrossCrashLoopBackoff` that covers exactly this sequence.

File: vertical-pod-autoscaler/pkg/recommender/input/oom/observer_test.go (hunk 4 above)
Comment (tkukushkin) [reply vertical-pod-autoscaler/pkg/recommender/input/oom/observer_test.go:539]: Added as `TestOOMNotDoubleCountedOnInformerRelist` in ad5fb271 — feeds the observer identical old/new pod state and asserts the channel stays empty.

**Review by maxcao13 — APPROVED** [review]
/lgtm

thanks for the work on this :-)

**Review by omerap12 — COMMENTED** [review]
Thanks for this! Overall, this LGTM, but there is quite a bit of code repetition in the test file. Can we merge these test functions into a single event-driven test function?

**Comment by tkukushkin** [comment]
@omerap12 done in cd7bb887 — merged the seven `OnUpdate` tests into a single table-driven `TestOOMObserverOnUpdate` and added a `mustNewPod` helper plus a shared `podYamlHeader` constant so each fixture only declares the containerStatus fields that distinguish its scenario. Test file shrank from 705 to 430 lines.

File: vertical-pod-autoscaler/pkg/recommender/input/oom/observer_test.go [hunk 5]
```diff
@@ -491,79 +145,161 @@ status:
...
-	observer := NewObserver()
-	observer.OnUpdate(oldPod, newPod)
-	assert.Empty(t, observer.observedOomsChannel)
+func mustNewPod(t *testing.T, yaml string) *corev1.Pod {
+	t.Helper()
+	pod, err := newPod(yaml)
+	if err != nil {
+		t.Fatalf("failed to parse pod YAML: %v", err)
+	}
+	return pod
```
Comment (omerap12) [inline vertical-pod-autoscaler/pkg/recommender/input/oom/observer_test.go]: Since `newPod` function being used only in `mustNewPod` we can merged those as well:

```golang
func mustNewPod(t *testing.T, yaml string) *corev1.Pod {
	t.Helper()
	decode := codecs.UniversalDeserializer().Decode
	obj, _, err := decode([]byte(yaml), nil, nil)
	if err != nil {
		t.Fatalf("failed to parse pod YAML: %v", err)
	}
	return obj.(*corev1.Pod)
}
```

and then delete `newPod` entirely

Comment (tkukushkin) [reply vertical-pod-autoscaler/pkg/recommender/input/oom/observer_test.go]: Done in 6910f909 — inlined the decode logic into `mustNewPod` and removed `newPod`.

**Review by omerap12 — APPROVED** [review]
Thanks! 
/lgtm
/approve
/label tide/merge-method-squash
