### PR TITLE
Fix(log flags): handle log streams correctly 

### LINKED ISSUE #7842: Cluster autoscaler argument --log-file is no longer working after v1.30.x
**Which component are you using?**: Cluster auto-scaler

**What version of the component are you using?**: v1.31.1, v.1.30.2

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**:

**What did you expect to happen?**:

**What happened instead?**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by lxuan94-pp**
#### What type of PR is this?
/kind bug

Optionally add one or more of the following kinds if applicable:
/kind regression

#### What this PR does / why we need it:
After upgrading to Autoscaler v1.30.x, the log file no longer exists and is not created. This PR fixes the issue without modifying component-base or klog in vendor

#### Which issue(s) this PR fixes:

Fixes #7842

#### Special notes for your reviewer:
Persist the behavior from klog:
```
commandLine.StringVar(&logging.logFile, "log_file", "", "If non-empty, use this log file (no effect when -logtostderr=true)")
commandLine.BoolVar(&logging.toStderr, "logtostderr", true, "log to standard error instead of files")
commandLine.BoolVar(&logging.alsoToStderr, "alsologtostderr", false, "log to standard error as well as files (no effect when -logtostderr=true)")
```

#### Does this PR introduce a user-facing change?
None

For more information on release notes see: https://git.k8s.io/community/contributors/guide/release-notes.md
-->
```release-note
Fixed an issue where the --log-file option stopped working. Logging now correctly writes to the specified file in addition to standard error.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
Tested in OCI cluster
Screenshot 2025-11-19 at 8 12 05 PM
Screenshot 2025-11-19 at 8 13 49 PM
Screenshot 2025-11-19 at 8 19 51 PM

```docs

```

### CODE REVIEW

File: cluster-autoscaler/config/flags/klog_flags.go [hunk 1]
```diff
@@ -0,0 +1,68 @@
+package flags
```
Comment (jackfrancis) [inline cluster-autoscaler/config/flags/klog_flags.go:17]: missing copyright header text (see examples in other files, make sure to set the date to 2025)

File: cluster-autoscaler/go.sum [hunk 2]
```diff
@@ -675,4 +675,4 @@ sigs.k8s.io/randfill v1.0.0/go.mod h1:XeLlZ/jmk4i1HRopwe7/aU3H5n1zNUcX6TM94b3QxO
 sigs.k8s.io/structured-merge-diff/v6 v6.3.0 h1:jTijUJbW353oVOd9oTlifJqOGEkUw2jB/fXCbTiQEco=
 sigs.k8s.io/structured-merge-diff/v6 v6.3.0/go.mod h1:M3W8sfWvn2HhQDIbGWj3S099YozAsymCo/wrT5ohRUE=
 sigs.k8s.io/yaml v1.6.0 h1:G8fkbMSAFqgEFgh4b1wmtzDnioxFCUgTZhlbj5P9QYs=
-sigs.k8s.io/yaml v1.6.0/go.mod h1:796bPqUfzR/0jLAl6XjHl3Ck7MiyVv8dbTdyT3/pMf4=
+sigs.k8s.io/yaml v1.6.0/go.mod h1:796bPqUfzR/0jLAl6XjHl3Ck7MiyVv8dbTdyT3/pMf4=
```
Comment (jackfrancis) [inline cluster-autoscaler/go.sum]: please remove this newline change, thank you!

**Review by jackfrancis — CHANGES_REQUESTED** [review]

File: cluster-autoscaler/go.sum (hunk 2 above)
Comment (lxuan94-pp) [reply cluster-autoscaler/go.sum]: I think it was changed by `go mod tidy` I ran, which caused different line endings. I have reverted it to the master version.

File: cluster-autoscaler/config/flags/klog_flags.go (hunk 1 above)
Comment (lxuan94-pp) [reply cluster-autoscaler/config/flags/klog_flags.go:17]: Thanks, added and the date is set to 2025.

File: cluster-autoscaler/config/flags/klog_flags.go [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+//   - If --alsologtostderr=true, logs also go to os.Stderr
+func ComputeLoggingOptions(fs *pflag.FlagSet) (*logsapi.LoggingOptions, error) {
+	logFilePath := getFlagString(fs, "log-file")
+	logToStderr := getFlagBool(fs, "logtostderr")
+	alsoLogToStderr := getFlagBool(fs, "alsologtostderr")
+
+	// default: both to stderr
+	var infoW, errW io.Writer = os.Stderr, os.Stderr
+
+	if logFilePath != "" && !logToStderr {
```
Comment (jackfrancis) [inline cluster-autoscaler/config/flags/klog_flags.go:60]: Can we drop the `-alsologtostderr` option?

If just `--log-file` is set but no `--logtostderr` (default to false), then we configure logging for redirecting both info and err logging to the configured log file.

If `--log-file` is set *and* `--logtostderr=true` we intrepret that as:
- configure logging for redirecting both info and err logging to the configured log file
- also tee log info and err output to stderr

Comment (lxuan94-pp) [reply cluster-autoscaler/config/flags/klog_flags.go:60]: We can drop `-alsologtostderr` if we want to follow this model, but just to note: klog’s guidance is that --log-file and --alsologtostderr are **ignored** when `--logtostderr=true`
```
commandLine.StringVar(&logging.logFile, "log_file", "", "If non-empty, use this log file (no effect when -logtostderr=true)")
commandLine.BoolVar(&logging.toStderr, "logtostderr", true, "log to standard error instead of files")
commandLine.BoolVar(&logging.alsoToStderr, "alsologtostderr", false, "log to standard error as well as files (no effect when -logtostderr=true)")
```
from klog/v2 https://pkg.go.dev/k8s.io/klog/v2#klog.go

I’m fine proceeding with your proposed interpretation, as long as we’re aware it slightly diverges from the standard klog usage pattern. Let me know if you want me to update the flags accordingly.

Comment (lxuan94-pp) [reply cluster-autoscaler/config/flags/klog_flags.go:60]: @jackfrancis Please advise on how we should proceed, and I can update or keep the change accordingly.

**Comment by lxuan94-pp** [comment]
Hi @jackfrancis, pls check the comment https://github.com/kubernetes/autoscaler/pull/8836#discussion_r2561801746 and advise on how we should proceed. IMO I want to keep the current behavior to align with klog.

**Comment by lxuan94-pp** [comment]
Bumping https://github.com/kubernetes/autoscaler/pull/8836#issuecomment-3657725106
cc:@jackfrancis

File: cluster-autoscaler/config/flags/klog_flags.go (hunk 3 above)
Comment (jackfrancis) [reply cluster-autoscaler/config/flags/klog_flags.go:60]: ACK, probably best not to overthink and follow that guidance
