### PR TITLE
Fix Azure client requests stuck issues on http.StatusTooManyRequests

### LINKED ISSUE #2124: autoscaler v1.14.2 is not working with Azure VMSS and Kubernetes 1.14.1
We deployed autoscaler v1.14.2 to our Kubernetes cluster that uses vmss as instance_type, the logs does not show any errors at all, however there wasn't any scaling action happened.

We switched the version back to v1.12.6 and the autoscaler started to work.

```
(⎈ |kubernetes-admin@test-definite-slug:default)huy@tryndamere:~|⇒  kubectl -n kube-system logs -f cluster-autoscaler-54998d5f8b-2z4ft
I0613 19:18:02.728702       1 flags.go:52] FLAG: --address=":8085"
I0613 19:18:02.728737       1 flags.go:52] FLAG: --alsologtostderr="false"
I0613 19:18:02.728741       1 flags.go:52] FLAG: --balance-similar-node-groups="false"
I0613 19:18:02.728745       1 flags.go:52] FLAG: --cloud-config=""
I0613 19:18:02.728748       1 flags.go:52] FLAG: --cloud-provider="azure"
I0613 19:18:02.728752       1 flags.go:52] FLAG: --cloud-provider-gce-lb-src-cidrs="130.211.0.0/22,209.85.152.0/22,209.85.204.0/22,35.191.0.0/16"
I0613 19:18:02.728771       1 flags.go:52] FLAG: --cluster-name=""
I0613 19:18:02.728776       1 flags.go:52] FLAG: --cores-total="0:320000"
I0613 19:18:02.728782       1 flags.go:52] FLAG: --estimator="binpacking"
I0613 19:18:02.728787       1 flags.go:52] FLAG: --expander="random"
I0613 19:18:02.728799       1 flags.go:52] FLAG: --expendable-pods-priority-cutoff="-10"
I0613 19:18:02.728803       1 flags.go:52] FLAG: --filter-out-schedulable-pods-uses-packing="true"
I0613 19:18:02.728807       1 flags.go:52] FLAG: --gke-api-endpoint=""
I0613 19:18:02.728810       1 flags.go:52] FLAG: --gpu-total="[]"
I0613 19:18:02.728814       1 flags.go:52] FLAG: --httptest.serve=""
I0613 19:18:02.728817       1 flags.go:52] FLAG: --ignore-daemonsets-utilization="false"
I0613 19:18:02.728821       1 flags.go:52] FLAG: --ignore-mirror-pods-utilization="false"
I0613 19:18:02.728824       1 flags.go:52] FLAG: --kubeconfig=""
I0613 19:18:02.728828       1 flags.go:52] FLAG: --kubernetes=""
I0613 19:18:02.728831       1 flags.go:52] FLAG: --leader-elect="true"
I0613 19:18:02.728845       1 flags.go:52] FLAG: --leader-elect-lease-duration="15s"
I0613 19:18:02.728855       1 flags.go:52] FLAG: --leader-elect-renew-deadline="10s"
I0613 19:18:02.728861       1 flags.go:52] FLAG: --leader-elect-resource-lock="endpoints"
I0613 19:18:02.728881       1 flags.go:52] FLAG: --leader-elect-retry-period="2s"
I0613 19:18:02.728885       1 flags.go:52] FLAG: --log-backtrace-at=":0"
I0613 19:18:02.728891       1 flags.go:52] FLAG: --log-dir=""
I0613 19:18:02.728895       1 flags.go:52] FLAG: --log-file=""
I0613 19:18:02.728898       1 flags.go:52] FLAG: --logtostderr="true"
I0613 19:18:02.728901       1 flags.go:52] FLAG: --max-autoprovisioned-node-group-count="15"
I0613 19:18:02.728906       1 flags.go:52] FLAG: --max-bulk-soft-taint-count="10"
I0613 19:18:02.728909       1 flags.go:52] FLAG: --max-bulk-soft-taint-time="3s"
I0613 19:18:02.728913       1 flags.go:52] FLAG: --max-empty-bulk-delete="10"
I0613 19:18:02.728916       1 flags.go:52] FLAG: --max-failing-time="15m0s"
I0613 19:18:02.728920       1 flags.go:52] FLAG: --max-graceful-termination-sec="600"
I0613 19:18:02.728923       1 flags.go:52] FLAG: --max-inactivity="10m0s"
I0613 19:18:02.728927       1 flags.go:52] FLAG: --max-node-provision-time="15m0s"
I0613 19:18:02.728932       1 flags.go:52] FLAG: --max-nodes-total="0"
I0613 19:18:02.728945       1 flags.go:52] FLAG: --max-total-unready-percentage="45"
I0613 19:18:02.728959       1 flags.go:52] FLAG: --memory-total="0:6400000"
I0613 19:18:02.728963       1 flags.go:52] FLAG: --min-replica-count="0"
I0613 19:18:02.728966       1 flags.go:52] FLAG: --namespace="kube-system"
I0613 19:18:02.728973       1 flags.go:52] FLAG: --new-pod-scale-up-delay="0s"
I0613 19:18:02.728979       1 flags.go:52] FLAG: --node-autoprovisioning-enabled="false"
I0613 19:18:02.728991       1 flags.go:52] FLAG: --node-group-auto-discovery="[]"
I0613 19:18:02.728995       1 flags.go:52] FLAG: --nodes="[1:20:test-kubernetesworkers-centralus-definite-slug]"
I0613 19:18:02.729001       1 flags.go:52] FLAG: --ok-total-unready-count="3"
I0613 19:18:02.729004       1 flags.go:52] FLAG: --regional="false"
I0613 19:18:02.729008       1 flags.go:52] FLAG: --scale-down-candidates-pool-min-count="50"
I0613 19:18:02.729011       1 flags.go:52] FLAG: --scale-down-candidates-pool-ratio="0.1"
I0613 19:18:02.729016       1 flags.go:52] FLAG: --scale-down-delay-after-add="10m0s"
I0613 19:18:02.729019       1 flags.go:52] FLAG: --scale-down-delay-after-delete="10s"
I0613 19:18:02.729023       1 flags.go:52] FLAG: --scale-down-delay-after-failure="3m0s"
I0613 19:18:02.729026       1 flags.go:52] FLAG: --scale-down-enabled="true"
I0613 19:18:02.729030       1 flags.go:52] FLAG: --scale-down-non-empty-candidates-count="30"
I0613 19:18:02.729033       1 flags.go:52] FLAG: --scale-down-unneeded-time="10m0s"
I0613 19:18:02.729037       1 flags.go:52] FLAG: --scale-down-unready-time="20m0s"
I0613 19:18:02.729040       1 flags.go:52] FLAG: --scale-down-utilization-threshold="0.5"
I0613 19:18:02.729044       1 flags.go:52] FLAG: --scan-interval="10s"
I0613 19:18:02.729049       1 flags.go:52] FLAG: --skip-headers="false"
I0613 19:18:02.729071       1 flags.go:52] FLAG: --skip-nodes-with-local-storage="false"
I0613 19:18:02.729077       1 flags.go:52] FLAG: --skip-nodes-with-system-pods="true"
I0613 19:18:02.729083       1 flags.go:52] FLAG: --stderrthreshold="2"
I0613 19:18:02.729094       1 flags.go:52] FLAG: --test.bench=""
I0613 19:18:02.729098       1 flags.go:52] FLAG: --test.benchmem="false"
I0613 19:18:02.729102       1 flags.go:52] FLAG: --test.benchtime="1s"
I0613 19:18:02.729105       1 flags.go:52] FLAG: --test.blockprofile=""
I0613 19:18:02.729109       1 flags.go:52] FLAG: --test.blockprofilerate="1"
I0613 19:18:02.729112       1 flags.go:52] FLAG: --test.count="1"
I0613 19:18:02.729116       1 flags.go:52] FLAG: --test.coverprofile=""
I0613 19:18:02.729119       1 flags.go:52] FLAG: --test.cpu=""
I0613 19:18:02.729122       1 flags.go:52] FLAG: --test.cpuprofile=""
I0613 19:18:02.729125       1 flags.go:52] FLAG: --test.failfast="false"
I0613 19:18:02.729129       1 flags.go:52] FLAG: --test.list=""
I0613 19:18:02.729132       1 flags.go:52] FLAG: --test.memprofile=""
I0613 19:18:02.729136       1 flags.go:52] FLAG: --test.memprofilerate="0"
I0613 19:18:02.729139       1 flags.go:52] FLAG: --test.mutexprofile=""
I0613 19:18:02.729144       1 flags.go:52] FLAG: --test.mutexprofilefraction="1"
I0613 19:18:02.729162       1 flags.go:52] FLAG: --test.outputdir=""
I0613 19:18:02.729167       1 flags.go:52] FLAG: --test.parallel="8"
I0613 19:18:02.729172       1 flags.go:52] FLAG: --test.run=""
I0613 19:18:02.729176       1 flags.go:52] FLAG: --test.short="false"
I0613 19:18:02.729180       1 flags.go:52] FLAG: --test.testlogfile=""
I0613 19:18:02.729185       1 flags.go:52] FLAG: --test.timeout="0s"
I0613 19:18:02.729191       1 flags.go:52] FLAG: --test.trace=""
I0613 19:18:02.729202       1 flags.go:52] FLAG: --test.v="false"
I0613 19:18:02.729205       1 flags.go:52] FLAG: --unremovable-node-recheck-timeout="5m0s"
I0613 19:18:02.729209       1 flags.go:52] FLAG: --v="3"
I0613 19:18:02.729213       1 flags.go:52] FLAG: --vmodule=""
I0613 19:18:02.729216       1 flags.go:52] FLAG: --write-status-configmap="true"
I0613 19:18:02.729222       1 main.go:344] Cluster Autoscaler 1.14.2
I0613 19:18:02.832075       1 leaderelection.go:217] attempting to acquire leader lease  kube-system/cluster-autoscaler...
I0613 19:18:20.423262       1 leaderelection.go:227] successfully acquired lease kube-system/cluster-autoscaler
I0613 19:18:20.426552       1 reflector.go:123] Starting reflector *v1.Pod (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:190
I0613 19:18:20.426592       1 reflector.go:161] Listing and watching *v1.Pod from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:190
I0613 19:18:20.426787       1 reflector.go:123] Starting reflector *v1.Pod (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:215
I0613 19:18:20.426836       1 reflector.go:161] Listing and watching *v1.Pod from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:215
I0613 19:18:20.426978       1 reflector.go:123] Starting reflector *v1.Node (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:253
I0613 19:18:20.426996       1 reflector.go:161] Listing and watching *v1.Node from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:253
I0613 19:18:20.427134       1 reflector.go:123] Starting reflector *v1.Node (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:280
I0613 19:18:20.427188       1 reflector.go:161] Listing and watching *v1.Node from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:280
I0613 19:18:20.427318       1 reflector.go:123] Starting reflector *v1beta1.PodDisruptionBudget (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:307
I0613 19:18:20.427335       1 reflector.go:161] Listing and watching *v1beta1.PodDisruptionBudget from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:307
I0613 19:18:20.427464       1 reflector.go:123] Starting reflector *v1.DaemonSet (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:319
I0613 19:18:20.427481       1 reflector.go:161] Listing and watching *v1.DaemonSet from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:319
I0613 19:18:20.427619       1 reflector.go:123] Starting reflector *v1.ReplicationController (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:329
I0613 19:18:20.427636       1 reflector.go:161] Listing and watching *v1.ReplicationController from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:329
I0613 19:18:20.427764       1 reflector.go:123] Starting reflector *v1.Job (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:339
I0613 19:18:20.427781       1 reflector.go:161] Listing and watching *v1.Job from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:339
I0613 19:18:20.427918       1 reflector.go:123] Starting reflector *v1.ReplicaSet (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:349
I0613 19:18:20.427936       1 reflector.go:161] Listing and watching *v1.ReplicaSet from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:349
I0613 19:18:20.428061       1 reflector.go:123] Starting reflector *v1.StatefulSet (1h0m0s) from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:359
I0613 19:18:20.428078       1 reflector.go:161] Listing and watching *v1.StatefulSet from k8s.io/autoscaler/cluster-autoscaler/utils/kubernetes/listers.go:359
I0613 19:18:21.622880       1 factory.go:331] Creating scheduler from algorithm provider 'DefaultProvider'
I0613 19:18:21.622927       1 factory.go:412] Creating scheduler with fit predicates 'map[PodToleratesNodeTaints:{} CheckVolumeBinding:{} NoVolumeZoneConflict:{} MaxEBSVolumeCount:{} MaxAzureDiskVolumeCount:{} GeneralPredicates:{} CheckNodeUnschedulable:{} MaxGCEPDVolumeCount:{} MatchInterPodAffinity:{} NoDiskConflict:{} MaxCSIVolumeCountPred:{}]' and priority functions 'map[ImageLocalityPriority:{} SelectorSpreadPriority:{} InterPodAffinityPriority:{} LeastRequestedPriority:{} BalancedResourceAllocation:{} NodePreferAvoidPodsPriority:{} NodeAffinityPriority:{} TaintTolerationPriority:{}]'
I0613 19:18:21.623599       1 predicates.go:168] Using predicate PodFitsResources
I0613 19:18:21.623633       1 predicates.go:168] Using predicate GeneralPredicates
I0613 19:18:21.623644       1 predicates.go:168] Using predicate PodToleratesNodeTaints
I0613 19:18:21.623652       1 predicates.go:168] Using predicate MaxAzureDiskVolumeCount
I0613 19:18:21.623661       1 predicates.go:168] Using predicate MaxCSIVolumeCountPred
I0613 19:18:21.623670       1 predicates.go:168] Using predicate CheckVolumeBinding
I0613 19:18:21.623679       1 predicates.go:168] Using predicate NoVolumeZoneConflict
I0613 19:18:21.623688       1 predicates.go:168] Using predicate CheckNodeUnschedulable
I0613 19:18:21.623702       1 predicates.go:168] Using predicate MaxGCEPDVolumeCount
I0613 19:18:21.623710       1 predicates.go:168] Using predicate MatchInterPodAffinity
I0613 19:18:21.623727       1 predicates.go:168] Using predicate ready
I0613 19:18:21.623737       1 predicates.go:168] Using predicate NoDiskConflict
I0613 19:18:21.623746       1 predicates.go:168] Using predicate MaxEBSVolumeCount
I0613 19:18:21.623790       1 cloud_provider_builder.go:29] Building azure cloud provider.
I0613 19:18:21.823137       1 azure_cloud_provider.go:135] Creating Azure Manager with default configuration.
I0613 19:18:21.823187       1 azure_manager.go:163] Starting azure manager with subscription ID "c193c6d7-0cc4-42dd-8af2-394a4780ac11"
I0613 19:18:21.823232       1 azure_client.go:440] azure: using client_id+client_secret to retrieve access token
I0613 19:18:21.829096       1 reflector.go:123] Starting reflector *v1.StorageClass (0s) from k8s.io/client-go/informers/factory.go:132
I0613 19:18:21.829124       1 reflector.go:161] Listing and watching *v1.StorageClass from k8s.io/client-go/informers/factory.go:132
I0613 19:18:21.829314       1 reflector.go:123] Starting reflector *v1.Node (0s) from k8s.io/client-go/informers/factory.go:132
I0613 19:18:21.829331       1 reflector.go:161] Listing and watching *v1.Node from k8s.io/client-go/informers/factory.go:132
I0613 19:18:21.829520       1 reflector.go:123] Starting reflector *v1.ReplicationController (0s) from k8s.io/client-go/informers/factory.go:132
I0613 19:18:21.829536       1 reflector.go:161] Listing and watching *v1.ReplicationController from k8s.io/client-go/informers/factory.go:132
I0613 19:18:21.829693       1 reflector.go:123] Starting reflector *v1.StatefulSet (0s) from k8s.io/client-go/informers/factory.go:132
I0613 19:18:21.829707       1 reflector.go:161] Listing and watching *v1.StatefulSet from k8s.io/client-go/informers/factory.go:132
I0613 19:18:21.829870       1 reflector.go:123] Starting reflector *v1.Pod (0s) from k8s.io/client-go/informers/factory.go:132
I0613 19:18:21.829884       1 reflector.go:161] Listing and watching *v1.Pod from k8s.io/client-go/informers/factory.go:132
I0613 19:18:21.830097       1 reflector.go:123] Starting reflector *v1.PersistentVolumeClaim (0s) from k8s.io/client-go/informers/factory.go:132
I0613 19:18:21.830113       1 reflector.go:161] Listing and watching *v1.PersistentVolumeClaim from k8s.io/client-go/informers/factory.go:132
I0613 19:18:21.830344       1 reflector.go:123] Starting reflector *v1.PersistentVolume (0s) from k8s.io/client-go/informers/factory.go:132
I0613 19:18:21.830361       1 reflector.go:161] Listing and watching *v1.PersistentVolume from k8s.io/client-go/informers/factory.go:132
I0613 19:18:21.923100       1 reflector.go:123] Starting reflector *v1beta1.PodDisruptionBudget (0s) from k8s.io/client-go/informers/factory.go:132
I0613 19:18:21.923139       1 reflector.go:161] Listing and watching *v1beta1.PodDisruptionBudget from k8s.io/client-go/informers/factory.go:132
I0613 19:18:21.923111       1 reflector.go:123] Starting reflector *v1.ReplicaSet (0s) from k8s.io/client-go/informers/factory.go:132
I0613 19:18:21.923175       1 reflector.go:161] Listing and watching *v1.ReplicaSet from k8s.io/client-go/informers/factory.go:132
I0613 19:18:22.023034       1 reflector.go:123] Starting reflector *v1.Service (0s) from k8s.io/client-go/informers/factory.go:132
I0613 19:18:22.023067       1 reflector.go:161] Listing and watching *v1.Service from k8s.io/client-go/informers/factory.go:132
I0613 19:18:24.522612       1 azure_manager.go:261] Refreshed ASG list, next refresh after 2019-06-13 19:19:24.522602065 +0000 UTC m=+82.294975275
I0613 19:18:24.522798       1 main.go:261] Registered cleanup signal handler
I0613 19:19:24.555228       1 azure_manager.go:261] Refreshed ASG list, next refresh after 2019-06-13 19:20:24.555216142 +0000 UTC m=+142.327589252
I0613 19:20:24.578335       1 azure_manager.go:261] Refreshed ASG list, next refresh after 2019-06-13 19:21:24.57832402 +0000 UTC m=+202.350697130
I0613 19:21:24.600761       1 azure_manager.go:261] Refreshed ASG list, next refresh after 2019-06-13 19:22:24.600751321 +0000 UTC m=+262.373124431
```

### PR DESCRIPTION
**Pull request by feiskyer**
In go-autorest SDK https://github.com/Azure/go-autorest/blob/master/autorest/sender.go#L242,
if ARM returns http.StatusTooManyRequests, the sender doesn't increase the retry attempt count,
hence the Azure clients will keep retrying forever until it gets a status code other than 429.

```go
// don't count a 429 against the number of attempts
// so that we continue to retry until it succeeds
if resp == nil || resp.StatusCode != http.StatusTooManyRequests {
    attempt++
}
```

So this PR explicitly remove `http.StatusTooManyRequests` from `autorest.StatusCodesForRetry`. To reduce the API throttling issues, it also adds caches for vmss instances.

Fix #2124.

/cc @andyzhangx @nilo19

### CODE REVIEW

**Comment by andyzhangx** [comment]
@feiskyer In azure cloud provider, we would still retry after hit 409, since it's exponential backoff, is it safe in azure cloud provider code? 
```
		// HTTP 4xx (except 412) or 5xx suggests we should retry.
		if 399 < resp.StatusCode && resp.StatusCode < 600 {
			return true
		}
``

File: cluster-autoscaler/cloudprovider/azure/azure_scale_set.go [hunk 1]
```diff
@@ -35,8 +36,29 @@ import (
...
+)
+
+func init() {
+	// In go-autorest SDK https://github.com/Azure/go-autorest/blob/master/autorest/sender.go#L242,
+	// if ARM returns http.StatusTooManyRequests, the sender doesn't increase the retry attempt count,
+	// hence the Azure clients will keep retrying forever until it get a status code other than 429.
+	// So we explicitly removes http.StatusTooManyRequests from autorest.StatusCodesForRetry.
+	// Refer https://github.com/Azure/go-autorest/issues/398.
+	statusCodesForRetry := make([]int, 0)
+	for _, code := range autorest.StatusCodesForRetry {
```
Comment (andyzhangx) [inline cluster-autoscaler/cloudprovider/azure/azure_scale_set.go]: we should update the retry status code for azure cloud provider here:
https://github.com/kubernetes/kubernetes/blob/bf86300241e51f011040d208e43f1cd2a5c0378a/staging/src/k8s.io/legacy-cloud-providers/azure/azure_backoff.go#L586-L589

Comment (feiskyer) [reply cluster-autoscaler/cloudprovider/azure/azure_scale_set.go]: The above retry logic is ok, since there's already a backoff-retry there. And for 412, cloud provider should retry actually, just with backoff delay.

**Comment by feiskyer** [comment]
> @feiskyer In azure cloud provider, we would still retry after hit 409, since it's exponential backoff, is it safe in azure cloud provider code?

Yep, it's safe from SDK's client side. CA doesn't need backoff retry since it would run again later. The issue is from go-autorest internal implementations, we should also add some fixes in the Kubernetes cloud provider.

By the way, the error code here is 429, not 409.

**Comment by feiskyer** [comment]
Rebased to solve the conflicts

**Comment by feiskyer** [comment]
@andyzhangx @losipiuk Could you help to approve the changes?

**Comment by losipiuk** [comment]
/lgtm
/approve
Thanks!
