### PR TITLE
[VPA] Add subresource status for vpa with e2e fix

### LINKED ISSUE #5675: vpa CRD not contain status subresource
**Which component are you using?**:

vertical-pod-autoscaler

**What version of the component are you using?**:

Component version:  0.13.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.10", GitCommit:"7e54d50d3012cf3389e43b096ba35300f36e0817", GitTreeState:"clean", BuildDate:"2022-08-17T18:32:54Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.10", GitCommit:"7e54d50d3012cf3389e43b096ba35300f36e0817", GitTreeState:"clean", BuildDate:"2022-08-17T18:26:59Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:
kubernetes 1.23

**What did you expect to happen?**:

vpa crd has stataus field in subresources, that `metadata.generation` only increase in spec change
relate pr #3606 

**What happened instead?**:

The vpa crd has empty subresources that leads to `metadata.generation` increase on vpa status update
https://github.com/kubernetes/autoscaler/blob/f173888d38b57f38c4328146c51284ebc62bfef2/vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml#L516

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

relate code: https://github.com/kubernetes/autoscaler/blob/f173888d38b57f38c4328146c51284ebc62bfef2/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L39-L52

### PR DESCRIPTION
**Pull request by wu0407**
Add status field in subresource on crd yaml and add new ClusterRole system:vpa-actor to patch /status subresource. 
The `metadata.generation` only increase on vpa spec update. 
Fix e2e test for patch and create vpa

#### What type of PR is this?
/kind bug
/kind failing-test
/kind api-change

#### What this PR does / why we need it:
Current vpa crd has empty subresource field, that leads to metadata.generation increase on vpa status update.
The controller-runtime has [GenerationChangedPredicate](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.14.5/pkg/predicate#GenerationChangedPredicate) to filter out update status event for cr, but it not work for vpa.
This PR add status field in subresource on crd yaml and add new ClusterRole system:vpa-actor to patch /status subresource.
The metadata.generation only increase on vpa spec update.

#### Which issue(s) this PR fixes:

Fixes #5675 

#### Special notes for your reviewer:
Previous pull request is #5680 and be revert #5738, because of e2e test failed #5727. 
This PR fixes e2e test failure. 

#### Does this PR introduce a user-facing change?

```release-note
Added the /status subresource to VPA
action required: If you're installing VPA with different means than the `hack/vpa-up.sh` script, you need to add the ClusterRole `system:vpa-status-actor` and corresponding ClusterRoleBinding yourself. Otherwise VPA will no longer be able to update the recommendations!
If you create vpa with status,  status be ignored in apiserver, so need to update status after create vpa.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by wu0407** [comment]
@voelzmo @jbartosik

File: vertical-pod-autoscaler/e2e/v1/common.go [hunk 1]
```diff
@@ -56,6 +56,8 @@ const (
 
 	defaultHamsterReplicas     = int32(3)
 	defaultHamsterBackoffLimit = int32(10)
+	// dummyRecommender for self update vpa status, avoid being modified by the default recommender
+	dummyRecommender = "notExistRecommender"
```
Comment (jbartosik) [inline vertical-pod-autoscaler/e2e/v1/common.go:60]: Please don't set this as recommender.

We don't need this. When running e2e tests with [run-e2e.sh](https://github.com/kubernetes/autoscaler/blob/114a35961a85efdf3f36859350764e5e2c0c7013/vertical-pod-autoscaler/hack/run-e2e.sh) only some components are deployed:
- For [admission-controller](https://github.com/kubernetes/autoscaler/blob/114a35961a85efdf3f36859350764e5e2c0c7013/vertical-pod-autoscaler/hack/deploy-for-e2e.sh#L47) tests only admission contoller is deployed,
- for [actuation](https://github.com/kubernetes/autoscaler/blob/114a35961a85efdf3f36859350764e5e2c0c7013/vertical-pod-autoscaler/hack/deploy-for-e2e.sh#L53) tests admission-controller and updater are deployed

So there is no need to set alternative recommender inside tests.

File: vertical-pod-autoscaler/e2e/v1beta2/common.go [hunk 2]
```diff
@@ -357,9 +357,27 @@ func getVpaClientSet(f *framework.Framework) vpa_clientset.Interface {
...
 	vpaClientSet := getVpaClientSet(f)
-	_, err := vpaClientSet.AutoscalingV1beta2().VerticalPodAutoscalers(f.Namespace.Name).Create(context.TODO(), vpa, metav1.CreateOptions{})
+	vpa, err := vpaClientSet.AutoscalingV1beta2().VerticalPodAutoscalers(f.Namespace.Name).Create(context.TODO(), vpa, metav1.CreateOptions{})
 	gomega.Expect(err).NotTo(gomega.HaveOccurred(), "unexpected error creating VPA")
+	// apiserver ignore status in vpa create, so need to update status
+	if !isStatusEmpty(&status) {
+		vpa.Status = status
+		_, err := vpaClientSet.AutoscalingV1beta2().VerticalPodAutoscalers(f.Namespace.Name).UpdateStatus(context.TODO(), vpa, metav1.UpdateOptions{})
+		gomega.Expect(err).NotTo(gomega.HaveOccurred(), "unexpected error update VPA status")
+	}
```
Comment (jbartosik) [inline vertical-pod-autoscaler/e2e/v1beta2/common.go:369]: Please:

- Extract helper for patching status, make lines 399-406 a function
- Use the new helper to patch status `PatchVpaRecommendation` and `InstallVPA` (then we don't need to make a copy of created VPA)

**Review by jbartosik — CHANGES_REQUESTED** [review]
We should mention the breaking change in the release notes.

Also a couple comments asking for some small code changes.

File: vertical-pod-autoscaler/e2e/v1beta2/common.go [hunk 3]
```diff
@@ -360,6 +360,23 @@ func InstallVPA(f *framework.Framework, vpa *vpa_types.VerticalPodAutoscaler) {
 	vpaClientSet := getVpaClientSet(f)
 	_, err := vpaClientSet.AutoscalingV1beta2().VerticalPodAutoscalers(f.Namespace.Name).Create(context.TODO(), vpa, metav1.CreateOptions{})
 	gomega.Expect(err).NotTo(gomega.HaveOccurred(), "unexpected error creating VPA")
+	// apiserver ignore status in vpa create, so need to update status
+	if !isStatusEmpty(&vpa.Status) {
+		if vpa.Status.Recommendation != nil {
+			PatchVpaRecommendation(f, vpa, vpa.Status.Recommendation)
+		}
+	}
```
Comment (wu0407) [inline vertical-pod-autoscaler/e2e/v1beta2/common.go:368]: A comment is needed leave in InstallVPA that create vpa with status need individual update status, so isStatusEmpty needs to be preserved, and the code may appear a bit redundant

**Comment by wu0407** [comment]
A comment is needed leave in InstallVPA that create vpa with status need individual update status, so isStatusEmpty needs to be preserved, and the code may appear a bit redundant

> We should mention the breaking change in the release notes.
> 
> Also a couple comments asking for some small code changes.

 A note in release notes is done

File: vertical-pod-autoscaler/e2e/v1/common.go [hunk 4]
```diff
@@ -372,6 +372,23 @@ func InstallVPA(f *framework.Framework, vpa *vpa_types.VerticalPodAutoscaler) {
 	vpaClientSet := getVpaClientSet(f)
 	_, err := vpaClientSet.AutoscalingV1().VerticalPodAutoscalers(f.Namespace.Name).Create(context.TODO(), vpa, metav1.CreateOptions{})
 	gomega.Expect(err).NotTo(gomega.HaveOccurred(), "unexpected error creating VPA")
+	// apiserver ignore status in vpa create, so need to update status
+	if !isStatusEmpty(&vpa.Status) {
+		if vpa.Status.Recommendation != nil {
```
Comment (jbartosik) [inline vertical-pod-autoscaler/e2e/v1/common.go:377]: I'd write this as one condition:

```
if !isStatusEmpty(&vpa.Status) && vpa.Status.Recommendation != nil {
```

**Review by jbartosik — APPROVED** [review]
Looks good to me.

I left one small comment to make code a bit cleaner.

I think this is good to merge but:
- Our release is overdue, I want to wait with merging until we release to avoid further delays
- I want to check if we're good on the API change (this is a breaking API change)

So
/hold

**Comment by jbartosik** [comment]
Release is tracked in #5851

File: vertical-pod-autoscaler/pkg/utils/vpa/api.go [hunk 5]
```diff
@@ -49,14 +49,14 @@ type patchRecord struct {
...
-func patchVpa(vpaClient vpa_api.VerticalPodAutoscalerInterface, vpaName string, patches []patchRecord) (result *vpa_types.VerticalPodAutoscaler, err error) {
+func patchVpaStatus(vpaClient vpa_api.VerticalPodAutoscalerInterface, vpaName string, patches []patchRecord) (result *vpa_types.VerticalPodAutoscaler, err error) {
 	bytes, err := json.Marshal(patches)
 	if err != nil {
 		klog.Errorf("Cannot marshal VPA status patches %+v. Reason: %+v", patches, err)
 		return
 	}
 
-	return vpaClient.Patch(context.TODO(), vpaName, types.JSONPatchType, bytes, meta.PatchOptions{})
+	return vpaClient.Patch(context.TODO(), vpaName, types.JSONPatchType, bytes, meta.PatchOptions{}, "status")
```
Comment (kwiesmueller) [inline vertical-pod-autoscaler/pkg/utils/vpa/api.go:59]: Is there a unit test we can add to cover this change?
Maybe using the fake client?

Comment (wu0407) [reply vertical-pod-autoscaler/pkg/utils/vpa/api.go:59]: It is already have test case on `TestUpdateVpaIfNeeded` https://github.com/kubernetes/autoscaler/blob/1384c8bc09cacd2f774872e01a945c4de6697238/vertical-pod-autoscaler/pkg/utils/vpa/api_test.go#L93-L101

Comment (kwiesmueller) [reply vertical-pod-autoscaler/pkg/utils/vpa/api.go:59]: Thanks, makes sense.

**Comment by kwiesmueller** [comment]
The release is published, are we good to unhold @jbartosik ?

**Review by jbartosik — APPROVED** [review]
/lgtm
/approve
/hold cancel

Yup, I think we can merge this

**Comment by kwiesmueller** [comment]
The PR was reverted in https://github.com/kubernetes/autoscaler/pull/5897
I'll try to run the e2e test locally to reproduce. @wu0407 please reach out if I can help with getting this back in.
You can also reach me on the kubernetes slack (kwiesmueller).

**Comment by wu0407** [comment]
> The PR was reverted in #5897 I'll try to run the e2e test locally to reproduce. @wu0407 please reach out if I can help with getting this back in. You can also reach me on the kubernetes slack (kwiesmueller).

please help me point what is the problem, because i  has not enviroment to test.  I not has acount on kubernetes slack, it not allow sign in on gmail.
