### PR TITLE
fix: replace RemoveNodeInfo with tainted ghost node in scale-down simulation

### LINKED ISSUE #9287: CA: Scale-down simulation mismatch with TopologySpreadConstraints causes scale-down/scale-up oscillation
**Which component are you using?**:

/area cluster-autoscaler

**What version of the component are you using?**:

Component version: 1.32+ (any version containing #8164)

**What k8s version are you using (`kubectl version`)?**:

1.33.6

**What environment is this in?**:

Reproduced on AKS, but the bug is cloud-provider-independent (core autoscaler logic).

**What did you expect to happen?**:

When CA encounters underutilized nodes where pods using hard `TopologySpreadConstraints` are scheduled, it should either correctly scale down (if the real scheduler can reschedule the pods) or correctly block scale-down (if the real scheduler cannot). The simulation should match real-world scheduling outcomes.

**What happened instead?**:

Nodes enter a scale-down/scale-up oscillation cycle. CA approves the scale-down (simulation says pods can reschedule), but evicted pods become unschedulable in reality, triggering an immediate scale-up. This repeats indefinitely.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a 3-node cluster with a deployment using hard topology spread constraints:

```yaml
topologySpreadConstraints:
- maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: DoNotSchedule
  labelSelector:
    matchLabels:
      app: my-app
```

2. Ensure there is enough slack capacity on the remaining 2 nodes for consolidation (i.e., the pods from 1 node could fit resource-wise on the other 2).
3. Wait for CA to attempt scale-down.
4. Observe repeated scale-down → pending pods → scale-up cycle.

**Anything else we need to know?**:

### Root cause

PR #8164 fixed a real problem where TSC pods always blocked scale-down by adding `RemoveNodeInfo(removedNode)` in `findPlaceFor()`. However, this over-corrects: removing the node entirely from the snapshot eliminates its topology domain, which doesn't match what actually happens during drain.

In reality, CA's drain process is:
1. Taint the node with `ToBeDeletedByClusterAutoscaler` (NoSchedule) — this is unconditional and synchronous, happening before any deletion or drain starts (see `taintNodesSync()` in `actuator.go`).
2. Cordon and evict pods.
3. **Node remains in the cluster** during drain — still counted as a topology domain.
4. Node eventually terminated.

With the default `nodeTaintsPolicy=Ignore` (which is what the kube-scheduler uses unless the TSC explicitly sets `nodeTaintsPolicy: Honor`), the scheduler **still counts tainted nodes as topology domains** even though pods cannot schedule on them. This creates a "phantom domain" with 0 matching pods, making the global minimum 0 and violating `maxSkew` for any rescheduling attempt.

The simulation (node removed → domain gone → pods reschedulable) disagrees with reality (node tainted → domain present with 0 pods → pods unschedulable), causing the oscillation.

#### Before #8164 (too pessimistic)

```
UnschedulePods → TrySchedulePods (node stays, empty, counted as domain with 0 pods)
```

Global min always 0 → TSC pods can never reschedule → scale-down always blocked.

#### After #8164 (too optimistic)

```
UnschedulePods → RemoveNodeInfo → TrySchedulePods (node gone, domain gone)
```

Domain disappears → simulation says pods reschedule fine → scale-down approved. But in reality, the tainted node's domain persists → pods unschedulable → scale-up → churn.

### Expected fix

CA should model the drain process faithfully: replace the removed node with a tainted, pod-less copy in the snapshot before running the scheduling simulation.
- With `nodeTaintsPolicy=Ignore` (default), the tainted node's domain stays → simulation correctly predicts unschedulable → scale-down blocked (no churn).
- With `nodeTaintsPolicy=Honor`, the tainted node's domain is excluded → simulation correctly predicts reschedulable → scale-down proceeds.

### PR DESCRIPTION
**Pull request by tallaxes**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it

Fixes scale-down/scale-up oscillation for pods with hard `TopologySpreadConstraints`.

PR #8164 added `RemoveNodeInfo(removedNode)` in `findPlaceFor()` to fix TSC pods always blocking scale-down. That fix may have been too aggressive - removing the node eliminates its topology domain from the simulation, but during actual drain the node is tainted and persists for some time. With the default `nodeTaintsPolicy=Ignore`, the kube-scheduler still counts the tainted node as a topology domain, making evicted pods unschedulable and triggering scale-up churn.

This PR replaces the bare `RemoveNodeInfo` with a "tainted ghost node": a deep copy of the node with the `ToBeDeletedByClusterAutoscaler` NoSchedule taint and no pods. This faithfully models the drain process and gives the scheduling simulation the same topology view that the real scheduler will have.

After `TrySchedulePods` completes, the ghost node is removed so that persisted snapshot state (used by subsequent `canPersist=true` simulations) correctly reflects the node being gone.

#### Behavior with the fix

| `nodeTaintsPolicy` | Simulation | Reality |
|---|---|---|
| `Ignore` (default) | Tainted domain counted, 0 pods → min=0 → unschedulable | Same |
| `Honor` | Tainted domain excluded → pods reschedulable | Same |

#### Which issue(s) this PR fixes:

Fixes #9287 

#### Tests

- Modified the existing simulator topology-spread case to expect `NoPlaceToMovePods` with the default `nodeTaintsPolicy` behavior
- Added a simulator case for `nodeTaintsPolicy: Honor` confirming node removal succeeds
- Added a scheduler-level table-driven test covering post-taint scheduling behavior for both policy values

#### Performance implications

The fix adds a `DeepCopy` + `RemoveNodeInfo` + `AddNodeInfo` sequence per simulated node removal, replacing the previous single `RemoveNodeInfo`. Was wondering about the impact, so ran some benchmarks. In my environment They appear to show very low constant overhead per node, independent of cluster size. As a fraction of total `SimulateNodeRemoval` time (which includes `TrySchedulePods`), this is <7% at 5 nodes and <1.7% at 200 nodes. Can share the code used, but also wondering if autoscaler has its own scheduling benchmarks that can be used to measure the impact.

#### Does this PR introduce a user-facing change?

```release-note
Pods with hard TopologySpreadConstraints using the default nodeTaintsPolicy will no longer cause scale-down/scale-up oscillation. The scale-down simulation now faithfully models the drain taint, matching real scheduler behavior. Pods using nodeTaintsPolicy: Honor are unaffected and continue to scale down correctly.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cluster-autoscaler/simulator/cluster.go [hunk 1]
```diff
@@ -212,6 +215,43 @@ func (r *RemovalSimulator) findPlaceFor(removedNode string, pods []*apiv1.Pod, n
...
+		return fmt.Errorf("couldn't get NodeInfo for removed node %s: %v", nodeName, err)
+	}
+	taintedNode := nodeInfo.Node().DeepCopy()
+	taintedNode.Spec.Taints = append(taintedNode.Spec.Taints, apiv1.Taint{
+		Key:    taints.ToBeDeletedTaint,
+		Value:  fmt.Sprint(timestamp.Unix()),
+		Effect: apiv1.TaintEffectNoSchedule,
+	})
+	if err = r.clusterSnapshot.RemoveNodeInfo(nodeName); err != nil {
+		return fmt.Errorf("couldn't remove NodeInfo for %s: %v", nodeName, err)
```
Comment (jackfrancis) [inline cluster-autoscaler/simulator/cluster.go]: micro nit: I think for every error scenario here (rare, obviously) the outcome will already be pre-determined by the time we enter this method, so we can probably do the condtional removal immediately after we prepare our nodeInfo object. That way we don't waste cycles doing an unnecessary DeepCopy.

File: cluster-autoscaler/simulator/cluster.go [hunk 2]
```diff
@@ -212,6 +215,43 @@ func (r *RemovalSimulator) findPlaceFor(removedNode string, pods []*apiv1.Pod, n
...
+	}
+	ghostNodeInfo := framework.NewNodeInfo(taintedNode, nodeInfo.LocalResourceSlices)
+	if nodeInfo.CSINode != nil {
```
Comment (jackfrancis) [inline cluster-autoscaler/simulator/cluster.go:254]: What are the pros/cons of adding this inside the `framework.NewNodeInfo` function itself?

```
// NewNodeInfo returns a new internal NodeInfo from the provided data.
func NewNodeInfo(node *apiv1.Node, slices []*resourceapi.ResourceSlice, csiNode *storagev1.CSINode, pods ...*PodInfo) *NodeInfo {
	result := &NodeInfo{
		schedNodeInfo:       schedulerframework.NewNodeInfo(),
		podsExtraInfo:       map[types.UID]PodExtraInfo{},
		LocalResourceSlices: slices,
        CSINode: csiNode,
	}
	if node != nil {
		result.schedNodeInfo.SetNode(node)
	}
	for _, pod := range pods {
		result.AddPod(pod)
	}
	return result
}
```

@gnufied was that meant to be a follow-up task? Seems surprising that we have an incomplete NodeInfo constructor func.

I'm happy to pick that up as an orthogonal task so that @tallaxes doesn't have to make this PR overly verbose :)

cc @towca

**Comment by towca** [comment]
@x13n I think you're very up to date with all the topology spread considerations, any chance you could review this one?

File: cluster-autoscaler/simulator/cluster.go (hunk 2 above)
Comment (tallaxes) [reply cluster-autoscaler/simulator/cluster.go:254]: Yeah, that touches a lot. Happy to contribute, but let's keep it separate.

Comment (gnufied) [reply cluster-autoscaler/simulator/cluster.go:254]: Yes, I am following it up on this release.  I am working on a set of updates to both autoscaler and k/k repo. that is scheduled for v1.36 - https://github.com/kubernetes/enhancements/issues/5030 , I will update CAS repo with this.

Comment (jackfrancis) [reply cluster-autoscaler/simulator/cluster.go:254]: sgtm, I'll close this thread on this PR

**Comment by x13n** [comment]
Yeah, replacing the node with a tainted one for scale down simulation makes sense to me on a high level. @jbtk volunteered to review this one.

File: cluster-autoscaler/simulator/cluster_scheduling_test.go [hunk 3]
```diff
@@ -0,0 +1,177 @@
...
+	//
+	// With default nodeTaintsPolicy=Ignore, PodTopologySpread still counts
+	// node1 as a domain with matchNum=0, so minMatchNum=0.
+	// Scheduling on node2: skew = (1+1) - 0 = 2 > maxSkew(1) → REJECT
+	// Scheduling on node3: skew = (1+1) - 0 = 2 > maxSkew(1) → REJECT
+	// Scheduling on node1: rejected by TaintToleration (NoSchedule)
+	//
+	// Result: pod is unschedulable on ALL nodes → CAS will trigger scale-up.
+	// -----------------------------------------------------------------------
+	t.Run("post_taint_scheduling_fails_with_default_nodeTaintsPolicy", func(t *testing.T) {
```
Comment (jbtk) [inline cluster-autoscaler/simulator/cluster_scheduling_test.go]: These two tests have very similar logic. Would it be possible to have these as different test cases of a single test?

Example test like this: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/core/static_autoscaler_test.go#L575

Comment (jbtk) [inline cluster-autoscaler/simulator/cluster_scheduling_test.go]: These tests are very similar. Can we make them be two test cases of a single test?

Example test with test cases: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/core/static_autoscaler_test.go#L575

File: cluster-autoscaler/simulator/cluster_test.go [hunk 4]
```diff
@@ -152,6 +152,30 @@ func TestSimulateNodeRemoval(t *testing.T) {
 	blocker2 := BuildTestPod("blocker2", 100, 100000)
 	blocker2.Spec.NodeName = "topo-n3"
 
+	// Same constraint but with NodeTaintsPolicy: Honor — ghost node's taint
+	// excludes it from domain counting, so removal succeeds even with maxSkew=1.
+	honorPolicy := apiv1.NodeInclusionPolicyHonor
+	honorTopoConstraint := topoConstraint
+	honorTopoConstraint.NodeTaintsPolicy = &honorPolicy
+
+	pod8 := BuildTestPod("p8", 100, 100000)
```
Comment (jbtk) [inline cluster-autoscaler/simulator/cluster_test.go]: It seems that using the p1-p10 names is not very descriptive. Would it be possible to have more descriptive pod names? Looking at the construction of the pods it also seems that we could extract the creation to some function and in the test cases call the function so that the test cases are self explanatory and do not require scrolling between the test case and the object definition.

**Review by jbtk — CHANGES_REQUESTED** [review]
The code looks good to me. I left small comments about the tests.

File: cluster-autoscaler/simulator/cluster_scheduling_test.go (hunk 3 above)
Comment (tallaxes) [reply cluster-autoscaler/simulator/cluster_scheduling_test.go]: Updated to a single table-driven test https://github.com/kubernetes/autoscaler/pull/9288/commits/e915357bd34efa0699685ac638619669b5589c83

File: cluster-autoscaler/simulator/cluster_test.go (hunk 4 above)
Comment (tallaxes) [reply cluster-autoscaler/simulator/cluster_test.go]: Made the test fixtures descriptive and local to each case so the scenarios are self-explanatory https://github.com/kubernetes/autoscaler/pull/9288/commits/143b8fe9332e66af33cabbc458625a1ef4aa1ef7

File: cluster-autoscaler/simulator/cluster_test.go [hunk 5]
```diff
@@ -160,49 +139,92 @@ func TestSimulateNodeRemoval(t *testing.T) {
...
-		{
-			name:        "topology spread constraint test - one node should be removable",
-			pods:        []*apiv1.Pod{pod5, pod6, pod7, blocker1, blocker2},
-			allNodes:    []*apiv1.Node{topoNode1, topoNode2, topoNode3},
-			nodeName:    topoNode1.Name,
-			toRemove:    &NodeToBeRemoved{Node: topoNode1, PodsToReschedule: []*apiv1.Pod{pod5}},
-			unremovable: nil,
-		},
+		func() simulateNodeRemovalTestConfig {
+			drainableReplicaPodA := buildReplicaSetPod("drainable-rs-pod-a", drainableNode.Name, 100, 100000)
```
Comment (jbtk) [inline cluster-autoscaler/simulator/cluster_test.go]: I would personally put these calls inline into the configuration and simplify this test definition into simple config instead of a function, but leaving it up to you as the goal of having the whole test definition in a single place is done. Thank you!

**Comment by jbtk** [comment]
/lgmt from me

@x13n or @BigDarkClown - could you have a look as approvers and people with context about topology spreading.

File: cluster-autoscaler/simulator/cluster_test.go (hunk 5 above)
Comment (tallaxes) [reply cluster-autoscaler/simulator/cluster_test.go]: I kind of like having everything related to a case in one place, but agree getting rid of functions makes it simpler. Done in https://github.com/kubernetes/autoscaler/pull/9288/commits/46a7983ce372f79af73b8e504a0a42c1826fbd50

**Comment by tallaxes** [comment]
Any objections to cherry-picking this into supported releases?
