### PR TITLE
Fix Autoscaling for worker nodes with invalid ProviderID

### LINKED ISSUE #6716: Cluster Autoscaler stops working when cluster has nodes with invalid server ID
**Which component are you using?**: cluster-autoscaler@1.29.0

While using autoscaler in Hetzner Cloud provider:
```bash
./cluster-autoscaler --cloud-provider=hetzner
```
Autoscaler stops working (continuous loop) with message:
```
E0416 12:21:58.365577       1 static_autoscaler.go:354] Failed to get node infos for groups: failed to check if server robot://1 exists error: failed to get servers for node root-minio-hcloud error: server not found
```
**Scenarios to catch this behaviour**:
1. join Hetzner Cloud worker node and than delete server via Hetzner Cloud Console or API
2. join Hetzner Dedicated worker node to cluster with ProviderID="robot://1" (other than valid "hcloud://[0-9]+")

**What did you expect to happen?**:

The autoscaler must function even when worker nodes do not have valid ProviderIDs. This will enable users to add Hetzner Dedicated worker nodes. Additionally, the cluster should continue to operate even when the server has been physically deleted.

### PR DESCRIPTION
**Pull request by maksim-paskal**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:
Fixes #6716 

#### Special notes for your reviewer:
This change fixes a bug that arises when the user's cluster includes worker nodes not from Hetzner Cloud, such as a Hetzner Dedicated server or any server resource other than Hetzner. It also corrects the behavior when a server has been physically deleted from Hetzner Cloud.

#### Does this PR introduce a user-facing change?
```release-note
Fixed an issue where the Hetzner provider breaks when nodes from other providers are present
```

### CODE REVIEW

File: cluster-autoscaler/cloudprovider/hetzner/hetzner_servers_cache.go [hunk 1]
```diff
@@ -136,7 +135,8 @@ func (m *serversCache) getServer(nodeIdOrName string) (*hcloud.Server, error) {
 		}
 	}
 
-	return nil, errors.New("server not found")
+	// return nil if server not found
+	return nil, nil
```
Comment (apricote) [inline cluster-autoscaler/cloudprovider/hetzner/hetzner_servers_cache.go:139]: This "fixes" two issues:

1. Deleted servers cause issues until the Kubernetes Node is deleted too
2. Servers with different Provider IDs than `hcloud://...` in the cluster break cluster-autoscaler

I think this is a good fix for the first "bug".

For the second bug, I think we should make this more explicit and handle it where we "parse" the provider ID. What do you think about this patch?

```patch
diff --git a/cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go b/cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go
index f75c69ee3..35a256f46 100644
--- a/cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go
+++ b/cluster-autoscaler/cloudprovider/hetzner/hetzner_manager.go
@@ -259,6 +259,12 @@ func (m *hetznerManager) addNodeToDrainingPool(node *apiv1.Node) (*hetznerNodeGr
 func (m *hetznerManager) serverForNode(node *apiv1.Node) (*hcloud.Server, error) {
        var nodeIdOrName string
        if node.Spec.ProviderID != "" {
+               if !strings.HasPrefix(node.Spec.ProviderID, providerIDPrefix) {
+                       // This cluster-autoscaler provider only handles Hetzner Cloud servers.
+                       // Any other provider ID prefix is invalid, and we return no server. Returning an error here breaks hybrid
+                       // clusters with nodes from Hetzner Cloud & Robot (or other providers).
+                       return nil, nil
+               }
                nodeIdOrName = strings.TrimPrefix(node.Spec.ProviderID, providerIDPrefix)
        } else {
                nodeIdOrName = node.Name
```

Comment (maksim-paskal) [reply cluster-autoscaler/cloudprovider/hetzner/hetzner_servers_cache.go:139]: That makes sense. Thanks.

**Comment by apricote** [comment]
Can you add a changelog entry to the PR description?

> #### Does this PR introduce a user-facing change?
>
> ```release-note
> Fixed an issue where the Hetzner provider breaks when nodes from other providers are present
> ```

Once this is merged, we should also port it all all current release branches (1.27-1.29). If you want you can do it, otherwise I will take care of it.

**Comment by maksim-paskal** [comment]
add `release-notes`, please port this commit to all available versions.

**Comment by apricote** [comment]
Thank you very much!

**Comment by apricote** [comment]
Backports:

- https://github.com/kubernetes/autoscaler/pull/6720
- https://github.com/kubernetes/autoscaler/pull/6721
- https://github.com/kubernetes/autoscaler/pull/6722
