### PR TITLE
fix: empty status configmap leads to nil ptr error

### LINKED ISSUE #5704: Empty `cluster-autoscaler-status` configmap results in panic
**Which component are you using?**:

**What version of the component are you using?**:

Component version:
v1.26.2

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"archive", BuildDate:"2023-03-19T19:47:22Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

TalosOS 1.3.7

**What did you expect to happen?**:

working/running daemon

**What happened instead?**:

panic

**How to reproduce it (as minimally and precisely as possible)**:

1. Clear out the `cluster-autoscaler-status` configmap
2. restart the cluster-autoscaler

**Anything else we need to know?**:

```
panic: assignment to entry in nil map

goroutine 72 [running]:
k8s.io/autoscaler/cluster-autoscaler/clusterstate/utils.WriteStatusConfigMap({0x5a5ced8, 0xc000461860}, {0x7ffdc3be3c15, 0x12}, {0xc001bc8d80, 0xd39}, 0xc001ab5920, {0x51162d1, 0x19})
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/clusterstate/utils/status.go:94 +0x42f
k8s.io/autoscaler/cluster-autoscaler/core.(*StaticAutoscaler).RunOnce.func1()
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/static_autoscaler.go:364 +0x17e
k8s.io/autoscaler/cluster-autoscaler/core.(*StaticAutoscaler).RunOnce(0xc00138b9a0, {0x4?, 0xc000077710?, 0x87e5e60?})
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/core/static_autoscaler.go:657 +0x2f0b
main.run(0xc0004b7900?, {0x5a2aa38, 0xc000aefa10})
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:449 +0x2cd
main.main.func2({0x5a20c98?, 0xc000684180?})
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/main.go:536 +0x25
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	/gopath/src/k8s.io/autoscaler/cluster-autoscaler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:211 +0x11b
```

### PR DESCRIPTION
**Pull request by vadasambar**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Fix nil pointer error if the status configmap is empty #5704.

#### Which issue(s) this PR fixes:

Fixes #5704 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cluster-autoscaler/clusterstate/utils/status_test.go [hunk 1]
```diff
@@ -95,6 +95,17 @@ func TestWriteStatusConfigMapExisting(t *testing.T) {
 	assert.True(t, ti.getCalled)
 	assert.True(t, ti.updateCalled)
 	assert.False(t, ti.createCalled)
+
+	// to test the case where configmap is empty
+	ti.configMap.Data = nil
```
Comment (vadasambar) [inline cluster-autoscaler/clusterstate/utils/status_test.go:100]: Test output without the fix:
```
(⎈ |teleport.dev.cloudservices.acquia.io-csd-hades82db5:default)➜  utils git:(fix/5704/fix-status-cm-nil-ptr-err) ✗ go test .
W0512 00:10:30.675808    3659 node_instances_cache.go:130] Entry cloudProviderNodeInstances is stale, refresh time is 2023-05-11 23:10:30.67579 +0530 IST m=-3599.987797575
W0512 00:10:30.675969    3659 node_instances_cache.go:130] Entry cloudProviderNodeInstances is stale, refresh time is 2023-05-11 23:10:30.67579 +0530 IST m=-3599.987797575
I0512 00:10:30.675979    3659 node_instances_cache.go:156] Start refreshing cloud provider node instances cache
I0512 00:10:30.675985    3659 node_instances_cache.go:168] Refresh cloud provider node instances cache finished, refresh took 2.775µs
--- FAIL: TestWriteStatusConfigMapExisting (0.00s)
panic: assignment to entry in nil map [recovered]
        panic: assignment to entry in nil map

goroutine 53 [running]:
testing.tRunner.func1.2({0x22f4980, 0x27596e0})
        /usr/local/go/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1399 +0x39f
panic({0x22f4980, 0x27596e0})
        /usr/local/go/src/runtime/panic.go:884 +0x212
k8s.io/autoscaler/cluster-autoscaler/clusterstate/utils.WriteStatusConfigMap({0x27853d8, 0xc000156160}, {0x251ecb9, 0xb}, {0x251bbe5, 0x8}, 0x0, {0x2525a41, 0x11})
        /Users/suraj.bankar/work/autoscaler/cluster-autoscaler/clusterstate/utils/status.go:97 +0x42f
k8s.io/autoscaler/cluster-autoscaler/clusterstate/utils.TestWriteStatusConfigMapExisting(0x0?)
        /Users/suraj.bankar/work/autoscaler/cluster-autoscaler/clusterstate/utils/status_test.go:101 +0x245
testing.tRunner(0xc0000c4820, 0x2605020)
        /usr/local/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1493 +0x35f
FAIL    k8s.io/autoscaler/cluster-autoscaler/clusterstate/utils 1.039s
FAIL
```

**Review by elmiko — COMMENTED** [review]
good find
/lgtm

**Comment by vadasambar** [comment]
@elmiko I think we need `approved` label to get this merged and maybe you need to merge the PR as well. 
image

**Comment by elmiko** [comment]
yes, that is correct @vadasambar . we will need an approver to review this (i don't have those privileges).
