### PR TITLE
Fix admission controller

### LINKED ISSUE #4557: VPA E2E tests are failing
VPA e2e tests are consistently failing. They were consistently passing (flake once every few days) until recently.

For `full` suite:
* Last green run was on 2021-12-20 at 16:15 CET [prow link](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-full/1472948804343828480),
* First red run was on 2021-12-20 at 18:15 CET [prow link](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-full/1472979003844333568).

For `admission-controller`:
* Last green run was on 2021-12-20 at 16:14 CET [prow link](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-admission-controller/1472948552723337216),
* First red run was on 2021-12-20 at 18:14 CET [prow link](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-admission-controller/1472978752269979648).

For `actuation`:
* Last green run was on 2021-12-20 at 16:14 CET [prow link](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-actuation/1472948552706560000),
* First red run was on 2021-12-20 at 18:14 CET [prow link](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-actuation/1472978752215453696).

It looks like admission-controller is broken. I suspect that the culprit is #4537

### PR DESCRIPTION
**Pull request by jbartosik**
Admission controller responses are rejected with

```
failed calling webhook "vpa.k8s.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
```

Fix this by setting fields API server expects us to set.

Fixes #4557

### CODE REVIEW

**Comment by jbartosik** [comment]
@adriananeci FYI I think I found and fixed the problem

I deployed VPA with this change to my cluster, ran e2e `admission-controller` tests there and they passed.

**Comment by jbartosik** [comment]
@mwielgus  @kgolab please take a look

File: vertical-pod-autoscaler/pkg/admission-controller/logic/server.go [hunk 1]
```diff
@@ -73,7 +73,6 @@ func (s *AdmissionServer) admit(data []byte) (*v1.AdmissionResponse, metrics_adm
 	var err error
 	resource := metrics_admission.Unknown
 
-	response.UID = ar.Request.UID
```
Comment (kgolab) [inline vertical-pod-autoscaler/pkg/admission-controller/logic/server.go:76]: Why remove this?

Comment (adriananeci) [reply vertical-pod-autoscaler/pkg/admission-controller/logic/server.go:76]: It was defined twice. See few lines above.

**Comment by kgolab** [comment]
Thanks, LGTM.

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve
