### PR TITLE
fix(VPA): Do not update webhook CA when registerWebhook is disabled

### LINKED ISSUE #8248: [VPA] Admission cert reloader use a hardcoded MutatingWebhookConfiguration name
**Which component are you using?**:

VPA admission controller

/area vertical-pod-autoscaler

**What version of the component are you using?**:

Component version: v1.4.1

**What k8s version are you using (`kubectl version`)?**: 

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.33.1
Kustomize Version: v5.6.0
Server Version: v1.32.3-eks-4096722
</pre></details>

**What environment is this in?**:

AWS EKS

with the following flag:
- --register-webhook=false
- --reload-cert=true

**What did you expect to happen?**:

The controller should not try to update the *MutatingWebhookConfiguration* because `--register-webhook=false`.

**What happened instead?**:

The controller try to get the `vpa-webhook-config` *MutatingWebhookConfiguration* which doesn't exists in our environment (it is named differently).
However, the certificates should be reloaded successfully.

**How to reproduce it (as minimally and precisely as possible)**:

Run the admision controller with `--register-webhook=false` & `--reload-cert=true` and without a `vpa-webhook-config` *MutatingWebhookConfiguration* in the cluster.
Modify the cert CA to trigger a reload.

**Anything else we need to know?**:

We use cert-manager to create the certificates and update the *MutatingWebhookConfiguration*, so there is no need for the admission controller to update it.

### PR DESCRIPTION
**Pull request by vflaux**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This disable the update of CA in the *MutatingWebhookConfiguration* by the admission controller when the `registerWebhook` option is not enabled and the CA file changed.

#### Which issue(s) this PR fixes:

Fixes #8248

#### Does this PR introduce a user-facing change?

```release-note
Vertical Pod Autoscaler Admission Controller will not try to update the `vpa-webhook-config` MutatingWebhookConfiguration when `registerWebhook` is disabled.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: vertical-pod-autoscaler/pkg/admission-controller/certs.go [hunk 1]
```diff
@@ -68,8 +68,10 @@ func (cr *certReloader) start(stop <-chan struct{}) error {
 	if err = watcher.Add(cr.tlsKeyPath); err != nil {
 		return err
 	}
-	if err = watcher.Add(cr.clientCaPath); err != nil {
-		return err
+	if cr.mutatingWebhookClient != nil {
+		if err = watcher.Add(cr.clientCaPath); err != nil {
+			return err
+		}
```
Comment (omerap12) [inline vertical-pod-autoscaler/pkg/admission-controller/certs.go:75]: You could combine these conditions into one line to keep it consistent with the rest of the code:
```go
if cr.mutatingWebhookClient != nil && err = watcher.Add(cr.clientCaPath); err != nil {
    return err
}
```
But I'm not fully sure about it.

File: vertical-pod-autoscaler/pkg/admission-controller/certs.go [hunk 2]
```diff
@@ -123,6 +125,9 @@ func (cr *certReloader) load() error {
 
 func (cr *certReloader) reloadWebhookCA() error {
 	client := cr.mutatingWebhookClient
+	if client == nil {
+		return nil
+	}
```
Comment (omerap12) [inline vertical-pod-autoscaler/pkg/admission-controller/certs.go]: This implementation seems problematic. There could be an edge case where client is `nil` but `registerWebhook` is set to true, which would indicate an inconsistent state. I suggest first checking whether we need to reload the webhook CA (based on `registerWebhook`), and then handle errors accordingly based on that condition.

**Review by omerap12 — COMMENTED** [review]
Thanks for this

File: vertical-pod-autoscaler/pkg/admission-controller/certs.go (hunk 2 above)
Comment (omerap12) [reply vertical-pod-autoscaler/pkg/admission-controller/certs.go]: The decision whether to reload the webhook CA should be made outside this function. If `reloadWebhookCA()` is called, it means we've already determined we need to reload, so a `nil` client should be treated as an error rather than silently ignored.

File: vertical-pod-autoscaler/pkg/admission-controller/certs.go (hunk 1 above)
Comment (vflaux) [reply vertical-pod-autoscaler/pkg/admission-controller/certs.go:75]: Unfortunately you can't have a condition then an assignment in the same if statement.
```
$ go vet ./pkg/admission-controller
# k8s.io/autoscaler/vertical-pod-autoscaler/pkg/admission-controller
# [k8s.io/autoscaler/vertical-pod-autoscaler/pkg/admission-controller]
vet: pkg/admission-controller/certs.go:71:5: cannot convert cr.mutatingWebhookClient != nil (untyped bool value) to type interface{Error() string}
```

Comment (omerap12) [reply vertical-pod-autoscaler/pkg/admission-controller/certs.go:75]: Yeah I figured. leave it as is then :)

File: vertical-pod-autoscaler/pkg/admission-controller/certs.go [hunk 3]
```diff
@@ -123,6 +125,9 @@ func (cr *certReloader) load() error {
 
 func (cr *certReloader) reloadWebhookCA() error {
 	client := cr.mutatingWebhookClient
+	if client == nil {
```
Comment (omerap12) [inline vertical-pod-autoscaler/pkg/admission-controller/certs.go:129]: Correct me if I'm wrong, but in the current implementation, if the flag is off, then `mutatingWebhookClient` is set to nil, which means the `reloadWebhookCA` function will always return an error?

Comment (vflaux) [reply vertical-pod-autoscaler/pkg/admission-controller/certs.go:129]: Yes but we don't watch the file when `mutatingWebhookClient` is nil so we should never call `reloadWebhookCA()`.

Comment (vflaux) [reply vertical-pod-autoscaler/pkg/admission-controller/certs.go:129]: I use `mutatingWebhookClient` as an indicator of whether `registerWebhook` is enabled, but introducing a new boolean variable in the struct `certReloader` might make the code clearer and easier to understand?

Comment (omerap12) [reply vertical-pod-autoscaler/pkg/admission-controller/certs.go:129]: Understood. thanks! adding a comment above line 71 (https://github.com/kubernetes/autoscaler/pull/8249/files#diff-504643e3760ffc997b03797073b201284f6483f8276acd1cf9057c8734e9f5b9R71) will be enough.

**Review by omerap12 — COMMENTED** [review]
Thanks for this!
/lgtm
/assign @adrianmoisey

**Comment by adrianmoisey** [comment]
Makes sense, thanks
/approve

@omerap12 should we also backport this change?

**Comment by omerap12** [comment]
> Makes sense, thanks /approve
> 
> @omerap12 should we also backport this change?

Yup!

**Comment by adrianmoisey** [comment]
This was added in 1.4, so only need to do 1 cherry pick:
/cherry-pick vpa-release-1.4
