### PR TITLE
Clarify simulation for removal log statement

### LINKED ISSUE #6170: Info message at the start of node removal simulation could be more clear
When monitoring the CA logs, we see a message that is essentially incomplete.  I'm hoping we can submit a change to make the message more clear.

It currently looks as follows:
```
I1003 18:48:06.916732       1 cluster.go:155] ip-10-0-41-141.ec2.internal for removal
```
and would propose that it be updated to:
```
I1003 18:48:06.916732       1 cluster.go:155] Simulating node ip-10-0-41-141.ec2.internal for removal
```
since it appears in [`SimulateNodeRemoval()`](https://github.com/kubernetes/autoscaler/blob/2f7c61e13bd1cbfc0ba4085fb84bd692a1e9ac6e/cluster-autoscaler/simulator/cluster.go#L159).

---

**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

1.27.2

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4-eks-2d98532
</pre></details>

**What environment is this in?**:

AWS EKS

**What did you expect to happen?**:

Informational log message could be more clear:
```
I1003 18:48:06.916732       1 cluster.go:155] ip-10-0-41-141.ec2.internal for removal
```

**What happened instead?**:

N/A

**How to reproduce it (as minimally and precisely as possible)**:

Monitor the CA POD log when there's at least one candidate for scale-down.

**Anything else we need to know?**:

Nothing.  I'm hoping I can submit a fix that would make the message appear as:
```
I1003 18:48:06.916732       1 cluster.go:155] Simulating node ip-10-0-41-141.ec2.internal for removal
```

### PR DESCRIPTION
**Pull request by kevin-bates**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR helps improve supportability by improving the clarity of an informational logging statement that adds context for the log's reader.  The message will go from:
```
I1003 18:48:06.916732       1 cluster.go:155] ip-10-0-41-141.ec2.internal for removal
```
to:
```
I1003 18:48:06.916732       1 cluster.go:155] Simulating node ip-10-0-41-141.ec2.internal for removal
```

Previously, it was difficult to determine the _for removal_ action.  Also, prefixing the node's name with `node` is consistent with other node-named log statements.

#### Which issue(s) this PR fixes:

Fixes #6170

### CODE REVIEW

File: cluster-autoscaler/simulator/cluster.go [hunk 1]
```diff
@@ -156,7 +156,7 @@ func (r *RemovalSimulator) SimulateNodeRemoval(
 	if err != nil {
 		klog.Errorf("Can't retrieve node %s from snapshot, err: %v", nodeName, err)
 	}
-	klog.V(2).Infof("%s for removal", nodeName)
+	klog.V(2).Infof("Simulating node %s for removal", nodeName)
```
Comment (x13n) [inline cluster-autoscaler/simulator/cluster.go:159]: nit: I'd drop `for`: `Simulating node %s removal` seems to reflect exactly what's going on.

**Review by x13n — COMMENTED** [review]
Thanks for the change! This looks good to me, leaving only one super minor comment. Feel free to cancel the hold if you disagree and want to merge as-is.

/lgtm
/approve
/hold

File: cluster-autoscaler/simulator/cluster.go (hunk 1 above)
Comment (kevin-bates) [reply cluster-autoscaler/simulator/cluster.go]: Thank you @x13n.  That's more concise - I agree.  (Change pushed.)

**Comment by x13n** [comment]
Thanks!

/lgtm

**Comment by Shubham82** [comment]
As the above nit is addressed, remove the hold label
/hold cancel
