### PR TITLE
fix(clusterapi): HasInstance with namespace prefix

### LINKED ISSUE #6774: clusterapi: `HasInstance` function tries to find machine with wrong key
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
latest master

**What k8s version are you using (`kubectl version`)?**:
1.28.5

**What environment is this in?**:
clusterapi provider running in an CAPZ cluster

**What did you expect to happen?**:
HasInstance method is able to find Machine which exists and does not report `machine not found for node: X`

**What happened instead?**:
Lookup of machine is using a wrong key. 

The store contains items using `{{cluster-namespace}}/{{machine-name}}` but the lookup uses only `{{machine-name}}` as the key. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup a CAPZ
2. Start cluster-autoscaler
3. Set a breakpoint in `clusterapi_controller.go#findMachine()`
4. Go into store find and compare the lookup key with the existing keys in the cache/informer

**Anything else we need to know?**:
Autoscaler was run in debug mode using following flags:

```bash
--cloud-provider=clusterapi 
--namespace=kube-system 
--node-group-auto-discovery=clusterapi:clusterName={{clusterName}},namespace={{managementClusterNamespace}}
--kubeconfig=~/.kube/{{clusterName}}.yaml 
--cloud-config=~/.kube/{{management-cluster}} 
--ignore-daemonsets-utilization=true 
--logtostderr=true 
--max-node-provision-time=0m30s 
--scale-down-delay-after-add=2m
--scale-down-unneeded-time=2m
--scan-interval=10s
--stderrthreshold=info
--v=4
--leader-elect=false
```

I'm not sure if there are specific flags which trigger the store keys being different. I'm going to look this up. 
Ping @MaxFedotov - the `HasInstance` method was introduced in #6708 and maybe we could figure out what is different in our envs?

### PR DESCRIPTION
**Pull request by mweibel**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
fixes lookup of Machines in MachineInformer store for the `HasInstance` case

#### Which issue(s) this PR fixes:

Fixes #6774

#### Special notes for your reviewer:
It would be good to verify this with other kind of clusters and/or flags (I'm testing on a CAPZ cluster) to make sure the lookup works in all cases.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mweibel** [comment]
ping @elmiko @MaxFedotov for authoring/reviewing the original PR #6708

**Comment by MaxFedotov** [comment]
@mweibel Thanks, that's my bad - I was looking as an example at `findMachineByProviderID` function:
https://github.com/kubernetes/autoscaler/blob/4f1c8e69a8a4031a531596c26718a262d4b6b716/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go#L335-L336

Although there is a test for this function, which passed without errors, there are two problems in it (which I missed completely): 
1) In `TestControllerFindMachineByProviderID` the part where machine is found using `MachineAnnotation` on node is skipped:
https://github.com/kubernetes/autoscaler/blob/4f1c8e69a8a4031a531596c26718a262d4b6b716/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go#L742-L750

2) When test data is generated, `MachineAnnotation` on `Node` is constructed using `namespace/machine.Name` format:
https://github.com/kubernetes/autoscaler/blob/4f1c8e69a8a4031a531596c26718a262d4b6b716/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go#L461

While in `cluster-api` it is just `machine.Name`:
https://github.com/kubernetes-sigs/cluster-api/blob/b29e26c0210d12fffb1c1d59e5bbcd492242801e/internal/controllers/machine/machine_controller_noderef.go#L109

Also, `ClusterNamespaceAnnotation` is not set at all.

So your logic in this case is correct, thanks for finding this out!

But to prevent such problems in the future, we need to update tests as well.  

@elmiko WDYT? I can make a separate issue and update all tests.

**Comment by mweibel** [comment]
@MaxFedotov thanks!

I tried updating the tests by doing the following change:

```patch
diff --git a/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go b/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
index fc89fdae5..e374ea447 100644
--- a/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
+++ b/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
@@ -458,7 +458,8 @@ func makeLinkedNodeAndMachine(i int, namespace, clusterName string, owner metav1
                ObjectMeta: metav1.ObjectMeta{
                        Name: fmt.Sprintf("%s-%s-node-%d", namespace, owner.Name, i),
                        Annotations: map[string]string{
-                               machineAnnotationKey: fmt.Sprintf("%s/%s-%s-machine-%d", namespace, namespace, owner.Name, i),
+                               machineAnnotationKey:          fmt.Sprintf("%s-%s-machine-%d", namespace, owner.Name, i),
+                               clusterNamespaceAnnotationKey: namespace,
                        },
                },
                Spec: corev1.NodeSpec{
```

As a result `TestControllerFindMachineFromNodeAnnotation` on line 1252-1257 fails because it can't find the machine because the `machineAnnotationKey` value doesn't match with what is in `Node.Spec.ProviderID`. I'm unsure what to change there currently, because Azure is a special case already (`normalizedProviderString` treats VMSS as a special case) and I'm not sure what other providers do. 
Might keep digging a bit more but in case you have an idea or want to do a follow-up, I'm happy too :)

**Comment by jackfrancis** [comment]
/test pull-cluster-autoscaler-e2e-azure

@mweibel I'm maintainining some Azure-infra cluster-autoscaler tests, one scenario of which includes the clusterapi provider (running in Azure via CAPZ), so this test run will get some basic signal against your change

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go [hunk 1]
```diff
@@ -86,8 +87,9 @@ func (p *provider) NodeGroupForNode(node *corev1.Node) (cloudprovider.NodeGroup,
 // HasInstance returns whether a given node has a corresponding instance in this cloud provider
 func (p *provider) HasInstance(node *corev1.Node) (bool, error) {
 	machineID := node.Annotations[machineAnnotationKey]
+	ns := node.Annotations[clusterNamespaceAnnotationKey]
```
Comment (elmiko) [inline cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go:90]: if the annotation is not present, or we fail to get it, what happens?

**Review by elmiko — COMMENTED** [review]
i think this looks good, just a question about failures

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go [hunk 2]
```diff
@@ -86,8 +87,9 @@ func (p *provider) NodeGroupForNode(node *corev1.Node) (cloudprovider.NodeGroup,
...
 
-	machine, err := p.controller.findMachine(machineID)
+	machine, err := p.controller.findMachine(path.Join(ns, machineID))
```
Comment (jackfrancis) [inline cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go:92]: I'm a bit confused how we could update the machine lookup key in this way and not have that break things.

Comment (elmiko) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go:92]: i think this would work, unless `ns` was empty perhaps? but if it ever ran on windows it would break. probably better if we just use a `fmt.Sprintf` instead.

Comment (mweibel) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go:92]: > I'm a bit confused how we could update the machine lookup key in this way and not have that break things.

To make sure I understood you correctly: are you worried about future refactorings where we'd change how the machine lookup key is created in the informer? 

The question triggered a few questions I had about the informer and how it's set up. 
Looking at the code and the debug output I see the following:

- machineInformer `keyFunc` is `k8s.io/client-go/tools/cache.DeletionHandlingMetaNamespaceKeyFunc`
- it additionally adds an indexer by providerID using `indexMachineByProviderID`

The `keyFunc` uses [ObjectNames](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/object-names.go) to construct the namespace/name string. 

The lookup therefore can be done either by the `providerID` (which we don't have in the corev1.Node object) or by `namespace/name` string. 

Using `path.Join` or `fmt.Sprintf` doesn't matter much, probably. If the `ns` is not set, the machine won't be found. In the clusterapi codebase I saw both `fmt.Sprintf` and `path.Join` being used, for slightly different or similar purposes. 

I'm happy to change or keep it as-is - please let me know your preference.

**Comment by mweibel** [comment]
btw it would be great if somebody could give this an /ok-to-test. Thanks!

**Comment by elmiko** [comment]
apologies @mweibel i lost track of this PR a little,  wonder if there were any further thoughts from @jackfrancis about the last comment?

**Comment by mweibel** [comment]
bumping this hoping to get a reply from @jackfrancis regarding what @elmiko asked :)

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go (hunk 2 above)
Comment (jackfrancis) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go:92]: This is gonna sound dumb but I think I didn't realize that the intention of this change was literally to fix a broken thing. Naively I assumed the current lookup worked, and so I didn't grok how it would continue to work w/ the introduction of the namespace prefix. Now I understand (if I understand correctly) that the current lookup implementation is broken!

**Comment by jackfrancis** [comment]
code lgtm

What's the latest on the viability of updating the tests as per the above conversation between @mweibel and @MaxFedotov?

**Comment by mweibel** [comment]
@jackfrancis thanks for the reminder!

I had another look this morning on the tests and actually found a missing update to a `.findMachine()` call thanks to updating the tests accordingly to what @MaxFedotov mentioned! Nice catch there :+1: 

Would be great to get another review. 

Given that I overlooked one call for findMachine I wonder if we should adjust the functions signature to accept a namespace/name or something similar to avoid potential issues in the future.

**Comment by elmiko** [comment]
@mweibel i'll take a look this week, thanks for the update!

**Review by elmiko — COMMENTED** [review]
this looks good to me, thanks for keeping it alive.

i'm adding lgtm for now to give a last chance for reviews, if nothing comes up i will approve by end of week (unless someone beats me to it XD).

/lgtm

**Comment by elmiko** [comment]
it seems like there are no further requests or objections, so i am going to approve this. thanks everyone!

/approve

**Comment by mweibel** [comment]
@elmiko thanks for merging! can you take care of including this in the next patch release, too? 🙇

**Comment by elmiko** [comment]
@mweibel yes,i will try to make sure that it's in the next patch release.
