### PR TITLE
Fix error message for long-waiting operations

### LINKED ISSUE #1661: Azure AKS cluster autoscaler hangs during up scaling
CloudProvider: Azure AKS
Kubernetes version: 1.11.5
Cluster Autoscaler version: 1.3.5
ACS-Engine version: v0.26.3-aks

In our setup we run an Azure AKS cluster with multiple nodes that each run a single pod requiring all resources on the node. The pods are part of a statefulset that we scale quite aggressively from 2 to 20 and then back to 2 replicas at regular intervals.

Sometimes (<10%) when scaling up nodes the whole process takes considerable longer time than usual and this is often associated with the autoscaler pod crashing. When everything works normally the average time for us is 21 minutes when going from 2 to 20 nodes and when not working scaling up can take as long as 75 minutes.

Attached logs and screenshot of the `cluster_autoscaler_nodes_count` metric for when the upscaling stopped working after scaling up to 16 nodes and then nothing happens for 30 minutes.

screenshot 2019-02-07 at 18 40 29

Logs before crash (16:30 to 17:15)
[autoscaler-azure-cluster-autoscaler-7c8df96664-h8fs4-before.log](https://github.com/kubernetes/autoscaler/files/2847708/autoscaler-azure-cluster-autoscaler-7c8df96664-h8fs4-before.log)

Logs after crash (17:15 to 17:45)
[autoscaler-azure-cluster-autoscaler-7c8df96664-h8fs4-after.log](https://github.com/kubernetes/autoscaler/files/2847710/autoscaler-azure-cluster-autoscaler-7c8df96664-h8fs4-after.log)

Relevant log lines are around this lines
```
E0207 16:49:23.319809       1 static_autoscaler.go:283] Failed to scale up: failed to increase node group size: Code="" Message=""
```

cc @feiskyer

### PR DESCRIPTION
**Pull request by feiskyer**
Get HTTP responses together with error, so that we could get full error
messages. It also fixes some edge cases for success responses.

Fix #1661.

### CODE REVIEW

**Comment by feiskyer** [comment]
cc @andyzhangx @ritazh

File: cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go [hunk 1]
```diff
@@ -226,7 +240,20 @@ func (agentPool *ContainerServiceAgentPool) setACSNodeCount(count int) error {
 		klog.Errorf("Failed to update ACS cluster (%q): %v", agentPool.clusterName, err)
 		return err
 	}
-	return future.WaitForCompletionRef(updateCtx, acsClient.Client)
+
+	err = future.WaitForCompletionRef(updateCtx, acsClient.Client)
+	resp := future.Response()
+	if isSuccessHTTPResponse(resp) {
```
Comment (andyzhangx) [inline cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go]: the code is a little duplicate in many places, what about write`isSuccessHTTPResponse` as
```
func isSuccessHTTPResponse(resp *http.Response) (bool, err error)
```
if failed, then return error message directly.

File: cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go [hunk 2]
```diff
@@ -209,15 +210,21 @@ func (as *AgentPool) IncreaseSize(delta int) error {
...
 	ctx, cancel := getContextWithCancel()
 	defer cancel()
-	_, err = as.manager.azClient.deploymentsClient.CreateOrUpdate(ctx, as.manager.config.ResourceGroup, newDeploymentName, newDeployment)
 	klog.V(3).Infof("Waiting for deploymentsClient.CreateOrUpdate(%s, %s, %v)", as.manager.config.ResourceGroup, newDeploymentName, newDeployment)
-	if err != nil {
-		return err
+	resp, err := as.manager.azClient.deploymentsClient.CreateOrUpdate(ctx, as.manager.config.ResourceGroup, newDeploymentName, newDeployment)
+	if isSuccessHTTPResponse(resp) {
+		klog.V(3).Infof("deploymentsClient.CreateOrUpdate(%s, %s, %v) success", as.manager.config.ResourceGroup, newDeploymentName, newDeployment)
+		as.curSize = int64(expectedSize)
```
Comment (andyzhangx) [inline cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go]: any code comments for the these two lines of code, why we set here since it's already succeeded?
```
		as.curSize = int64(expectedSize)
		as.lastRefresh = time.Now()
```

Comment (feiskyer) [reply cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go]: This is for updating cache.

File: cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go (hunk 1 above)
Comment (feiskyer) [reply cluster-autoscaler/cloudprovider/azure/azure_container_service_pool.go]: Good catch, would fix in the new commit.

File: cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go (hunk 2 above)
Comment (andyzhangx) [reply cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go]: then would you add the comments?

Comment (feiskyer) [reply cluster-autoscaler/cloudprovider/azure/azure_agent_pool.go]: of course
