### PR TITLE
Fix/asg resource tags for 1.26.x

### LINKED ISSUE #5164: Extended resources provided by ASG via tags is not working
**Which component are you using?**:
autoscaler

**What version of the component are you using?**:
 1.25.0-alpha.0 AND 1.23.1

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-13T19:57:43Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:19:57Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**:
sanbox ( AWS )

**What did you expect to happen?**:
I tried to use extended resource defined as tag in ASG according documentation for AWS it should be `k8s.io/cluster-autoscaler/node-template/resources/<resource-name>` https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.23.1/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup . This sould work at least for node-group-auto-discovery mode. Is anybody successfully using it?

**What happened instead?**:
This tag is never read or ignored. CA is still complaining about insufficient resource and not scaling up.

**How to reproduce it (as minimally and precisely as possible)**:
Add extended resource as descirbe in https://kubernetes.io/docs/tasks/configure-pod-container/extended-resource/
Add  `k8s.io/cluster-autoscaler/node-template/resources/<resource-name>` tag with same reasonable value to ASG

**Anything else we need to know?**:
I did some tests, it looks like this is never executed https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/aws_manager.go#L412

### PR DESCRIPTION
**Pull request by paleozogt**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Applies #5214 to 1.26 (since 1.27 seems like its a long way off from release).

#### Which issue(s) this PR fixes:

Fixes #5164

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cluster-autoscaler/main.go [hunk 1]
```diff
@@ -396,6 +396,7 @@ func buildAutoscaler(debuggingSnapshotter debuggingsnapshot.DebuggingSnapshotter
 			nodeInfoComparatorBuilder = nodegroupset.CreateAzureNodeInfoComparator
 		} else if autoscalingOptions.CloudProviderName == cloudprovider.AwsProviderName {
 			nodeInfoComparatorBuilder = nodegroupset.CreateAwsNodeInfoComparator
+			opts.Processors.TemplateNodeInfoProvider = nodeinfosprovider.NewAsgTagResourceNodeInfoProvider(nodeInfoCacheExpireTime, *forceDaemonSets)
```
Comment (gjtempleton) [inline cluster-autoscaler/main.go:399]:
```suggestion
			opts.Processors.TemplateNodeInfoProvider = nodeinfosprovider.NewAsgTagResourceNodeInfoProvider(nodeInfoCacheExpireTime)
```

Comment (paleozogt) [reply cluster-autoscaler/main.go]: Oops looks like I brought over a 1.27-ish part of the commit.

**Comment by x13n** [comment]
/lgtm

But leaving approval to aws owners

/assign @gjtempleton @jaypipes
