### PR TITLE
make DecreaseTargetSize more accurate for clusterapi

### LINKED ISSUE #7928: clusterapi provider can cause autoscaler to stop processing node groups when failing to decrease target size
when a single node group (MachineDeployment, MachineSet, or MachinePool) has an error, it can cause the autoscaler to fail on scheduling any new nodes. the primary way to detect this is to see the failre to decrease target size errors in the logs. for example:

```
I0305 12:53:48.487412       1 static_autoscaler.go:709] Decreasing size of MachineSet/<obfuscated>, expected=2 current=1 delta=-1
E0305 12:53:48.687985       1 static_autoscaler.go:448] Failed to fix node group sizes: failed to decrease MachineSet/<obfuscated>: attempt to delete existing nodes targetSize:2 delta:-1 existingNodes: 2
```

**Which component are you using?**:

/area cluster-autoscaler

**What version of the component are you using?**:

Component version: cluster-autoscaler-1.32

i have also reproduced this on versions back to 1.28

**What k8s version are you using (`kubectl version`)?**:

1.32, but also happens on kubernetes back to 1.28 (and further)

**What environment is this in?**:

clusterapi

**What did you expect to happen?**:

i would expect the autoscaler to continue creating nodes even if there is a failure in one node group.

**What happened instead?**:

the autoscaler will not process any node groups after the failed one, in effect this stops scaling for new workloads.

**How to reproduce it (as minimally and precisely as possible)**:

a way to reproduce this is:

* create 2 machinesets, with one of them pointing to an infrastructure template that creates machines with a bad instance sku for the platform. the second machineset should have a valid sku.
* add a workload that would cause the cluster to scale out.
* observe the machines in the first machineset go into failure, and no new nodes will be created in the good machineset

**Anything else we need to know?**:

this can be a very tricky scenario to capture as it depends on the ordering of the node group.

it can occur frequently when a node group does not have quota for the instance type that is requested.

this is related to #6128 , except the platform is clusterapi instead of aws

### PR DESCRIPTION
**Pull request by elmiko**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

this change ensures that when DecreaseTargetSize is counting the nodes that it does not include any instances which are considered to be pending (i.e. not having a node ref), deleting, or are failed. this change will allow the core autoscaler to then decrease the size of the node group accordingly, instead of raising an error.

This change also add some code to the unit tests to make detection of this condition easier.

#### Which issue(s) this PR fixes:

Fixes #7928 

#### Does this PR introduce a user-facing change?

```release-note
the log messages related to the DecreaseTargetSize function have been updated to better reflect the names of the values.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by elmiko** [comment]
hmm, not sure about the test failures. i didn't change any dependencies but it seems to be complaining about them.

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go [hunk 1]
```diff
@@ -203,11 +203,28 @@ func (ng *nodegroup) DecreaseTargetSize(delta int) error {
...
+	// where an instance is created, but cannot become a node due to cloud provider
+	// issues such as quota limitations, and thus the autoscaler needs to properly
+	// set the size of the node group. without this adjustment, the core autoscaler
+	// will become confused about the state of nodes and instances in the clusterapi
+	// provider.
+	actualNodes := 0
+	for _, node := range nodes {
+		if !isPendingMachineProviderID(normalizedProviderID(node.Id)) &&
+			!isFailedMachineProviderID(normalizedProviderID(node.Id)) &&
+			!isDeletingMachineProviderID(normalizedProviderID(node.Id)) {
```
Comment (jackfrancis) [inline cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go:217]: Is it not possible to do something like `if node.Status.State == cloudprovider.InstanceDeleting {` instead of mucking with the providerID string and then having to do string in-line mutations in order to extract the providerID bit when we need it?

Comment (elmiko) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go:217]: i'll have to investigate that deeper to see if it would work.

i tried to follow the pattern in https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go#L597 which returns a list of provider ids, and not specifically the node objects.

Comment (elmiko) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go:217]: i looked at the code a little more, part of the problem here is that we are not filling in all the details for the `Instances` structure that is returned as part of `nodes`. see https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go#L241-L245

i had thought about improving that part of the function to set the proper state for the Instance, but that is a much larger change than what i'm proposing, and it would also rely on using the provider string mutation method.

Comment (jackfrancis) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go:217]: ACK, let's move forward with a more targeted fix, acknowledging that some of our current difficulty is that our foundational node accounting is incomplete. Pending time/priority, I think addressing that will reduce these edge cases in the long term.

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go [hunk 2]
```diff
@@ -339,6 +343,15 @@ func (c *machineController) findMachineByProviderID(providerID normalizedProvide
 	return c.findMachine(path.Join(ns, machineID))
 }
 
+func isDeletingMachineProviderID(providerID normalizedProviderID) bool {
```
Comment (jackfrancis) [inline cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go:346]: let's UT this function discretely for basic input/output determinism hygiene

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go [hunk 3]
```diff
@@ -339,6 +343,15 @@ func (c *machineController) findMachineByProviderID(providerID normalizedProvide
...
+	return strings.HasPrefix(string(providerID), deletingMachinePrefix)
+}
+
+func machineKeyFromDeletingMachineProviderID(providerID normalizedProviderID) string {
```
Comment (jackfrancis) [inline cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go:350]: ditto above comment about UT

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go [hunk 4]
```diff
@@ -610,6 +623,12 @@ func (c *machineController) findScalableResourceProviderIDs(scalableResource *un
 
 		if found {
 			if providerID != "" {
+				// If the machine is deleting, prepend the deletion guard on the provider id
+				// so that it can be properly filtered when counting the number of nodes and instances.
+				if !machine.GetDeletionTimestamp().IsZero() {
+					klog.V(4).Infof("Machine %q has a non-zero deletion timestamp", machine.GetName())
+					providerID = fmt.Sprintf("%s%s_%s", deletingMachinePrefix, machine.GetNamespace(), machine.GetName())
```
Comment (jackfrancis) [inline cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go:630]: let's hoist this string transformation into a dedicated func w/ UT

**Comment by elmiko** [comment]
thanks @jackfrancis i'll add more unit tests and write a function for the labeling.

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go (hunk 1 above)
Comment (elmiko) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go:217]: thanks, i'm trying to find some time to do more refactoring here. i think the tests could use it, and then it will make it easier to add more testing and structure for the other bits of code.

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go (hunk 3 above)
Comment (elmiko) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go:354]: added

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go (hunk 4 above)
Comment (elmiko) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go:634]: added

**Comment by elmiko** [comment]
updated with requests from comments. also fixed an error with the unit tests.

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go [hunk 5]
```diff
@@ -610,6 +627,13 @@ func (c *machineController) findScalableResourceProviderIDs(scalableResource *un
...
```
Comment (jackfrancis) [inline cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go:634]: I'd love to see this entire string concatenation behind a UT-tested func, and then a UT scenario where we invoke the func w/ the 3 inputs, and then test that we always get a true response back from `isDeletingMachineProviderID` when we pass in the return from this new func.

Comment (elmiko) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go:634]: i put the function and unit tests there, i just forgot to plug it in. i was having a weird unit test issue.

Comment (elmiko) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go]: added 2 more test cases, and fixed the commented out line here.

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go [hunk 6]
```diff
@@ -203,11 +203,28 @@ func (ng *nodegroup) DecreaseTargetSize(delta int) error {
...
+			actualNodes += 1
+		}
+	}
+
+	if size+delta < actualNodes {
+		return fmt.Errorf("node group %s: attempt to delete existing nodes currentReplicas:%d delta:%d existingNodes: %d",
+			ng.scalableResource.Name(), size, delta, actualNodes)
 	}
 
+	klog.V(4).Infof("%s: DecreaseTargetSize: scaling down: currentReplicas: %d, delta: %d, existingNodes: %d", ng.scalableResource.Name(), size, delta, len(nodes))
```
Comment (theobarberbany) [inline cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go:227]: Logs <3

**Review by jackfrancis — APPROVED** [review]
/lgtm
