### PR TITLE
set cluster_autoscaler_max_nodes_count dynamically

### LINKED ISSUE #4703: cluster_autoscaler_max_nodes_count metric has always value of 0
**Which component are you using?**:
cluster-autoscaler

**What version of the component are you using?**:
Component version: 1.20.1

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version                                                                                                                                                                                 
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-eks-f17b81", GitCommit:"f17b810c9e5a82200d28b6210b458497ddfcf31b", GitTreeState:"clean", BuildDate:"2021-10-15T21:46:21Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

</pre></details>

**What environment is this in?**:
AWS EKS

**What did you expect to happen?**:
I would expect that the metric value will be equal to the maximum nodes count in all autoscaling groups

**What happened instead?**:
the value is 0

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

The setup is using autodiscovery

### LINKED ISSUE #5305: cluster_autoscaler_max_nodes_count is always equal to 0
**Which component are you using?**:

cluster-autoscaler

**What version of the component are you using?**:

Helm chart version: 9.21.0
Application version: 1.23.0

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.15-eks-fb459a0", GitCommit:"be82fa628e60d024275efaa239bfe53a9119c2d9", GitTreeState:"clean", BuildDate:"2022-10-24T20:33:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**:

AWS EKS

**What did you expect to happen?**:

When I use the `cluster_autoscaler_max_nodes_count` metric, it should display the number of max nodes in each autoscaling group.

**What happened instead?**:

The value is always 0 displayed once even if i have multiple autoscaling groups.

### PR DESCRIPTION
**Pull request by yasinlachiny**
Signed-off-by: yasin.lachiny <yasin.lachiny@gmail.com>

#### Which component this PR applies to?

cluster-autoscaler

#### What type of PR is this?

bug

#### What this PR does / why we need it:
This PR will solve [#4703](https://github.com/kubernetes/autoscaler/issues/4703) ,  [#5250](https://github.com/kubernetes/autoscaler/issues/5250) , and  [#5305](https://github.com/kubernetes/autoscaler/issues/5305)
`cluster_autoscaler_max_nodes_count` is an env we can set it manually but we can calculate it dynamically by looping through all node groups and counting the `MaxSize` of each node group

#### Which issue(s) this PR fixes:

Fixes [#4703](https://github.com/kubernetes/autoscaler/issues/4703)
Fixes  [#5305](https://github.com/kubernetes/autoscaler/issues/5305)
Fixes [#5250](https://github.com/kubernetes/autoscaler/issues/5250)
#### Does this PR introduce a user-facing change?

NONE
```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by yasinlachiny** [comment]
Hi @x13n ,
Could you please look at this merge request?
I would like to create an alert based on it.

File: cluster-autoscaler/core/static_autoscaler.go [hunk 1]
```diff
@@ -313,12 +313,14 @@ func (a *StaticAutoscaler) RunOnce(currentTime time.Time) errors.AutoscalerError
...
-	// Update node groups min/max after cloud provider refresh
+	// Update node groups min/max and maximum number of nodes being set for all node groups after cloud provider refresh
+	maxNodesCount := 0
 	for _, nodeGroup := range a.AutoscalingContext.CloudProvider.NodeGroups() {
 		metrics.UpdateNodeGroupMin(nodeGroup.Id(), nodeGroup.MinSize())
 		metrics.UpdateNodeGroupMax(nodeGroup.Id(), nodeGroup.MaxSize())
+		maxNodesCount += nodeGroup.MaxSize()
 	}
-
+	metrics.UpdateMaxNodesCount(maxNodesCount)
```
Comment (x13n) [inline cluster-autoscaler/core/static_autoscaler.go:323]: Shouldn't it be `min(autoscalingOptions.MaxNodesTotal, maxNodesCount)` when `autoscalingOptions.MaxNodesTotal > 0`?

Comment (yasinlachiny) [reply cluster-autoscaler/core/static_autoscaler.go:323]: `maxNodesTotal               = flag.Int("max-nodes-total", 0, "Maximum number of nodes in all node groups. Cluster autoscaler will not grow the cluster beyond this number.")`

I think they are equal. but because `maxNodesCount` is an env someone can set it lower than the actual number for any reason.
So `min` of them is better. I'll fix it.

**Comment by yasinlachiny** [comment]
@x13n 
I updated my code based on your comment.
