### PR TITLE
cluster-autoscaler: fix Exoscale instance pool node groups ignoring configured minSize

### LINKED ISSUE #9441: [Exoscale]: Instance pools always default back to 1 min size
**Which component are you using?**:
/area cluster-autoscaler

**What version of the component are you using?**:
1.35.0

Component version: cluster-autoscaler-chart-9.56.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version 
Server Version: v1.34.4+rke2r1
</pre></details>

**What environment is this in?**:
Exoscale

**What did you expect to happen?**:
I would expect the cluster autoscaler to respect the minimum set instances on a Instance Pool. 

**What happened instead?**:
The cluster autoscaler ignores the minimum set instances and always defaults back onto 1

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy 3 static controlplane instances on Exoscale
2. Deploy a self-managed kubernetes cluster, no SKS, on Exoscale with cloud provider set to external.
3. Deploy the exoscale Cloud Controller Manager.
4. Deploy a Instance pool with a mimum set to three to be configured as worker nodes.
5. Deploy the Cluster Autoscaler with the Exoscale configuration.
6. Wait for the CA to be fully active and see that it automatically scales back to 1

**Anything else we need to know?**:
Based on my analysis on these two files:  
- [exoscale_node_group_instance_pool.go](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/exoscale/exoscale_node_group_instance_pool.go)
- [exoscale_node_group_sks_nodepool.go](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/exoscale/exoscale_node_group_instance_pool.go)

The `exoscale_node_group_sks_nodepool.go` has parameters for setting the Instance Pool size but the `exoscale_node_group_instance_pool.go` does not which is why the CA seems to default back 1 as it's hardcoded.

### PR DESCRIPTION
**Pull request by Debasish-87**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

Currently, Exoscale instance pool node groups ignore the configured minimum size and always fall back to 1. 

This happens because the instancePoolNodeGroup implementation does not carry over the minSize/maxSize from NodeGroupSpec, unlike the SKS nodepool implementation.

This PR fixes that by:
- Adding minSize and maxSize fields to instancePoolNodeGroup
- Passing the correct values from NodeGroupSpec
- Making the behavior consistent with SKS nodepools

After this change, the Cluster Autoscaler correctly respects the configured minimum size for instance pools.

#### Which issue(s) this PR fixes:
Fixes #9441

#### Special notes for your reviewer:

This brings instance pool behavior in line with the existing SKS implementation. Tests were updated accordingly and are passing for the Exoscale provider.

#### Does this PR introduce a user-facing change?
```release-note
Fixed an issue where Exoscale instance pool node groups ignored the configured minimum size and defaulted to 1.
```

### CODE REVIEW

**Comment by jackfrancis** [comment]
@quentinalbertone @thomasstxyz @francoismeulenberg can you PTAL?

File: cluster-autoscaler/cloudprovider/exoscale/exoscale_node_group_instance_pool.go [hunk 1]
```diff
@@ -52,7 +58,7 @@ func (n *instancePoolNodeGroup) MaxSize() int {
 
 // MinSize returns minimum size of the node group.
 func (n *instancePoolNodeGroup) MinSize() int {
-	return 1
+	return n.minSize
```
Comment (jackfrancis) [inline cluster-autoscaler/cloudprovider/exoscale/exoscale_node_group_instance_pool.go:68]: Should we add any checks here and fall back to 1?

**Comment by Debasish-87** [comment]
Good point.

Added a fallback to 1 when minSize is not set or invalid, to preserve previous behavior and ensure safe defaults.

File: cluster-autoscaler/cloudprovider/exoscale/exoscale_node_group_instance_pool.go [hunk 2]
```diff
@@ -52,7 +58,12 @@ func (n *instancePoolNodeGroup) MaxSize() int {
 
 // MinSize returns minimum size of the node group.
 func (n *instancePoolNodeGroup) MinSize() int {
-	return 1
+
+	if n.minSize <= 0 {
```
Comment (jackfrancis) [inline cluster-autoscaler/cloudprovider/exoscale/exoscale_node_group_instance_pool.go:64]: Do we want to add a comment that if scale from zero support is ever added we'll need to change this to `< 0` ?

**Comment by Debasish-87** [comment]
Good point.

Added a comment clarifying that minSize is currently expected to be >= 1, and that this should be updated if scale-from-zero support is introduced.

**Review by jackfrancis — APPROVED** [review]
/lgtm

Let's see if any other folks contributing to exoscale provider would like to weigh in

**Comment by Debasish-87** [comment]
Hi @jackfrancis,

I hope you're doing well.

I'm currently applying for Kubernetes GitHub organization membership, and since we worked together on this PR, I wanted to ask if you'd be willing to sponsor my application. If you feel our collaboration has been sufficient to meet the sponsorship requirements, I'd really appreciate your support.

Thank you!
