### PR TITLE
Correctly wrap the ErrNodeInvalidOwner error

### LINKED ISSUE #8461: VPA updater excessive logs - Failed to get parent controller for [static] pods
**Which component are you using?**:
vertical-pod-autoscaler

**What version of the component are you using?**:
Component version: VPA v1.4.1 with [cowboysysop chart v11.0.0](https://github.com/cowboysysop/charts/tree/master/charts/vertical-pod-autoscaler) 

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.32.1
Kustomize Version: v5.5.0
Server Version: v1.31.2

</pre></details>

**What environment is this in?**:
Self-hosted Kubernetes cluster on AWS infrastructure (not EKS managed).

**What did you expect to happen?**:
According to [PR #7632](https://github.com/kubernetes/autoscaler/pull/7632), the fix should have eliminated the excessive error logging for static pods with `ownerRef: Node` by properly handling the `NodeInvalidOwnerError`. The error messages should no longer appear or should be handled gracefully.

**What happened instead?**:
The VPA updater continues to log ERROR-level messages about static pods with `ownerRef: Node` even after the fix was supposedly incorporated into VPA 1.4.1. The same error pattern continues to appear for a number of pods in `kube-system` approximately once per minute:
```
E0819 16:46:20.913909       1 api.go:146] "Failed to get parent controller for pod" err="Unhandled targetRef v1 / Node / i-<node-id>.<region>.compute.internal, last error node is not a valid owner" pod="kube-system/kube-scheduler-i-<node-id>.<region>.compute.internal"
```

**How to reproduce it (as minimally and precisely as possible)**:
_Note: Reproducible in minikube, appears to be non environment-specific_

```bash
# Install VPA 1.4.1
helm repo add cowboysysop https://cowboysysop.github.io/charts/
helm install vpa cowboysysop/vertical-pod-autoscaler --version 11.0.0 

kubectl wait --for=condition=ready pod -l app.kubernetes.io/component=updater --timeout=300s

# Create test deployment and VPA
kubectl create deployment nginx --image=nginx:alpine
kubectl apply -f test-vpa.yaml

# Monitor logs for static pod errors (appear within 1-2 minutes)
kubectl logs deployment/vpa-vertical-pod-autoscaler-updater -f | grep "Failed to get parent controller"
```

**test-vpa.yaml:**
```yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: nginx-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: nginx
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        cpu: 100m
        memory: 50Mi
      maxAllowed:
        cpu: 1
        memory: 500Mi
      controlledValues: RequestsAndLimits
```

**Anything else we need to know?**:

- **Issue frequency:** Errors occur approximately once per minute
- **Affected components:** VPA updater (**admission controller appears unaffected**)
- **Static pods affected:** kube-apiserver, kube-scheduler, kube-controller-manager, aws-iam-authenticator
- **Log level:** Decreasing the log level did not reduce the error frequency
- **Original issue:** [#7378](https://github.com/kubernetes/autoscaler/issues/7378)
- **Previous fix:** [PR #7632](https://github.com/kubernetes/autoscaler/pull/7632) was supposed to fix this issue

### PR DESCRIPTION
**Pull request by adrianmoisey**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This suppresses the errors similar to this:
```
api.go:175] "Failed to get parent controller for pod" err="unhandled targetRef v1 / Node / kind-control-plane, last error node is not a valid owner" pod="kube-system/kube-apiserver-kind-control-plane"
```

This was mostly fixed in https://github.com/kubernetes/autoscaler/pull/7632, but the error wrapping wasn't done correctly.
This PR fixes that error wrapping.

#### Which issue(s) this PR fixes:

Fixes #8461

#### Does this PR introduce a user-facing change?

```release-note
vpa-updater and vpa-admission-controller no longer excessively log fail to get pod controller: (...) last error node is not a valid owner
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: vertical-pod-autoscaler/pkg/target/controller_fetcher/controller_fetcher.go [hunk 1]
```diff
@@ -210,7 +210,7 @@ func (f *controllerFetcher) getParentOfController(ctx context.Context, controlle
 		return nil, nil
 	}
 	if err != nil {
-		return nil, fmt.Errorf("unhandled targetRef %s / %s / %s, last error %v",
+		return nil, fmt.Errorf("unhandled targetRef %s / %s / %s, last error %w",
```
Comment (adrianmoisey) [inline vertical-pod-autoscaler/pkg/target/controller_fetcher/controller_fetcher.go:213]: https://pkg.go.dev/errors#pkg-overview

**Review by omerap12 — APPROVED** [review]
Thanks!
/lgtm
/approve
