### PR TITLE
fix: CA on fargate causing log flood

### LINKED ISSUE #5842: AWS provider warning Failed to check cloud provider has instance for fargate is flooding the log
cluster-autoscaler

**What version of the component are you using?**:

v1.27.2

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

```
clientVersion:
  buildDate: "2023-05-17T14:14:46Z"
  compiler: gc
  gitCommit: 890a139214b4de1f01543d15003b5bda71aae9c7
  gitTreeState: clean
  gitVersion: v1.26.5
  goVersion: go1.19.9
  major: "1"
  minor: "26"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2023-04-14T20:40:28Z"
  compiler: gc
  gitCommit: abfec7d7e55d56346a5259c9379dea9f56ba2926
  gitTreeState: clean
  gitVersion: v1.27.1-eks-2f008fe
  goVersion: go1.20.3
  major: "1"
  minor: 27+
  platform: linux/amd64
```

</pre></details>

**What environment is this in?**:

AWS

cluster-autoscaler would skip checking Fargate node.

**What happened instead?**:

```
W0607 11:20:17.160735       1 clusterstate.go:1016] Failed to check cloud provider has instance for fargate-ip-<redacted>.<redacted>.compute.internal: node is not present in aws: could not find instance {aws:///ap-southeast-2b/efbff6af53-48dd3613780e4d1e825353558e31b868/fargate-ip-<redacted>.<redacted>.compute.internal efbff6af53-48dd3613780e4d1e825353558e31b868}
W0607 11:20:17.160766       1 clusterstate.go:1016] Failed to check cloud provider has instance for fargate-ip-<redacted>.<redacted>.compute.internal: node is not present in aws: could not find instance {aws:///ap-southeast-2b/efbff6af53-22db57863d5a40bb8a918a165403ddef/fargate-ip-<redacted>.<redacted>.compute.internal efbff6af53-22db57863d5a40bb8a918a165403ddef}
```

**How to reproduce it (as minimally and precisely as possible)**:

Apply the [cluster-autoscaler-one-asg](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-one-asg.yaml) example with coredns running on Fargate will do. Doesn't matter if there's any node group or workload.

**Anything else we need to know?**:

The warning message is flooding the log and causing noise. For AWS provider it probably should not warn as it is not applicable? 

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go#L86

### PR DESCRIPTION
**Pull request by vadasambar**
- happens when CA tries to check if the unmanaged fargate node is a part of ASG (it isn't)
- and keeps on logging error
Signed-off-by: vadasambar <surajrbanakar@gmail.com>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Fixes  #5842 (and adds tests)

* Scenario: EKS cluster running on fargate but uses CA to scale some non-fargate nodegroups
* Problem: CA reads all K8s nodes including fargate ones and checks if the instance is present in AWS (by calling [HasInstance](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/aws_cloud_provider.go#L131)). This leads to error and causes log flooding (fargate is not a part of any ASG).

#### Which issue(s) this PR fixes:

Fixes  #5842

#### Does this PR introduce a user-facing change?

```release-note
Fixed: CA tries to check if unmanaged fargate node exists in AWS and keeps on logging error message
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go [hunk 1]
```diff
@@ -55,16 +56,21 @@ func newTestAwsManagerWithMockServices(mockAutoScaling autoScalingI, mockEC2 ec2
 			autoscalingOptions:    make(map[AwsRef]map[string]string),
 		},
 	}
+
+	if instanceStatus != nil {
```
Comment (vadasambar) [inline cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go:60]: To pass custom `instanceStatus` so that it is easy to test `HasInstance()`

File: cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go [hunk 2]
```diff
@@ -604,3 +610,64 @@ func TestCleanup(t *testing.T) {
...
+	assert.Equal(t, cloudprovider.ErrNotImplemented, err)
+	assert.True(t, present)
+
+	// Case 3: correct node - not present in AWS
+	node3 := &apiv1.Node{
+		ObjectMeta: metav1.ObjectMeta{
+			Name: "node-XXX",
+		},
+		Spec: apiv1.NodeSpec{
+			ProviderID: "aws:///us-east-1a/test-instance-id-2",
```
Comment (vadasambar) [inline cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go:666]: This node has a provider ID which is not present in the asg cache.

**Comment by tri-bao** [comment]
May I know which version contains this fix? I've just installed version 1.27.2 on an EKS cluster containing Fargate workload and getting a lot of such warning, the more fargate nodes the more warning messages printed.

The version 1.27.3 was out but the latest helm chart at the time of this writing (9.29.1) is still using version 1.27.2

**Comment by vadasambar** [comment]
@tri-bao sorry for the delay. 

> May I know which version contains this fix?

The fix is in `master` right now. It will be there in the new release of cluster-autoscaler. 

If you want, I can create cherry-pick PR for 1.27.
