### PR TITLE
Fix pricing endpoint in AWS China Region

### LINKED ISSUE #3076: Cluster Autoscaler 1.15.6 AWS has problem with start in region cn-northwest-1
After update version to 1.15.6 on clusters in China region cn-northwest-1 (is present change **Load AWS EC2 Instance Types dynamically**)
I've got error:

> W0421 13:07:06.686353       1 aws_util.go:86] Error unmarshalling https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/cn-northwest-1/index.json, skip...
> F0421 13:07:06.686381       1 aws_cloud_provider.go:366] Failed to generate AWS EC2 Instance Types: unable to load EC2 Instance Type list

But after set parameter **aws-use-static-instance-list** in _true_ CA start in normal state

### PR DESCRIPTION
**Pull request by qqshfox**
Fixes #3076, #3276

### CODE REVIEW

**Review by jordan-huangwei — APPROVED** [review]
very good

**Comment by Jeffwan** [comment]
Add pricing list api here.
https://docs.amazonaws.cn/en_us/aws/latest/userguide/billing-and-payment.html#price-list

Thanks for the contribution

```

    "AmazonEC2" : {
      "offerCode" : "AmazonEC2",
      "versionIndexUrl" : "/offers/v1.0/cn/AmazonEC2/index.json",
      "currentVersionUrl" : "/offers/v1.0/cn/AmazonEC2/current/index.json",
      "currentRegionIndexUrl" : "/offers/v1.0/cn/AmazonEC2/current/region_index.json"
    },

```

File: cluster-autoscaler/cloudprovider/aws/aws_util.go [hunk 1]
```diff
@@ -31,9 +31,10 @@ import (
 )
 
 var (
-	ec2MetaDataServiceUrl        = "http://169.254.169.254/latest/dynamic/instance-identity/document"
-	ec2PricingServiceUrlTemplate = "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/%s/index.json"
-	staticListLastUpdateTime     = "2019-10-14"
+	ec2MetaDataServiceUrl          = "http://169.254.169.254/latest/dynamic/instance-identity/document"
+	ec2PricingServiceUrlTemplate   = "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/%s/index.json"
+	ec2PricingServiceUrlTemplateCN = "https://pricing.cn-north-1.amazonaws.com.cn/offers/v1.0/cn/AmazonEC2/current/%s/index.json"
```
Comment (Jeffwan) [inline cluster-autoscaler/cloudprovider/aws/aws_util.go:36]: Minor: There're multiple partitions like AWS, AWS-cn, AWS-gov.  It would be great to have all of them

File: cluster-autoscaler/cloudprovider/aws/aws_util.go [hunk 2]
```diff
@@ -53,6 +54,13 @@ type productAttributes struct {
 
 // GenerateEC2InstanceTypes returns a map of ec2 resources
 func GenerateEC2InstanceTypes(region string) (map[string]*InstanceType, error) {
+	var pricingUrlTemplate string
+	if strings.HasPrefix(region, "cn-") {
```
Comment (Jeffwan) [inline cluster-autoscaler/cloudprovider/aws/aws_util.go:58]: minor: I am ok with this now. It would be better to use AWS SDK to check partition

**Review by Jeffwan — APPROVED** [review]

**Comment by zxh326** [comment]
Can we cherry-pick this change to `v1.17.x` `v.1.18.x` version?

@Jeffwan

**Comment by Jeffwan** [comment]
@zxh326 Why not using cherry-picks?

**Comment by zxh326** [comment]
> @zxh326 Why not to use cherry-picks scripts?

I don't know how to use and didn't find this script

**Comment by yongzhang** [comment]
is it available in 1.18? I still have this issue in 1.18:
```
W1211 05:13:25.624702       1 aws_util.go:71] Error fetching https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/cn-northwest-1/index.json skipping...
F1211 05:13:25.624754       1 aws_cloud_provider.go:358] Failed to generate AWS EC2 Instance Types: unable to load EC2 Instance Type list
```

**Comment by qqshfox** [comment]
@yongzhang  Looks like the backport to 1.18 hasn't been released yet. https://github.com/kubernetes/autoscaler/compare/cluster-autoscaler-1.18.3...cluster-autoscaler-release-1.18

**Comment by yongzhang** [comment]
> @yongzhang Looks like the backport to 1.18 hasn't been released yet. [cluster-autoscaler-1.18.3...cluster-autoscaler-release-1.18](https://github.com/kubernetes/autoscaler/compare/cluster-autoscaler-1.18.3...cluster-autoscaler-release-1.18)

Fine, so looks like I have to build the binary from branch `cluster-autoscaler-release-1.18` for now.
