### PR TITLE
Fix multiple run of informers created in fetcher.go

### LINKED ISSUE #6156: [VPA] sharedIndexInformer started twice
**Which component are you using?**:

vertical-pod-autoscaler

**What version of the component are you using?**:

Component version: 0.14.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What environment is this in?**:

AWS EKS / k3d local cluster

**What did you expect to happen?**:

sharedIndexInformer not started more than once

**What happened instead?**:

[Seven sharedIndexInformer](https://github.com/kubernetes/autoscaler/blob/cc3283c917c58666c4747f096e43cd23874730ea/vertical-pod-autoscaler/pkg/target/fetcher.go#L83-L89) are started twice and following log are output seven times.

`The sharedIndexInformer has started, run more than once is not allowed`

**How to reproduce it (as minimally and precisely as possible)**:

just start vpa-admission-controller

**Anything else we need to know?**:

It is similar to: https://github.com/kubernetes-sigs/metrics-server/issues/1002

### PR DESCRIPTION
**Pull request by mikutas**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Suppress warn logs `The sharedIndexInformer has started, run more than once is not allowed` appear at every admission-controller startup

#### Which issue(s) this PR fixes:

Fixes #6156

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: vertical-pod-autoscaler/pkg/utils/limitrange/limit_range_calculator.go [hunk 1]
```diff
@@ -55,12 +56,12 @@ func NewLimitsRangeCalculator(f informers.SharedInformerFactory) (*limitsChecker
...
-	for _, ok := range f.WaitForCacheSync(stopCh) {
-		if !ok {
-			if !f.Core().V1().LimitRanges().Informer().HasSynced() {
-				return nil, fmt.Errorf("informer did not sync")
-			}
+	informer := f.Core().V1().LimitRanges().Informer()
+	go informer.Run(stopCh)
+	ok := cache.WaitForCacheSync(stopCh, informer.HasSynced)
+	if !ok {
+		if !f.Core().V1().LimitRanges().Informer().HasSynced() {
```
Comment (laoj2) [inline vertical-pod-autoscaler/pkg/utils/limitrange/limit_range_calculator.go:63]: do we really need this inner `if`? It seems to be redundant with `cache.WaitForCacheSync(stopCh, informer.HasSynced)`

**Review by laoj2 — APPROVED** [review]

**Review by kwiesmueller — APPROVED** [review]
/lgtm

**Comment by devthejo** [comment]
Same error on version 1.2.1, here is the manifest:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-recommender
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vpa-recommender
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vpa-recommender
    spec:
      containers:
      - args:
        - --target-cpu-percentile=0.95
        - --recommendation-upper-bound-cpu-percentile=1.0
        image: registry.k8s.io/autoscaling/vpa-recommender:1.2.1
        imagePullPolicy: Always
        name: recommender
        ports:
        - containerPort: 8942
          name: prometheus
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 500Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccount: vpa-recommender
      serviceAccountName: vpa-recommender
      terminationGracePeriodSeconds: 30
```
