### PR TITLE
fix(clusterapi): use kind-aware version discovery for infra references

### LINKED ISSUE #9439: Incorrect version for infrastructureRef assumed based on apiGroup
**Which component are you using?**:

/area cluster-autoscaler

**What version of the component are you using?**:

`v1.35.0` 

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.34.3
Kustomize Version: v5.7.1
Server Version: v1.35.2
</pre></details>

**What environment is this in?**:

Nutanix

**What did you expect to happen?**:

CA should continue to work with CAPI `v1.12.4` and infra providers that do not have `v1beta2` APIs.

**What happened instead?**:

The CA never initializes and errors with:
```
E0331 21:29:19.400182       1 reflector.go:204] "Failed to watch" err="failed to list infrastructure.cluster.x-k8s.io/v1beta2, Resource=nutanixmachinetemplates: the server could not find the requested resource" logger="UnhandledError" reflector="pkg/mod/k8s.io/client-go@v0.35.0/tools/cache/reflector.go:289" type="infrastructure.cluster.x-k8s.io/v1beta2, Resource=nutanixmachinetemplates"
```
Notice `infrastructure.cluster.x-k8s.io/v1beta2`, which is incorrect
```
$ k get crds nutanixmachinetemplates.infrastructure.cluster.x-k8s.io -o yaml
...
  storedVersions:
  - v1beta1
```

**How to reproduce it (as minimally and precisely as possible)**:

Deploy a Cluster with https://github.com/nutanix-cloud-native/cluster-api-provider-nutanix

**Anything else we need to know?**:

I was able to workaround this by setting
```
env:
  - name: CAPI_VERSION
    value: v1beta1
```

This looks related to https://github.com/kubernetes/autoscaler/pull/8410. 
With `v1beta2` the MD spec looks like,
```
      spec:
        bootstrap:
          configRef:
            apiGroup: bootstrap.cluster.x-k8s.io
            kind: KubeadmConfigTemplate
            name: dk-nutanix-ca-md-0-h8c25
        clusterName: dk-nutanix-ca
        infrastructureRef:
          apiGroup: infrastructure.cluster.x-k8s.io
          kind: NutanixMachineTemplate
          name: dk-nutanix-ca-md-0-h7kzv
```
With `v1beta1` the version is correctly read from the ref itself.
```
$ kubectl get machinedeployments.v1beta1.cluster.x-k8s.io  -o yaml
...
      spec:
        bootstrap:
          configRef:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
            kind: KubeadmConfigTemplate
            name: dk-nutanix-ca-md-0-h8c25
            namespace: default
        clusterName: dk-nutanix-ca
        infrastructureRef:
          apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
          kind: NutanixMachineTemplate
          name: dk-nutanix-ca-md-0-h7kzv
          namespace: default
```

From [InfraMachine contract](https://cluster-api.sigs.k8s.io/developer/providers/contracts/infra-machine)
>Note: The version of your provider does not need to be in sync with the version of core Cluster API resources. Instead, prefer choosing a version that matches the stability of the provider API and its backward compatibility guarantees.

### PR DESCRIPTION
**Pull request by LiangquanLi930**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Add getKindPreferredVersion to resolve the API version that actually serves a given infrastructure Kind, replacing the group-level getAPIGroupPreferredVersion. This fixes incorrect GVK construction when multiple versions exist in a CAPI infra provider group but not all versions serve every Kind (e.g. Nutanix vs AWS machine templates).

Includes unit tests for getKindPreferredVersion and a test framework fix to populate Kind in the fake discovery client.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/autoscaler/issues/9439

#### Does this PR introduce a user-facing change?

```release-note
Fixed CAPI provider failing to initialize when using CAPI v1.11+ with infrastructure providers that only serve v1beta1 APIs (e.g. Azure CAPZ).
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by LiangquanLi930** [comment]
@enxebre @elmiko  When you have time, PTAL, Thanks!

**Comment by yashrajshuklaaa** [comment]
Thanks for putting this together! The approach of resolving at the Kind level rather than just the API group makes sense 
a group can serve multiple versions and not every version exposes every Kind, so group-level resolution was always going to be fragile here

A few thoughts while reading through:

**On `getKindPreferredVersion`**  would it be worth adding a short comment above the function explaining the v1beta2 context? Something like:
> in v1beta2, `infrastructureRef` only carries `apiGroup` and `kind`, not a full `apiVersion`  so we need to resolve the version by looking up which server resource actually serves this Kind.

Future readers won't have issue #9439 in their head.

**On the test fix for the fake discovery client** (good catch) 
Without `Kind` populated in the fake, this whole class of bug would stay invisible in unit tests going forward

**On the original reporter's case**  the Nutanix error was:
infrastructure.cluster.x-k8s.io/v1beta2, Resource=nutanixmachinetemplates
which is exactly what this fixes. The Kind-aware lookup will correctly land on `v1beta1` since that's what CAPN actually serves. Also try to confirm this in a test environment

**Comment by LiangquanLi930** [comment]
> On getKindPreferredVersion would it be worth adding a short comment above the function explaining the v1beta2 context? Something like:
> 
> > in v1beta2, infrastructureRef only carries apiGroup and kind, not a full apiVersion so we need to resolve the version by looking up which server resource actually serves this Kind.

updated

> On the original reporter's case the Nutanix error was:
infrastructure.cluster.x-k8s.io/v1beta2, Resource=nutanixmachinetemplates
which is exactly what this fixes. The Kind-aware lookup will correctly land on v1beta1 since that's what CAPN actually serves. Also try to confirm this in a test environment

@yashrajshuklaaa The unit test TestGetKindPreferredVersion directly simulates this exact scenario — group preferred version is v1beta2 but the Kind only exists in v1beta1. Happy to test in a real environment if you'd like, but I think the unit coverage is sufficient here.

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go [hunk 1]
```diff
@@ -611,6 +611,36 @@ func getAPIGroupPreferredVersion(client discovery.DiscoveryInterface, APIGroup s
...
+	groupList, err := client.ServerGroups()
+	if err != nil {
+		return "", fmt.Errorf("failed to get ServerGroups: %v", err)
+	}
+
+	for _, group := range groupList.Groups {
+		if group.Name != apiGroup {
+			continue
+		}
+		for _, v := range group.Versions {
```
Comment (elmiko) [inline cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go:627]: do we know what order these versions will be returned in?

i'm just curious if there is a case where we get an older version or something.

**Review by elmiko — COMMENTED** [review]
thanks @LiangquanLi930 , i just have a quick question.

also, could you update the description to add `Fixes #9439`

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go (hunk 1 above)
Comment (LiangquanLi930) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go:627]: group.Versions follows CRD .spec.versions definition order, not PreferredVersion. But for the Kinds we're fixing (e.g. AzureMachineTemplate), they only exist in v1beta1, so the order doesn't affect correctness here. 

Should we also update the logic to try `group.PreferredVersion` first before iterating?

**Comment by LiangquanLi930** [comment]
> could you update the description to add Fixes #9439

updated, Thanks!

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go (hunk 1 above)
Comment (elmiko) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go:627]: ack, thanks.

> Should we also update the logic to try group.PreferredVersion first before iterating?

good question, i don't think we need to but i'm trying to think through scenarios where this might fail.

Comment (elmiko) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go:627]: i'm having trouble thinking of a case where we would need it. let's move forward and see what breaks XD
