### PR TITLE
Fix VPA admission controller server test

### LINKED ISSUE #2886: Fix flaky admission controller unit test
I've seen multiple instances of this on unrelated PRs: 

?   	k8s.io/autoscaler/vertical-pod-autoscaler/common	[no test files]
?   	k8s.io/autoscaler/vertical-pod-autoscaler/pkg/admission-controller	[no test files]
--- FAIL: TestGetPatchesForResourceRequest_TwoReplacementResources (0.00s)
    server_test.go:396: 
        	Error Trace:	server_test.go:396
        	Error:      	Should be true
        	Test:       	TestGetPatchesForResourceRequest_TwoReplacementResources
FAIL
FAIL	k8s.io/autoscaler/vertical-pod-autoscaler/pkg/admission-controller/logic	0.097s

### PR DESCRIPTION
**Pull request by jbartosik**
It seems that order of CPU and unobtanium is somewhat random, which was
causing flaky tests:

fixes #2886

### CODE REVIEW

**Comment by krzysied** [comment]
Additional context: This problem is caused by https://github.com/kubernetes/autoscaler/blob/4317838e1971d7c7cda6649f96c68c5a1720f160/vertical-pod-autoscaler/pkg/admission-controller/logic/server.go#L168. Golang assumes that map can be iterate in any order. This makes our test result non-deterministic.

File: vertical-pod-autoscaler/pkg/admission-controller/logic/server_test.go [hunk 1]
```diff
@@ -407,7 +407,9 @@ func TestGetPatchesForResourceRequest_TwoReplacementResources(t *testing.T) {
 		assertPatchOneOf(t, patches[1], []patchRecord{cpuUpdate, unobtaniumUpdate})
 		assert.False(t, eqPatch(patches[0], patches[1]))
 		assertEqPatch(t, patches[2], getAddEmptyAnnotationsPatch())
-		assertEqPatch(t, patches[3], addAnnotationRequest([][]string{{cpu, unobtanium}}, request))
+		cpuFirstUnobtaniumSecond := addAnnotationRequest([][]string{{cpu, unobtanium}}, request)
```
Comment (krzysied) [inline vertical-pod-autoscaler/pkg/admission-controller/logic/server_test.go]: This solution requires all n! permutation sets of n resources to be created. However in out tests there shouldn't be more than 2 resources per test so this shouldn't be a problem, right?

Comment (jbartosik) [reply vertical-pod-autoscaler/pkg/admission-controller/logic/server_test.go]: Yes, I went with this because there are only 2 values to rearrange here. If we ever have 3 or more values appearing in undeterministic order then it will probably be worth to implement matcher that's not sensitive to their order.

**Comment by krzysied** [comment]
/lgtm
/approve

Thanks!
