### PR TITLE
Process apiGroup in capi provider

### LINKED ISSUE #8330: CA clusterapi provider scale from zero does not work properly with v1beta2 API
**Which component are you using?**:

/area cluster-autoscaler

**What version of the component are you using?**: 

Component version: cluster-autoscaler-1.33.0

**What k8s version are you using (`kubectl version`)?**: 1.33

**What environment is this in?**: 

clusterapi, with the cluster-api vsphere provider.

**What did you expect to happen?**:

scale from zero should work.

**What happened instead?**:

it did not scale from zero. no new nodes were made.

**How to reproduce it (as minimally and precisely as possible)**:

configure cluster-api provider for CA, then create a MachineDeployment with 0 replicas. add a workload that targets the nodes created by the MachineDeployment.

**Anything else we need to know?**:

this is happening because of a difference between how a Machine's `infrastructureRef` field has changed from v1beta1 to v1beta2.

v1beta1 definition uses the core ObjectRef, see https://github.com/kubernetes-sigs/cluster-api/blob/main/api/core/v1beta1/machine_types.go#L396

v1beta2 definition uses an internal type for the reference, see https://github.com/kubernetes-sigs/cluster-api/blob/main/api/core/v1beta2/common_types.go#L361-L387

whereas the current code in CA does not account for this difference, see https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go#L378

### PR DESCRIPTION
**Pull request by wjunott**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
With capi v1beta2, a MachineDeployment or MachineSet's infrastructureRef field has changed from [ObjectReference](https://github.com/kubernetes-sigs/cluster-api/blob/main/api/core/v1beta1/machine_types.go#L396) to [ContractVersionedObjectReference](https://github.com/kubernetes-sigs/cluster-api/blob/main/api/core/v1beta2/common_types.go#L361-L387). We need to process the difference between apiVersion and apiGroup.
#### Which issue(s) this PR fixes:

Fixes #8330

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go [hunk 1]
```diff
@@ -416,9 +416,9 @@ func createTestConfigs(specs ...testSpec) []*testConfig {
 						"template": map[string]interface{}{
 							"spec": map[string]interface{}{
 								"infrastructureRef": map[string]interface{}{
-									"apiVersion": "infrastructure.cluster.x-k8s.io/v1beta1",
-									"kind":       machineTemplateKind,
-									"name":       "TestMachineTemplate",
+									"apiGroup": "infrastructure.cluster.x-k8s.io",
```
Comment (sbueringer) [inline cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go:419]: We probably want test coverage for both cases as autoscaler should work with v1beta1 (apiVersion) and v1beta2 (apiGroup)

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go [hunk 2]
```diff
@@ -380,17 +380,33 @@ func (r unstructuredScalableResource) readInfrastructureReferenceResource() (*un
...
+		if !ok {
+			klog.V(4).Info("Missing apiVersion")
+			return nil, errors.New("Missing apiVersion")
+		}
 	}
+
 	kind, ok := infraref["kind"]
 	if !ok {
-		return nil, nil
+		klog.V(4).Info("Missing kind")
```
Comment (sbueringer) [inline cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go]: Not sure if we should log & return the error. Usually one should be enough, but I'm not that familiar with the autoscaler

(same in other cases around here)

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go [hunk 3]
```diff
@@ -380,17 +380,33 @@ func (r unstructuredScalableResource) readInfrastructureReferenceResource() (*un
...
+		return nil, errors.New("Missing kind")
```
Comment (sbueringer) [inline cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go]:
```suggestion
		return nil, errors.New("missing kind")
```
Same below (and above)

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go [hunk 4]
```diff
@@ -380,17 +380,33 @@ func (r unstructuredScalableResource) readInfrastructureReferenceResource() (*un
...
 	}
 
-	apiversion, ok := infraref["apiVersion"]
-	if !ok {
-		return nil, nil
+	var apiversion string
+
+	apiGroup, ok := infraref["apiGroup"]
+	if ok {
+		if apiversion, err = getAPIGroupPreferredVersion(r.controller.managementDiscoveryClient, apiGroup); err != nil {
```
Comment (sbueringer) [inline cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go:390]: If I see correctly this is doing a live call against the apiserver. I'm wondering if 1 live call for every call of readInfrastructureReferenceResource is too much

Should we use a cache with a TTL to cache the apiGroup => version mapping? (ttl: 1m or 10m?)
(we can use client-go/tools/cache.NewTTLStore for that)

**Comment by sbueringer** [comment]
@wjunott Thx!

/assign @elmiko 

Once we settled on the implementation I can do a test with Cluster API if it works as expected

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go (hunk 1 above)
Comment (wjunott) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go:419]: The machineset uses apiVersion in the InfrastructureRef, so we can cover both cases. @elmiko how about I replace all alpha3 version to beta2 in the test cases? as alpha3 is a bit out-of-date.

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go (hunk 2 above)
Comment (wjunott) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go]: I am following the current code structures as one dependency of "CanScaleFromZero()" will return false directly.

Comment (sbueringer) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go]: Makes sense to me

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go (hunk 4 above)
Comment (wjunott) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go:390]: Good point. Initially, I think this api is invoked only during scale up/down. @elmiko any advice where to put the cache?

Comment (sbueringer) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go:390]: If it's okay to always do a live call here because this isn't called too often, absolutely fine for me of course (I just don't know :))

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go (hunk 1 above)
Comment (elmiko) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go:419]: > how about I replace all alpha3 version to beta2 in the test cases?

+1, makes good sense to me.

i definitely think we should make sure these tests work for both v1beta1 and v1beta2, with both MachineSets and MachineDeployments.

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go (hunk 4 above)
Comment (elmiko) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go:390]: these calls will only happen when the core autoscaler wants to construct a node template. if the autoscaler has a ready node from the node group, then it will use a node as a template instead of asking the provider to generate a new template (where this function is called).

in the worst case scenario, this function will get called once per node group per scan interval from the autoscaler, which defaults to 10 seconds. in a large cluster this could be called several time for the same template depending on how the cluster-api resources are organized.

i think it's worth investigating putting a cache in for the infrastructure templates as they probably won't change that frequently and it could save us some api calls.

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go [hunk 5]
```diff
@@ -380,17 +380,33 @@ func (r unstructuredScalableResource) readInfrastructureReferenceResource() (*un
...
+			klog.V(4).Infof("Unable to read preferred version from api group %s, error: %v", apiGroup, err)
+			return nil, err
+		}
+		apiversion = fmt.Sprintf("%s/%s", apiGroup, apiversion)
+	} else {
+		// Fall back to ObjectReference in capi v1beta1
+		apiversion, ok = infraref["apiVersion"]
+		if !ok {
+			klog.V(4).Info("Missing apiVersion")
+			return nil, errors.New("Missing apiVersion")
```
Comment (elmiko) [inline cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go]: i'd like to add a little more information here to help with triage

```suggestion
            errorMsg := fmt.Sprintf("missing apiVersion for infrastructureRef of scalable resource %q", r.unstructured.GetName())
			klog.V(4).Info(errorMsg)
			return nil, errors.New(errorMsg)
```

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go (hunk 2 above)
Comment (elmiko) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go]: logging at level 4 is helpful here for debugging and triaging.

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go (hunk 3 above)
Comment (elmiko) [inline cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go]: similar to the missing apiVersion, i'd like a little more info here

```suggestion
        errorMsg := fmt.Sprintf("missing kind for infrastructureRef of scalable resource %q", r.unstructured.GetName())
		klog.V(4).Info(errorMsg)
		return nil, errors.New(errorMsg)
```

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go [hunk 6]
```diff
@@ -380,17 +380,33 @@ func (r unstructuredScalableResource) readInfrastructureReferenceResource() (*un
...
 	if !ok {
-		return nil, nil
+		klog.V(4).Info("Missing kind")
+		return nil, errors.New("Missing kind")
 	}
 	name, ok := infraref["name"]
 	if !ok {
-		return nil, nil
+		klog.V(4).Info("Missing name")
+		return nil, errors.New("Missing name")
```
Comment (elmiko) [inline cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go]: same here too

```suggestion
        errorMsg := fmt.Sprintf("missing name for infrastructureRef of scalable resource %q", r.unstructured.GetName())
		klog.V(4).Info(errorMsg)
		return nil, errors.New(errorMsg)
```

**Review by elmiko — COMMENTED** [review]
this making sense to me, i have some suggestions about the error messages and i tend to agree with @sbueringer about caching.

although, if we feel adding caching to this PR will make it too complex, i'm fine to review it in a followup.

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go (hunk 4 above)
Comment (sbueringer) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go:390]: Sounds like we don't necessarily need caching. If I see correctly the getInfrastructureResource below is also not cached? So this won't add much on top

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go (hunk 1 above)
Comment (wjunott) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go:419]: Replaced v1alpha3 with v1beta2.

**Comment by sbueringer** [comment]
@wjunott see https://github.com/kubernetes/autoscaler/pull/8410#issuecomment-3166474238

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go (hunk 5 above)
Comment (wjunott) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go]: Added more detailed information.

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go (hunk 4 above)
Comment (wjunott) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go:390]: getInfrastructureResource enables informer's cache.

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go [hunk 7]
```diff
@@ -366,7 +366,7 @@ func createTestConfigs(specs ...testSpec) []*testConfig {
 		config.machineSet = &unstructured.Unstructured{
 			Object: map[string]interface{}{
 				"kind":       machineSetKind,
-				"apiVersion": "cluster.x-k8s.io/v1alpha3",
+				"apiVersion": "cluster.x-k8s.io/v1beta2",
```
Comment (sbueringer) [inline cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go:369]: I think we have to adjust the infrastructureRef here to use the new format of v1beta2 (i.e. apiGroup instead of apiVersion)

(please also check if there are other cases below)

Comment (wjunott) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go:369]: The current test structure is not so flexible. For this case, it covers the machineset with apiVersion case, e.g. the previous behavior.

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go (hunk 5 above)
Comment (wjunott) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go]: @elmiko @sbueringer I created a commit to support cached preferred version of an apiGroup with about 24 lines' change. How about we discuss more if we still need cached version and if so I will create a new PR after this one is merged? given only scale from zero will access apiserver to get preferred version of an apiGroup.

**Comment by elmiko** [comment]
apologies, i didn't get a chance to do any reviews today. i will revisit this PR early next week.

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go (hunk 7 above)
Comment (sbueringer) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go:369]: Maybe then we should use v1beta1 here. As it is it is not a valid v1beta2 object

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go (hunk 5 above)
Comment (elmiko) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go]: i think a cache would be helpful to reduce the number of api calls that the cluster-api provider makes. i'm not sure that it is absolutely required, but it would be interesting to test it out.

under normal operation, the cluster-api provider can generate many log lines reporting client-side throttling. i would think that having a cache would help us to reduce the frequency of calls.
```
 Waited for 174.987663ms due to client-side throttling, not priority and fairness, request: <details of HTTP request>
```

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go (hunk 7 above)
Comment (elmiko) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go:369]: +1

Comment (elmiko) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go:369]: i have some thoughts about how to make these tests easier to work with, but best if we get this review done first then perhaps i can propose some cleanups.

**Review by elmiko — COMMENTED** [review]
i think this is looking good, i'd like to see if @jackfrancis might be able to give a review.

not sure the best way to address the test spec creation for the different infrastructure versions.

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go (hunk 7 above)
Comment (wjunott) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go:369]: +1 to Michael's comment. Plus v1beta2 + apiVersion in InfrastructureReference is also a valid combination in capi v1beta2.alpha.1, so we may address in a later cleanup.

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go (hunk 5 above)
Comment (wjunott) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go]: OK, I will create a new PR with cache enabled after this PR is tested and merged.

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go (hunk 7 above)
Comment (sbueringer) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go:369]: Not sure if I got it right, but v1beta2 MachineDeployments, MachineSets and MachinePools always have apiGroup. How could they have apiVersion?

Comment (elmiko) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go:369]: this line is the apiVersion for the kind that is being created, for this clause it's a MachineSet. this isn't about the infrastructure ref.

edit: misread your comment @sbueringer 

i agree with your suggestion that we use `v1beta1` here.

Comment (sbueringer) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go:369]: Just chatted with Jun. While it looks trivial to just change this apiVersion to v1beta1 here it breaks a huge amount of tests and requires refactoring

(57 tests failed, 143 tests passed when changing this to v1beta1)

So from my side it would be okay to defer the test refactoring if we feel the change in this PR is sufficiently unit tested.

But I leave this to autoscaler reviewers / maintainers of course

Comment (jackfrancis) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go:369]: I assume we're talking about test refactoring under the cloudprovider/clusterapi directory, which is in fact maintained independently from the core autoscaler. So I'll defer to @elmiko for final call on merging w/ v1beta2 change.

Overall lgtm

**Comment by elmiko** [comment]
sorry, i didn't get a chance to review today. i'm adding to my queue for tomorrow.

File: cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go (hunk 7 above)
Comment (elmiko) [reply cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go:369]: yeah, i was talking about refactoring the tests for clusterapi. one of things i'd like to do is replace the brittle test config functions with a better interface modeled around a builder/fluent pattern for creating the capi objects.

**Comment by elmiko** [comment]
i think this is looking good. i'd like to improve the tests, but that can come next.

/unhold

**Comment by sbueringer** [comment]
@elmiko let's backport?

(xref: testing this PR in CAPI here: https://github.com/kubernetes-sigs/cluster-api/pull/12643)

**Comment by sbueringer** [comment]
Also verified this fix and the previous one for scale to 0 locally with the debugger. Looks perfect.

@elmiko When is the next patch release planned?

**Comment by elmiko** [comment]
thanks @jackfrancis !

> @elmiko When is the next patch release planned?

good question, i can bring this up at the next sig meeting.

**Comment by jackfrancis** [comment]
looks like something changed in the UT foundations maybe prior to this PR change, which is missing in release branches prior to 1.33, I haven't had time to look into it yet

tl;dr we probably need to cherry-pick some other stuff into < 1.32 before this one will slot in cleanly
