### PR TITLE
Avoid returning error when annotation patch for InPlaceOrResize fails

### LINKED ISSUE #9080: In-place update falled back to eviction when it actually succeeded
**Which component are you using?**:

/area vertical-pod-autoscaler

**What version of the component are you using?**:

master

Component version:

**What k8s version are you using (`kubectl version`)?**: N/A

**What environment is this in?**:

N/A

**What did you expect to happen?**:

In the case where in-place resource patch succeeded and in-place annotation patch failed, the pod should still be updated in-place.

**What happened instead?**:

The pod was evicted.

**How to reproduce it (as minimally and precisely as possible)**:

Force in-place annotation patch to fail.

**Anything else we need to know?**:

When I did the experiment, there were 2 pods in my deployment. One pod was evicted, the other skipped the eviction due to pod disruption budget, and it never retried again to evict (note that in Recreate mode if a pod skipped eviction, it will try again later). When I describe that pod, it has an in-place update success event.

### PR DESCRIPTION
**Pull request by adrianmoisey**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This should help mitigate the issue here: https://github.com/kubernetes/autoscaler/issues/9080
(but it's still possible that this annotation patch fails 3 times, and causes the pod to be recreated)

#### Which issue(s) this PR fixes:

Fixes #9080

#### Does this PR introduce a user-facing change?

```release-note
Avoid returning error when annotation patch for InPlaceOrResize fails, that would cause Pods to get unnecessarily evicted after resize
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/cc @omerap12 @maxcao13 @jkyros

### CODE REVIEW

File: vertical-pod-autoscaler/pkg/updater/restriction/pods_inplace_restriction.go [hunk 1]
```diff
@@ -153,11 +153,23 @@ func (ip *PodsInPlaceRestrictionImpl) InPlaceUpdate(podToUpdate *apiv1.Pod, vpa
...
+			for attempt := range maxRetries {
+				res, err = ip.client.CoreV1().Pods(podToUpdate.Namespace).Patch(context.TODO(), podToUpdate.Name, k8stypes.JSONPatchType, patch, metav1.PatchOptions{})
+				if err == nil {
+					klog.V(4).InfoS("Patched pod annotations", "pod", klog.KObj(res), "patches", string(patch))
+					break
+				}
+				if attempt < maxRetries-1 {
+					time.Sleep(retryDelay * 1 << attempt)
+				}
+			}
```
Comment (omerap12) [inline vertical-pod-autoscaler/pkg/updater/restriction/pods_inplace_restriction.go]: Kubernetes already implemented this logic in https://pkg.go.dev/k8s.io/client-go/util/retry
Specifically I think we can just use https://pkg.go.dev/k8s.io/client-go/util/retry#OnError

Maybe something like:
```golang
err := retry.OnError(retry.DefaultBackoff, func(err error) bool {
    return true  // Always retry
}, func() error {
    res, err = ip.client.CoreV1().Pods(podToUpdate.Namespace).Patch(
        context.TODO(), podToUpdate.Name, k8stypes.JSONPatchType, patch, metav1.PatchOptions{})
    return err
})
```

Comment (adrianmoisey) [reply vertical-pod-autoscaler/pkg/updater/restriction/pods_inplace_restriction.go]: 🤦 
I looked for that, and only saw the "RetryOnConflict" at the bottom, and I missed the "OnError" function

Comment (adrianmoisey) [reply vertical-pod-autoscaler/pkg/updater/restriction/pods_inplace_restriction.go]: Oh, the issue is that we need a `retriable` function, meaning I need to figure out what errors are retryable or not

Comment (adrianmoisey) [reply vertical-pod-autoscaler/pkg/updater/restriction/pods_inplace_restriction.go]: I guess I can make it retry on everything, and we can tweak that later as needed.

Comment (omerap12) [reply vertical-pod-autoscaler/pkg/updater/restriction/pods_inplace_restriction.go]: Yeah, retry on everything for now is ok

File: vertical-pod-autoscaler/pkg/updater/restriction/pods_inplace_restriction.go [hunk 2]
```diff
@@ -153,7 +155,15 @@ func (ip *PodsInPlaceRestrictionImpl) InPlaceUpdate(podToUpdate *apiv1.Pod, vpa
...
+			err = retry.OnError(
+				wait.Backoff{Steps: 3, Duration: 100 * time.Millisecond},
+				func(error) bool { return true },
+				func() error {
+					res, err = ip.client.CoreV1().Pods(podToUpdate.Namespace).Patch(context.TODO(), podToUpdate.Name, k8stypes.JSONPatchType, patch, metav1.PatchOptions{})
+					return err
+				})
 			if err != nil {
 				return err
 			}
```
Comment (maxcao13) [inline vertical-pod-autoscaler/pkg/updater/restriction/pods_inplace_restriction.go:161]: I like the retry idea, but I generally think that even if the annotation patch doesn't go through, it shouldn't block whether the overall operation was a failure or not. I think maybe we should think about not returning an error, but just logging it. The annotation isn't really a big deal, I don't think it's used other than for cosmetic reasons.

But also now thinking about it, what happens if all pods for resize in one loop have to retry? That's around 300ms per pod, and I don't think that we're doing concurrent updates here right?

Comment (adrianmoisey) [reply vertical-pod-autoscaler/pkg/updater/restriction/pods_inplace_restriction.go:161]: All valid points, thanks Max.

> But also now thinking about it, what happens if all pods for resize in one loop have to retry? That's around 300ms per pod, and I don't think that we're doing concurrent updates here right?

I had thought about this, and originally came to the conclusion  that  a scenario where all annotation patcher were to fail, then all the resizes would fail first, causing the patch to not be executed. But it turns out that this situation is actually possibly,  if someone reduces the RBAC to only `pods/resize` only, see:

https://github.com/kubernetes/autoscaler/blob/ce55a882414e127c49d3ceb6b0f1790062950fce/vertical-pod-autoscaler/deploy/vpa-rbac.yaml#L133-L135

> I think maybe we should think about not returning an error, but just logging it.

Agree, I'll remove the retry and add a log entry

Comment (omerap12) [reply vertical-pod-autoscaler/pkg/updater/restriction/pods_inplace_restriction.go:161]: Sounds good. thanks Max!

**Review by omerap12 — APPROVED** [review]
Thanks!
/lgtm

should we also backport this?

**Comment by adrianmoisey** [comment]
> should we also backport this?

Good idea! 

/cherry-pick vpa-release-1.5
