### PR TITLE
fix(hetzner): missing error return in scale up/down

### LINKED ISSUE #6240: Cluster Autoscaler not backing off exhausted node group
**Which component are you using?**:

Cluster Autoscaler

**What version of the component are you using?**:

registry.k8s.io/autoscaling/cluster-autoscaler:v1.26.4

Component version:

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.26.6+k3s1
Kustomize Version: v4.5.7
Server Version: v1.26.6+k3s1
</pre></details>

**What environment is this in?**:

Hetzner Cloud

**What did you expect to happen?**:

When the cluster autoscaler is configured with a priority expander, and multiple node groups of differing priorities are provided, the cluster autoscaler should back-off after some time if the cloud provider fails to provision nodes in the high priority node group due to resource unavailability and proceed to lower priority node groups.

**What happened instead?**:

The high priority node group (in the below log pool1) has no resources available currently to provision the requested nodes.
The cluster autoscaler is stuck in a loop trying to provision nodes in the high-prio group and not proceeding to pool2 (lower prio, resources available). I've also tried to set `--max-node-group-backoff-duration=1m` with no effect.

```
W1101 05:15:05.399825       1 hetzner_servers_cache.go:94] Fetching servers from Hetzner API
I1101 05:15:15.806488       1 hetzner_node_group.go:438] Set node group draining-node-pool size from 0 to 0, expected delta 0
I1101 05:15:15.806519       1 hetzner_node_group.go:438] Set node group pool1 size from 1 to 1, expected delta 0
I1101 05:15:15.806525       1 hetzner_node_group.go:438] Set node group pool2 size from 0 to 0, expected delta 0
I1101 05:15:15.808727       1 scale_up.go:608] Scale-up: setting group pool1 size to 4
E1101 05:15:16.068533       1 hetzner_node_group.go:117] failed to create error: could not create server type ccx43 in region fsn1: we are unable to provision servers for this location, try with a different location or try later (resource_unavailable)
E1101 05:15:16.079704       1 hetzner_node_group.go:117] failed to create error: could not create server type ccx43 in region fsn1: we are unable to provision servers for this location, try with a different location or try later (resource_unavailable)
E1101 05:15:16.126786       1 hetzner_node_group.go:117] failed to create error: could not create server type ccx43 in region fsn1: we are unable to provision servers for this location, try with a different location or try later (resource_unavailable)
W1101 05:15:16.126816       1 hetzner_servers_cache.go:94] Fetching servers from Hetzner API
I1101 05:15:26.655179       1 hetzner_node_group.go:438] Set node group pool1 size from 1 to 1, expected delta 0
I1101 05:15:26.655243       1 hetzner_node_group.go:438] Set node group pool2 size from 0 to 0, expected delta 0
I1101 05:15:26.655257       1 hetzner_node_group.go:438] Set node group draining-node-pool size from 0 to 0, expected delta 0
I1101 05:15:26.660093       1 scale_up.go:608] Scale-up: setting group pool1 size to 4
E1101 05:15:26.948368       1 hetzner_node_group.go:117] failed to create error: could not create server type ccx43 in region fsn1: we are unable to provision servers for this location, try with a different location or try later (resource_unavailable)
E1101 05:15:26.981452       1 hetzner_node_group.go:117] failed to create error: could not create server type ccx43 in region fsn1: we are unable to provision servers for this location, try with a different location or try later (resource_unavailable)
E1101 05:15:27.044150       1 hetzner_node_group.go:117] failed to create error: could not create server type ccx43 in region fsn1: we are unable to provision servers for this location, try with a different location or try later (resource_unavailable)
```

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: v1
data:
  priorities: |
    10:
      - pool2
    20:
      - pool1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    spec:
      containers:
      - command:
        - ./cluster-autoscaler
        - --scale-down-unneeded-time=5m
        - --cloud-provider=hetzner
        - --stderrthreshold=info
        - --nodes=0:4:CCX43:FSN1:pool1
        - --nodes=0:4:CCX43:NBG1:pool2
        - --expander=priority
        env:
        - name: HCLOUD_IMAGE
          value: debian-11
        - name: HCLOUD_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: hcloud
        image: registry.k8s.io/autoscaling/cluster-autoscaler:v1.26.4
        name: cluster-autoscaler
      serviceAccountName: cluster-autoscaler
```

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by apricote**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

There is no Node Group/Autoscaling Group in Hetzner Cloud API, so the Hetzner provider implemented this by manually creating as many servers as needed.

The current code did not return any of the errors that could have happened. Without any returned errors, cluster-autoscaler assumed that everything was fine with the Node Group.

In cases where there is a temporary issue with one of the node groups (ie. Location is unavailable, no leftover capacity for the requested server type), cluster-autoscaler should consider this and try to scale up a different Node Group. This will automatically happen once we return an error, as cluster-autoscaler backs off from scaling Node Groups that have recently returned errors.

#### Which issue(s) this PR fixes:

Fixes #6240

#### Does this PR introduce a user-facing change?

```release-note
Fixed exhausted node groups not backing off for Hetzner Provider
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by apricote** [comment]
@elohmeier Could you test this PR to see if it fixes your issue? In my tests I have observed that the Node Group is now properly marked in an error state, but I do not have a production-like setup to test this with.

File: cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go [hunk 1]
```diff
@@ -91,7 +92,8 @@ func (n *hetznerNodeGroup) IncreaseSize(delta int) error {
 		return fmt.Errorf("delta must be positive, have: %d", delta)
 	}
 
-	targetSize := n.targetSize + delta
+	expectedDelta := delta
```
Comment (jooola) [inline cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go:95]: I struggle to understand the different between `n.targetSize`, `targetSize`, `delta` and `expectedDelta`. Can the naming be improved, or commented?

**Review by jooola — APPROVED** [review]

File: cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go (hunk 1 above)
Comment (apricote) [reply cluster-autoscaler/cloudprovider/hetzner/hetzner_node_group.go]: - `n.targetSize` is the count of servers that currently exists. Its exposed through `n.TargetSize()` and has additional docs there.
- `targetSize` is the count of servers that should exist after the current call. Its only used to verify against the configured limit. I have renamed this to `desiredTargetSize`
- `delta` is the count of additional nodes that should be added. This is "given" from the interface we implement.
- `expectedDelta` is the count of additional nodes we actually added. `delta` minus any failures that occured. I have renamed this to `actualDelta`.

Realistically this could be all removed and we can just get the count of nodes from the servers cache when we need it. This code is older than the cache, without a cache it makes sense to keep the exact number of servers around for these checks. Ill open another PR to remove it

**Review by jooola — APPROVED** [review]
The naming is definitely clearer!

**Comment by apricote** [comment]
@x13n Could you merge lgtm this? We only have a single `kubernetes` org member from our company.

**Comment by Shubham82** [comment]
Thanks @apricote 
/lgtm

**Comment by Shubham82** [comment]
@apricote, I will open PR to backport these changes in the supported previous releases.

**Comment by apricote** [comment]
Thanks! Sounds good! if you didn't get to until tomorrow morning (CEST) I'll open the PRs :)

**Comment by Shubham82** [comment]
Hi @apricote, I have raised the following PRs:
For CA 1.28 #7021 
For CA 1.29 #7022 
For CA 1.30 #7023
