### PR TITLE
cluster-autoscaler: Fix excessive calls to DescribeAutoScalingGroup

### LINKED ISSUE #45: cluster-autoscaler: Excessive calls to DescribeAutoScalingGroup
a.k.a https://github.com/kubernetes/contrib/issues/2541.
I'm recreating the issue here so that we can better track it from the corresponding and upcoming PR.

### PR DESCRIPTION
**Pull request by mumoshu**
By caching AWS refs for nodes/EC2 instances already known to be not in any of ASGs managed by cluster-autoscaler(CA).

Please beware of the edge case - this method is safe as long as users don't attach nodes by calling AttachInstances API after CA cached them. I believe, even if it was necessary, a warning in the documentation about the edge case is enough for now. If we really need to support the case, I will submit an another PR to invalidate the cache periodically so that CA can detect the formerly cached nodes are attached to ASG(s).

The docker image built from this branch is available for testing at `mumoshu/fix-excessive-describe-asg-calls`.

You can see that CA detects and remembers nodes in unmanaged ASGs so that it can prevent the nodes from triggering unnecessary `regenerateCache` invocations afterwards:

```
I0509 05:37:28.165739       1 leaderelection.go:204] succesfully renewed lease kube-system/cluster-autoscaler
I0509 05:37:28.824668       1 aws_manager.go:197] Regenerating ASG information for kube4-Asg1-5GX1OEW9YLPA-Workers-1WBDQUOBGXA6A
I0509 05:37:28.882084       1 aws_manager.go:188] Instance {Name:i-06079265fc8999d4c} is not in any ASG managed by CA. CA is now memorizing the fact not to unnecessarily call AWS API afterwards trying to find the unexistent managed ASG for the instance
I0509 05:37:28.882149       1 aws_manager.go:197] Regenerating ASG information for kube4-Asg1-5GX1OEW9YLPA-Workers-1WBDQUOBGXA6A
I0509 05:37:28.918931       1 aws_manager.go:188] Instance {Name:i-0c6c700cbcc62ed1d} is not in any ASG managed by CA. CA is now memorizing the fact not to unnecessarily call AWS API afterwards trying to find the unexistent managed ASG for the instance
I0509 05:37:28.918984       1 aws_manager.go:197] Regenerating ASG information for kube4-Asg1-5GX1OEW9YLPA-Workers-1WBDQUOBGXA6A
I0509 05:37:28.946945       1 aws_manager.go:188] Instance {Name:i-0e48a422f75ae6500} is not in any ASG managed by CA. CA is now memorizing the fact not to unnecessarily call AWS API afterwards trying to find the unexistent managed ASG for the instance
I0509 05:37:28.947044       1 aws_manager.go:197] Regenerating ASG information for kube4-Asg1-5GX1OEW9YLPA-Workers-1WBDQUOBGXA6A
I0509 05:37:28.984235       1 aws_manager.go:188] Instance {Name:i-0a8cb4932d32e1296} is not in any ASG managed by CA. CA is now memorizing the fact not to unnecessarily call AWS API afterwards trying to find the unexistent managed ASG for the instance
I0509 05:37:28.984272       1 static_autoscaler.go:197] Filtering out schedulables
I0509 05:37:28.984338       1 static_autoscaler.go:205] No schedulable pods
I0509 05:37:28.984356       1 static_autoscaler.go:211] No unschedulable pods
```

Resolves #45

### CODE REVIEW

**Comment by mwielgus** [comment]
cc: @andrewsykim

**Comment by mumoshu** [comment]
Hi @SleepyBrett!
This is the fix for https://github.com/kubernetes/contrib/issues/2541 you've reported last month.
Would you mind confirming if it works for you?
If you have a k8s 1.6 cluster, running your cluster-autoscaler from the docker image `mumoshu/fix-excessive-describe-asg-calls` would work.

**Comment by mwielgus** [comment]
Does it work with autodiscovery and dynamic config updates for aws?

**Comment by mumoshu** [comment]
@mwielgus Yes

**Comment by andrewsykim** [comment]
I'm on vacation, so won't be able to review til next week, sorry!

**Comment by mumoshu** [comment]
Hi @andrewsykim, sorry for rushing but I hope you could review this 🌷

File: cluster-autoscaler/cloudprovider/aws/aws_manager.go [hunk 1]
```diff
@@ -170,13 +172,21 @@ func (m *AwsManager) GetAsgForInstance(instance *AwsRef) (*Asg, error) {
 	if config, found := m.asgCache[*instance]; found {
 		return config, nil
 	}
+	if _, found := m.instancesNotInManagedAsg[*instance]; found {
+		// The instance is already known to not belong to any configured ASG
+		// Skip regenerateCache so that we won't unnecessarily call DescribeAutoScalingGroups
+		// See https://github.com/kubernetes/contrib/issues/2541
```
Comment (andrewsykim) [inline cluster-autoscaler/cloudprovider/aws/aws_manager.go]: Let's link to the issue in the new repo instead: https://github.com/kubernetes/autoscaler/issues/45

File: cluster-autoscaler/cloudprovider/aws/aws_manager.go [hunk 2]
```diff
@@ -170,13 +172,21 @@ func (m *AwsManager) GetAsgForInstance(instance *AwsRef) (*Asg, error) {
...
+	}
 	if err := m.regenerateCache(); err != nil {
 		return nil, fmt.Errorf("Error while looking for ASG for instance %+v, error: %v", *instance, err)
 	}
 	if config, found := m.asgCache[*instance]; found {
 		return config, nil
 	}
 	// instance does not belong to any configured ASG
+	glog.V(6).Infof("Instance %+v is not in any ASG managed by CA. CA is now memorizing the fact not to unnecessarily call AWS API afterwards trying to find the unexistent managed ASG for the instance", *instance)
+	m.instancesNotInManagedAsg[*instance] = struct{}{}
```
Comment (andrewsykim) [inline cluster-autoscaler/cloudprovider/aws/aws_manager.go]: Are there possible race conditions here? i.e. could a recently launched instance be added to this list because it was missing tags for short period of time?

File: cluster-autoscaler/cloudprovider/aws/aws_manager.go [hunk 3]
```diff
@@ -69,9 +70,10 @@ func CreateAwsManager(configReader io.Reader) (*AwsManager, error) {
 
 	service := autoscaling.New(session.New())
 	manager := &AwsManager{
-		asgs:     make([]*asgInformation, 0),
-		service:  service,
-		asgCache: make(map[AwsRef]*Asg),
+		asgs:                     make([]*asgInformation, 0),
+		service:                  service,
+		asgCache:                 make(map[AwsRef]*Asg),
+		instancesNotInManagedAsg: make(map[AwsRef]struct{}),
```
Comment (andrewsykim) [inline cluster-autoscaler/cloudprovider/aws/aws_manager.go]: I feel like we are adding a lot of complexity here by adding this field (`instancesNotInManagedAsg`). I was thinking of a solution where we can put `regenerateCache` in a separate loop and have it run every X seconds. Would you happen to know if that's a feasible solution?

Comment (mumoshu) [inline cluster-autoscaler/cloudprovider/aws/aws_manager.go]: Excuse me I'm not following you correctly but I'd rather suggest extracting a new object dedicated to efficiently fetch ASG data(probably named like `asgRegistry` which has the actual implementation of [`GetAsgForInstance`](https://github.com/kubernetes/autoscaler/pull/46/files/a55e8680777d9fdce4d0a8c78ea6443d9940d789#diff-ade7b95627ea0dd6b6f4deee7f24fa7eR169) if we'd want less complexity here.

After the change, `AwsManager` would just delegate `GetAsgForInstance` to `asgRegistry` and relevant struct members like `asgs`, `asgCache`, `instancesNotInManagedAsg` would move to `asgRegistry`.

The reasoning behind my suggestion is that we won't want to introduce an another gorountine just for calling `regenerateCache` - the less concurrent programming the more deterministic CA's behavior is/the happier our lives are? 😃 

And if you'd just like to `regenerateCache` every X seconds, theoretically, we can just do it by checking if elapsed time since the last regeneration is greater than X, in the very beginning of `regenerateCache`?

File: cluster-autoscaler/cloudprovider/aws/aws_manager.go (hunk 2 above)
Comment (mumoshu) [inline cluster-autoscaler/cloudprovider/aws/aws_manager.go]: @andrewsykim AFAIK, this func is called only after a K8S cluster notices the existence of the node.
Suppose the node exists, shouldn't it already have appropriate tags added, kubelet started, node registered, etc?

Comment (mumoshu) [inline cluster-autoscaler/cloudprovider/aws/aws_manager.go]: @andrewsykim Would you mind informing me which tag will be missed?

File: cluster-autoscaler/cloudprovider/aws/aws_manager.go (hunk 3 above)
Comment (andrewsykim) [inline cluster-autoscaler/cloudprovider/aws/aws_manager.go]: > And if you'd just like to regenerateCache every X seconds, theoretically, we can just do it by checking if elapsed time since the last regeneration is greater than X, in the very beginning of regenerateCache?

sounds good to me

File: cluster-autoscaler/cloudprovider/aws/aws_manager.go (hunk 2 above)
Comment (andrewsykim) [inline cluster-autoscaler/cloudprovider/aws/aws_manager.go]: Ahh, didn't know the instance would only be evaluated once it's registered with the master, this shouldn't be a problem then :)

File: cluster-autoscaler/cloudprovider/aws/aws_manager.go (hunk 3 above)
Comment (mumoshu) [inline cluster-autoscaler/cloudprovider/aws/aws_manager.go]: @andrewsykim Thanks for the confirmation 👍 

I'm going to include the work of extracting `asgRegistry` as I've described above in this PR.

However, regarding the periodic `regenerateCache` you've suggested, I'm not yet sure why it is needed.
AFAIK, cache regeneration is needed and done only when CA sees a k8s node for the first time. If we agree to assume a k8s node to not move among different ASGs, which seems reasonable to me, we won't need to periodically invalidate the asg cache.
What do you think?

Comment (andrewsykim) [inline cluster-autoscaler/cloudprovider/aws/aws_manager.go]: I can't say at the moment, the cluster-autoscaler code changed a lot from the last time I developed anything so I'm probably not the best person to make any calls here. What you're saying seems reasonable, though I'll need to read the code again to be sure.

Comment (mumoshu) [inline cluster-autoscaler/cloudprovider/aws/aws_manager.go]: @andrewsykim Thanks!
Then, would you mind if we proceed to get this merged without the periodic `regenerateCache` thing for now? Even without it, merging this doesn't make the situation worse. If we really need the regenerateCache improvement, we can submit a new github issue, right?

cc @mwielgus

Comment (mumoshu) [inline cluster-autoscaler/cloudprovider/aws/aws_manager.go]: > I'm probably not the best person to make any calls here

So am I!
I guess that we are the only contributors concerned to the AWS part of CA? 😄 
As this is being an OSS project, I suppose that one of maintainers, or one of active contributors appointed as responsible by a maintainer, would be eligible make decision.

Comment (mumoshu) [inline cluster-autoscaler/cloudprovider/aws/aws_manager.go]: @andrewsykim Oh, hey, I just realized that we already had the periodic regenerateCache [in our code-base](https://github.com/kubernetes/autoscaler/blob/e9c7cd0/cluster-autoscaler/cloudprovider/aws/aws_manager.go#L80-L86) 😃

**Comment by mumoshu** [comment]
@andrewsykim According to [our discussion](https://github.com/kubernetes/autoscaler/pull/46#discussion_r117912687), I've added 24a75816d178921079f5a283c5ffd6c1552df9a7 to avoid adding the `instancesNotInManagedAsg`  field directly to `AwsManager` while maintaining consistency throughout the codebase.
It would seem like a big change regarding LOC. However, basically, what I did is just splitting `AwsManager` into 3 types to keep each type simple.

**Comment by mumoshu** [comment]
To ensure I'm not breaking anything, I did some manual testing with 37b8225 and verified it scales up/down the cluster successfully as before.

**Comment by mumoshu** [comment]
Hi @MaciekPytel @mwielgus, thanks as always for maintaining CA 👍 
Would you mind providing your decisions on this, LGTM, need further changes, questions, another issues to be tracked in the future(more tests, more e2e, more README), etc?
Also, not very important but as a contributor, I personally prefer PRs getting merged relatively quick if they look not perfect but good enough so that we can keep constantly moving forward.

**Comment by mumoshu** [comment]
Anyway, as myself being a heavy user of K8S on AWS, I do want to fix this issue before CA 0.6.

**Comment by MaciekPytel** [comment]
@mumoshu We definitely want this for 0.6. 
It looks ok to me at a glance, but I don't have an AWS env to test this and I don't know AWS cloudprovider too well. @andrewsykim reviewed this and if it looks good to him and you confirm you tested it (running with non-managed ASG no longer causes constant cache regeneration, scale-up and scale-down work ok) , than I'm happy to merge this.

**Comment by mumoshu** [comment]
I'll take some time to test this again shortly.

**Comment by mumoshu** [comment]
@MaciekPytel @mwielgus I believe this is going to conflict with #107.
Would you mind merging #107 before this?

**Comment by mumoshu** [comment]
Rebased this onto #137 so that we can merge this after #107 and #137 without any conflict.
Please look at the last commit if you need to see only the changes made by this PR.
