### PR TITLE
Fix/aws asg unsafe decommission 5829

### LINKED ISSUE #5829: [AWS] Unsafe decomissioning of nodes when ASGs are out of instances
**Which component are you using?**: cluster-autoscaler

**What version of the component are you using?**: cluster-autoscaler 1.25.1

Component version: chart cluster-autoscaler-9.28.0

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.9-eks-0a21954", GitCommit:"eb82cd845d007ae98d215744675dcf7ff024a5a3", GitTreeState:"clean", BuildDate:"2023-04-15T00:37:59Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What environment is this in?**: AWS EKS

**What did you expect to happen?**: We are running EKS on managed nodes using cluster-autoscaler to dynamically scale up and down the sizes of the node groups. Unfortunately, sometimes AWS is unable to fulfil requests for scaling up (Could not launch On-Demand Instances. InsufficientInstanceCapacity). When that happens, cluster-autoscaler gets confused about the size of the ASG and sends unnecessary `SetDesiredCapacity` requests, which result in unsafe scaling down of the ASG (details below).
The expectation is that CA handles these situations transparently and does not scale down the ASG.

**What happened instead?**: We are observing the following behavior, by looking at both the CA logs and the CloudTrail logs of the requests sent. I don't know enough about the internal workings of the CA, so some of this is an assumption.
* Pods are pending, waiting for capacity in a given node group.
* CA wants to scale up this node group and sends a SetDesiredCapacity request to the ASG to increase the size (say from 3 -> 5). This happens async, so the CA fires off the request and goes back to doing different things. However it updates its internal representation of the ASG to be at capacity 5.
* ASG can’t scale up and returns that info to the CA.
* CA comes back around to the request and realizes the ASG is blocked. It updates its internal representation (back to 3)  but crucially for some reason it also updates the ASG, sending a number of SetDesiredCapacity requests, to revert the capacity back down to 3.
* In the meantime, a new instance might have successfully started, so the actual capacity of the ASG is now 4.
* So as a result to receiving the SetDesiredCapacity requests from the CA, the ASG terminates one (or more) of its running instances resulting in the unsafe scale down.

image

See the attached image that shows the sequence of events as well.

**How to reproduce it (as minimally and precisely as possible)**: Difficult to reproduce as it only happens when the AWS capacity issues occur. We are regularly observing this behavior though, I am happy to assist with more information.

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by ravisinha0506**
This merge resolves an issue in the Kubernetes Cluster Autoscaler where actual instances within AWS Auto Scaling Groups (ASGs) were incorrectly decommissioned instead of placeholders. The updates ensure that placeholders are exclusively targeted for scaling down under conditions where recent scaling activities have failed. This prevents the accidental termination of active nodes and enhances the reliability of the autoscaler in AWS environments.

#### What type of PR is this?

/kind bug

Optionally add one or more of the following kinds if applicable:
/kind api-change
/kind deprecation
/kind failing-test
/kind flake
/kind regression
-->

#### What this PR does / why we need it:
This PR prevents the Kubernetes Cluster Autoscaler from erroneously decommissioning actual nodes during scale-down operations in AWS environments, which could lead to unintended service disruptions.

#### Which issue(s) this PR fixes:
Fixes #5829

#### Does this PR introduce a user-facing change?
Fix an issue in the Kubernetes Cluster Autoscaler where actual AWS instances could be incorrectly scaled down instead of placeholders.

### CODE REVIEW

**Comment by drmorr0** [comment]
Hi, can you please keep all of the changes in a single PR?  It's very difficult in GH to compare changes and responses to feedback (or even remember what the feedback was) if you open a new PR for every change.

**Comment by ravisinha0506** [comment]
> Hi, can you please keep all of the changes in a single PR? It's very difficult in GH to compare changes and responses to feedback (or even remember what the feedback was) if you open a new PR for every change.

If you are referring to [this PR](https://github.com/kubernetes/autoscaler/pull/6818), it was authored by a different person. Hence, I have created a new PR for this change. 

Regarding the PR you mentioned (https://github.com/kubernetes/autoscaler/pull/6818), it was submitted by someone else. Therefore, I have opened a new pull request for the proposed modification.

**Comment by drmorr0** [comment]
I don't understand.  Multiple people can commit things to a single PR, and this change is clearly based on the previous one.  It's going to be very difficult to review if a new PR gets opened every single time a change is made (right now I don't even know which one is the correct one to review, since they are both still open).

I can add some comments here if this is going to be the PR to reference in the future, but in that case can we please close the other one?  Also please make sure we have a CLA signed and fix the issues with the linter in test-and-verify.

**Comment by kmsarabu** [comment]
Hi @drmorr0, Sorry for the multiple submissions. We have now closed the old PR and will use this PR for the review going forward. Please review and provide feedback. Thanks.

File: cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go [hunk 1]
```diff
@@ -308,6 +308,60 @@ func (m *asgCache) DeleteInstances(instances []*AwsInstanceRef) error {
...
+
+	placeHolderInstancesCount := m.GetPlaceHolderInstancesCount(instances)
+	// Check if there are any placeholder instances in the list.
+	if placeHolderInstancesCount > 0 {
+		// Log the check for placeholders in the ASG.
+		klog.V(4).Infof("Detected %d placeholder instance(s), checking recent scaling activity for ASG %s",
+			placeHolderInstancesCount, commonAsg.Name)
+
+		// Retrieve the most recent scaling activity to determine its success state.
+		isRecentScalingActivitySuccess, err = m.getMostRecentScalingActivity(commonAsg)
```
Comment (drmorr0) [inline cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go:322]: In the meeting, we talked about not getting the scaling activity at all, just getting the list of instances in the ASG and seeing if the number of placeholders was incorrect.  I think we can just get rid of this function entirely.

File: cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go [hunk 2]
```diff
@@ -308,6 +308,60 @@ func (m *asgCache) DeleteInstances(instances []*AwsInstanceRef) error {
...
+		}
+
+		if isRecentScalingActivitySuccess {
+			// recent scaling activity is successful but asgCache contains placeholders. This can also happen when the cache is stale
+			// hence we will succeed this step such that cache can be refreshed and scale down can be retried again.
+			klog.V(4).Infof("Detected %d placeholder instance(s), with no scaling issues. Skipping further scale down in %s",
+				placeHolderInstancesCount, commonAsg.Name)
+			return nil
+		} else {
+			asgDetail, err := m.getDescribeAutoScalingGroupResults(commonAsg)
```
Comment (drmorr0) [inline cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go:338]: Please call `m.awsService.getAutoscalingGroupsByNames` here

File: cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go [hunk 3]
```diff
@@ -352,6 +406,33 @@ func (m *asgCache) DeleteInstances(instances []*AwsInstanceRef) error {
 	return nil
 }
 
+func (m *asgCache) getDescribeAutoScalingGroupResults(commonAsg *asg) (*autoscaling.Group, error) {
```
Comment (drmorr0) [inline cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go:409]: Please remove, we don't need this function.

File: cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go [hunk 4]
```diff
@@ -624,3 +705,55 @@ func (m *asgCache) buildInstanceRefFromAWS(instance *autoscaling.Instance) AwsIn
 func (m *asgCache) Cleanup() {
 	close(m.interrupt)
 }
+
+func (m *asgCache) getMostRecentScalingActivity(asg *asg) (bool, error) {
```
Comment (drmorr0) [inline cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go:709]: Same as above.

**Review by drmorr0 — CHANGES_REQUESTED** [review]

File: cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go (hunk 2 above)
Comment (ravisinha0506) [reply cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go]: Done

File: cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go (hunk 3 above)
Comment (ravisinha0506) [reply cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go]: Done. Replaced with existing getAutoscalingGroupByName api

File: cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go (hunk 4 above)
Comment (ravisinha0506) [reply cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go]: Done

File: cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go (hunk 1 above)
Comment (ravisinha0506) [reply cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go]: Some times scaling activities can take longer to complete, so I wanted to ensure that scaling has indeed failed. But since we are looking at total active count if ec2 instances, I think it should be okay to remove this logic.

File: cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go [hunk 5]
```diff
@@ -308,46 +308,74 @@ func (m *asgCache) DeleteInstances(instances []*AwsInstanceRef) error {
...
+		err = m.setAsgSizeNoLock(commonAsg, activeInstancesInAsg)
+
+		if err != nil {
+			klog.Errorf("Error reducing ASG %s size to %d: %v", commonAsg.Name, activeInstancesInAsg, err)
+			return err
+		}
+		return nil
+	}
+
 	for _, instance := range instances {
```
Comment (drmorr0) [inline cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go:345]: This list still contains all of the placeholders, correct?  I don't see anything in the above code that is removing placeholder nodes from the instance list, although maybe I just missed it?  If that's correct, the code will fail on line 369 with the `m.awsService.TerminateInstanceInAutoScalingGroup(params)` function call, because AWS doesn't know anything about placeholder instances.

I think what we actually need to do is partition the instance list into two halves, the "placeholder" nodes and the "real" nodes.  Then we can say

```
if len(placeholders) > 0 {
  // fetch current ASG size 
  // change ASG target capacity to current size
}

for _, instance := range realInstances {
  // same logic as before, with the placeholder logic removed
}
```

File: cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go [hunk 6]
```diff
@@ -27,6 +25,7 @@ import (
 	"k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws-sdk-go/aws"
 	"k8s.io/autoscaler/cluster-autoscaler/cloudprovider/aws/aws-sdk-go/service/autoscaling"
 	"k8s.io/autoscaler/cluster-autoscaler/config"
+	"testing"
```
Comment (drmorr0) [inline cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go:28]: Why did the import order change here?

File: cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go [hunk 7]
```diff
@@ -603,7 +602,7 @@ func TestDeleteNodesWithPlaceholder(t *testing.T) {
 	err = asgs[0].DeleteNodes([]*apiv1.Node{node})
 	assert.NoError(t, err)
 	a.AssertNumberOfCalls(t, "SetDesiredCapacity", 1)
-	a.AssertNumberOfCalls(t, "DescribeAutoScalingGroupsPages", 1)
+	a.AssertNumberOfCalls(t, "DescribeAutoScalingGroupsPages", 2)
```
Comment (drmorr0) [inline cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go:605]: I think we need another test here that verifies the behaviour we're expecting -- specifically, create an ASG with (say) 7 instances and a desired capacity of (say) 10, and then call `DeleteNodes` with 5 placeholders and 2 real nodes.  Then we should see that the target size of the ASG goes down to 5.

**Review by drmorr0 — CHANGES_REQUESTED** [review]
I am trying to think through the implications of this again.  In the current version of code, the ASG size got decremented each time a placeholder was removed, which led to (potentially) some real instances getting terminated.  This was problematic for the reasons we've discussed, but one "positive" outcome is that the ASG size ended up being the "correct" size from cluster autoscaler's perspective.

With this change, we will no longer delete real instances, but if cluster autoscaler asks the cloud provider to delete 10 instances, there is a possibility that fewer of them will be deleted than requested.  As best as I can _tell_, cluster autoscaler doesn't actually care.  It looks as though the AWS provider [schedules a refresh of the ASG cache](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/aws_manager.go#L165) on the next main loop iteration, so at that point it should be up to date, and as far as I can tell nothing else really depends on "all the nodes" being deleted before the start of the next main loop.

But, my point is I'd like a second opinion on this change -- @gjtempleton are you available to take a look?

File: cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go (hunk 5 above)
Comment (ravisinha0506) [reply cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go:345]: The logic I added in this PR would adjust ASG size if placeholders are found and return nil at the end. Hence, the for loop wouldn't be executed in case of placeholders.

File: cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go (hunk 7 above)
Comment (ravisinha0506) [reply cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go:606]: Done. I have added context on the unit test to avoid any confusion.

File: cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go (hunk 5 above)
Comment (ravisinha0506) [reply cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go:344]: Handled this. Also verified through unit test

File: cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go (hunk 6 above)
Comment (ravisinha0506) [reply cluster-autoscaler/cloudprovider/aws/aws_cloud_provider_test.go:29]: Verify script was failing. This change is a result of `hack/update-gofmt.sh` script.

**Comment by drmorr0** [comment]
I think this addresses my concerns and is a better state than what we have now, but I'd still like a second set of eyes on it before we merge.

**Review by gjtempleton — COMMENTED** [review]
One small nit, but generally happy enough that the trade-off mentioned by @drmorr0 is only potentially going to result in instances hanging around for one extra iteration, so small increase in cost.

File: cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go [hunk 8]
```diff
@@ -308,46 +308,78 @@ func (m *asgCache) DeleteInstances(instances []*AwsInstanceRef) error {
 		}
 	}
 
+	placeHolderInstancesCount := m.GetPlaceHolderInstancesCount(instances)
+	// Check if there are any placeholder instances in the list.
+	if placeHolderInstancesCount > 0 {
+		// Log the check for placeholders in the ASG.
+		klog.V(4).Infof("Detected %d placeholder instance(s), checking recent scaling activity for ASG %s",
+			placeHolderInstancesCount, commonAsg.Name)
+
```
[the remark this answers is not in the document]
Comment (ravisinha0506) [reply cluster-autoscaler/cloudprovider/aws/auto_scaling_groups.go]: Thank you for pointing this out, I have updated this log statement

**Comment by gjtempleton** [comment]
Thanks!
/lgtm
/approve
