### PR TITLE
VPA - Always process OOM samples

### LINKED ISSUE #3078: [VPA] Incorrect OOM handling
It often happens that OOM memory values are not recorder.
In logs there are many entries like:

W0421 16:47:20.131118       1 cluster_feeder.go:406] Failed to record OOM {Timestamp:2020-04-21 16:46:24 +0000 UTC Memory:476450463 ContainerID:{PodID:{Namespace:vertical-pod-autoscaling-4228 PodName:hamster-6ddf9fb54d-wzzzd} ContainerName:hamster}}. Reason: error while recording OOM for {{vertical-pod-autoscaling-4228 hamster-6ddf9fb54d-wzzzd} hamster}, Reason: adding OOM sample failed

### PR DESCRIPTION
**Pull request by krzysied**
Disabling "outdated" samples filter when processing OOM samples.

/fixes #3078

### CODE REVIEW

File: vertical-pod-autoscaler/pkg/recommender/model/container.go [hunk 1]
```diff
@@ -134,7 +134,9 @@ func (container *ContainerState) GetMaxMemoryPeak() ResourceAmount {
 
 func (container *ContainerState) addMemorySample(sample *ContainerUsageSample, isOOM bool) bool {
 	ts := sample.MeasureStart
-	if !sample.isValid(ResourceMemory) || ts.Before(container.lastMemorySampleStart) {
+	// We are always processing OOM samples.
```
Comment (jbartosik) [inline vertical-pod-autoscaler/pkg/recommender/model/container.go:137]: Nit: We always process OOM samples

Comment (krzysied) [reply vertical-pod-autoscaler/pkg/recommender/model/container.go]: Done.
