### PR TITLE
[VPA] Use factory start to fill caches instead of separate informers

### LINKED ISSUE #8256: [VPA] SharedIndexInformer in the updater started multiple times
**Which component are you using?**:

/area vertical-pod-autoscaler

**What version of the component are you using?**:

Component version: 1.4.1, also tested in the master branch (pre-1.5.0)

**What k8s version are you using (`kubectl version`)?**:

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: v1.31.4
Kustomize Version: v5.4.2
Server Version: v1.30.13
</pre></details>

**What environment is this in?**:

hardware configuration

**What did you expect to happen?**:

SharedIndexInformer not started more than once

**What happened instead?**:

SharedIndexInformer is started multiple times and gives the following log:
```
I0620 18:12:54.429161   72290 shared_informer.go:535] "Warning: the sharedIndexInformer has started, run more than once is not allowed"
I0620 18:12:54.429159   72290 shared_informer.go:535] "Warning: the sharedIndexInformer has started, run more than once is not allowed"
I0620 18:12:54.429192   72290 shared_informer.go:535] "Warning: the sharedIndexInformer has started, run more than once is not allowed"
I0620 18:12:54.429197   72290 shared_informer.go:535] "Warning: the sharedIndexInformer has started, run more than once is not allowed"
I0620 18:12:54.429214   72290 shared_informer.go:535] "Warning: the sharedIndexInformer has started, run more than once is not allowed"
I0620 18:12:54.429225   72290 shared_informer.go:535] "Warning: the sharedIndexInformer has started, run more than once is not allowed"
```

**How to reproduce it (as minimally and precisely as possible)**:

just start vpa-updater

**Anything else we need to know?**
The factory is used twice with the same informers [here](https://github.com/kubernetes/autoscaler/blob/168a26ef428b9e4ddd2438114f25be58ae89ebc3/vertical-pod-autoscaler/pkg/target/fetcher.go#L84) and [here](https://github.com/kubernetes/autoscaler/blob/168a26ef428b9e4ddd2438114f25be58ae89ebc3/vertical-pod-autoscaler/pkg/target/controller_fetcher/controller_fetcher.go#L129)

### PR DESCRIPTION
**Pull request by yalosev**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
VPA controllers initialize a few informers, but the informers in `targetSelectorFetcher` and `controllerFetcher` are duplicated. If we start them one by one, it leads to a warning message because the caches are already synchronized.  
We can use the factory (it was made for this purpose) that was used to create these informers to start them and wait for all caches to sync.
Then caches will be populated without any warning messages.
```
I0621 01:27:41.171294   84656 reflector.go:430] "Caches populated" type="*v1.CronJob" reflector="pkg/mod/k8s.io/client-go@v0.33.0/tools/cache/reflector.go:285"
I0621 01:27:41.171294   84656 reflector.go:430] "Caches populated" type="*v1.Job" reflector="pkg/mod/k8s.io/client-go@v0.33.0/tools/cache/reflector.go:285"
I0621 01:27:41.171385   84656 reflector.go:430] "Caches populated" type="*v1.LimitRange" reflector="pkg/mod/k8s.io/client-go@v0.33.0/tools/cache/reflector.go:285"
I0621 01:27:41.266254   84656 reflector.go:430] "Caches populated" type="*v1.StatefulSet" reflector="pkg/mod/k8s.io/client-go@v0.33.0/tools/cache/reflector.go:285"
I0621 01:27:41.267590   84656 reflector.go:430] "Caches populated" type="*v1.ReplicationController" reflector="pkg/mod/k8s.io/client-go@v0.33.0/tools/cache/reflector.go:285"
I0621 01:27:41.268791   84656 reflector.go:430] "Caches populated" type="*v1.DaemonSet" reflector="pkg/mod/k8s.io/client-go@v0.33.0/tools/cache/reflector.go:285"
I0621 01:27:41.270992   84656 reflector.go:430] "Caches populated" type="*v1.ReplicaSet" reflector="pkg/mod/k8s.io/client-go@v0.33.0/tools/cache/reflector.go:285"
I0621 01:27:41.273464   84656 reflector.go:430] "Caches populated" type="*v1.Deployment" reflector="pkg/mod/k8s.io/client-go@v0.33.0/tools/cache/reflector.go:285"
```

Potentially, we could start the factory elsewhere, for example inside the `RunOnce` function of the updater.  
However, that would move it too far from the initialization logic, which might lead to bugs.  
So I decided to place the factory start function closer to the `NewSharedInformerFactory` call, right after all informers for this factory are initialized.

#### Which issue(s) this PR fixes:

Fixes #8256

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by adrianmoisey** [comment]
Thank you!
/lgtm 
/assign @omerap12

File: vertical-pod-autoscaler/pkg/admission-controller/main.go [hunk 1]
```diff
@@ -116,6 +116,16 @@ func main() {
 	recommendationProvider := recommendation.NewProvider(limitRangeCalculator, vpa_api_util.NewCappingRecommendationProcessor(limitRangeCalculator))
 	vpaMatcher := vpa.NewMatcher(vpaLister, targetSelectorFetcher, controllerFetcher)
 
+	stopCh := make(chan struct{})
+	defer close(stopCh)
+	factory.Start(stopCh)
+	informerMap := factory.WaitForCacheSync(stopCh)
+	for informerType, synced := range informerMap {
+		if !synced {
+			klog.V(0).InfoS("Initial sync failed", "kind", informerType)
```
Comment (omerap12) [inline vertical-pod-autoscaler/pkg/admission-controller/main.go]: When informer sync fails, it means that the controller doesn't have a complete view of the cluster state which could lead to incorrect behavior. So we should:
Use error level logging instead of info such as
```go
klog.ErrorS(nil, "Could not sync cache for "+string(kind))
```
and exit when sync fails to prevent operating with incomplete state.

File: vertical-pod-autoscaler/pkg/admission-controller/main.go [hunk 2]
```diff
@@ -116,6 +116,16 @@ func main() {
 	recommendationProvider := recommendation.NewProvider(limitRangeCalculator, vpa_api_util.NewCappingRecommendationProcessor(limitRangeCalculator))
 	vpaMatcher := vpa.NewMatcher(vpaLister, targetSelectorFetcher, controllerFetcher)
 
+	stopCh := make(chan struct{})
+	defer close(stopCh)
+	factory.Start(stopCh)
+	informerMap := factory.WaitForCacheSync(stopCh)
+	for informerType, synced := range informerMap {
```
Comment (omerap12) [inline vertical-pod-autoscaler/pkg/admission-controller/main.go]: For better readability, let's keep consistent variable naming:
```go
for kind, informer := range informersMap {
```

Comment (omerap12) [reply vertical-pod-autoscaler/pkg/admission-controller/main.go]: This is true for all components code.

File: vertical-pod-autoscaler/pkg/admission-controller/main.go (hunk 1 above)
Comment (omerap12) [reply vertical-pod-autoscaler/pkg/admission-controller/main.go]: This is true for all components code.

**Review by omerap12 — COMMENTED** [review]
Thanks for this. some comments from me

File: vertical-pod-autoscaler/pkg/admission-controller/main.go (hunk 1 above)
Comment (yalosev) [reply vertical-pod-autoscaler/pkg/admission-controller/main.go]: Totally agree with you. Fixed.
It was just a copypaste from the [current code](https://github.com/kubernetes/autoscaler/blob/vertical-pod-autoscaler-1.4.1/vertical-pod-autoscaler/pkg/target/controller_fetcher/controller_fetcher.go#L145). 
I thought it was weird, but maybe there was some idea behind it.

File: vertical-pod-autoscaler/pkg/admission-controller/main.go (hunk 2 above)
Comment (yalosev) [reply vertical-pod-autoscaler/pkg/admission-controller/main.go]: done

File: vertical-pod-autoscaler/pkg/admission-controller/main.go (hunk 1 above)
Comment (omerap12) [reply vertical-pod-autoscaler/pkg/admission-controller/main.go]: Yeah not sure why some components were treated this issue differently. anyway, look good now :)

**Review by omerap12 — APPROVED** [review]
Thanks for this!
/lgtm
/approve

File: vertical-pod-autoscaler/pkg/admission-controller/main.go (hunk 1 above)
Comment (adrianmoisey) [reply vertical-pod-autoscaler/pkg/admission-controller/main.go]: I should have commented before this was merged, but this does change the behaviour of the app. 
If someone had previously restricted the VPA to only resources they care about (for example, may be they denied it access to CronJobs) it (I think) wouldn't have failed to start, but now it will.
Is that enough of a concern to maintain the backwards compatibility?

Comment (omerap12) [reply vertical-pod-autoscaler/pkg/admission-controller/main.go]: The behavior was inconsistent to begin with actually:
https://github.com/kubernetes/autoscaler/pull/8259/files#diff-b234b6b39662bad81ddcb1d9cbc8be663d9984681045f370b7223f410e99c529L100
And
https://github.com/kubernetes/autoscaler/pull/8259/files#diff-b5382ad2d65ec680068c8afdce88601839c9322aa988378022a974db5acc9afdL144

So the idea is to avoid incorrect behavior of the VPA ( and it doesn't change the current behavior )

Comment (adrianmoisey) [reply vertical-pod-autoscaler/pkg/admission-controller/main.go]: Oh interesting, right, it seems fine to leave as-is then.
